### ISSUE TITLE
Scuole - C.SC.1.3 - UTILIZZO DI TEMI PER CMS

### ISSUE THREAD

**Issue by dg7dd** [italia/pa-website-validator#105]
Buongiorno.
Utilizzo il tema Design Scuole Italia v2.0.3 su WordPress 6.1, ma l'app mi restituisce flag giallo sul criterio in oggetto.

![screenshot](https://user-images.githubusercontent.com/72756285/201077518-edb56090-ff2a-43d0-8f2b-98b9f5ddedb9.png)

**Comment by tensor5** [comment]
Al momento il controllo del tema viene fatto sul file `style.css` (vedi [documentazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html), sezione 4.3). Dove essere esteso a tutti i CSS.

**Comment by sdi-sw** [comment]
![image](https://user-images.githubusercontent.com/88513374/206034269-af5c293e-c88e-4b9c-ae1e-16e0892b6c80.png)

Anche nel mio caso, pur utilizzando l'ultima versione del tema CMS del modello scuole, il controllo fallisce perché prende il primo file .css che trova che è quello del plugin del calendario...

**Comment by tensor5** [comment]
Sarà corretto nella prossima release.

**Comment by OProf77** [comment]
Questo tipo di controllo dovrebbe essere eliminato, usando Drupal9 tale punto alla conformità risulta sempre negativo.

**Comment by tensor5** [comment]
@OProf77 al momento non forniamo un tema Drupal per le scuole, questo è il motivo per cui il test non è “verde”, ma comunque non costituisce un fallimento.

**Comment by sdi-sw** [comment]
Dopo aver osservato l'output e il codice prodotto di un paio di siti web, tutti utilizzanti il tema scuole nella loro ultima versione, mi sembra che il criterio adottato, il controllo della versione del file style.css non sia efficace allo scopo.

Infatti fallisce non solo se si utilizza qualche plugin che utilizzi un file con lo stesso nome di quello del tema, ma anche quando, per ottimizzare il sito come richiesto dalla Raccomandazione progettuale R.SC.3.1, si utilizzi un plugin che ottimizzi la cache del sito, raggruppando i file .css ed inviando le versioni ottimizzate al browser che effettua l'accesso al sito. 

In questo secondo caso, ovviamente, non ci sarà nessun file style.css, pur utilizzando il tema originale, dando in questo secondo caso il messaggio "Il sito non sembra utilizzare il tema CMS del modello.", come segnalato dal collega  #dg7dd.

**Comment by OProf77** [comment]
> @OProf77 al momento non forniamo un tema Drupal per le scuole, questo è il motivo per cui il test non è "verde", ma comunque non costituisce un fallimento.

Ci è ben chiaro che non fornite un tema Drupal, tanto che lo stiamo preparando noi e nell'attuale versione beta raggiungiano in Criteri di conformità il 94%. Certo è che se il tema Drupal9 Porte Aperte sul Web viene riconosciuto il punteggio potrebbe raggiungere 100%. [https://beta.drupal9pasw.it/ ]
Qual è la percentuale per cui un sito scolastico può essere considerato conforme ai vostri criteri?

**Comment by tensor5** [comment]
La cosa fondamentale è che **nessuno** dei criteri (i vari "C.SC.*") dia risultato rosso; se anche uno solo è rosso il sito è non conforme.

**Comment by Giaimo-DTD** [comment]
Il test sull'utilizzo dei temi CMS è stato potenziato nella [nuova versione](https://github.com/italia/pa-website-validator/releases) effettuando la verifica in tutti i .css presenti in pagina

**Comment by IsabellaTarini** [comment]
Segnalo di star riscontrando lo stesso problema per il criterio C.SC.1.3 (Utilizzo temi per CMS), ovvero non viene rilevato l'utilizzo del tema Design Scuole Italia e in conseguenza non viene rilevata neanche la versione, restituendo quindi un parametro "giallo".

Tema installato: Design Scuole Italia, Versione: 2.5.1
Versione di Lighthouse utilizzata: scuole-2.7.2-Windows-x64
Sito sottoposto a valutazione: https://iisgalileipacinotti.edu.it/
Screenshot della restituzione:
![Screenshot issue non presente CMS C SC 1dot3](https://github.com/italia/pa-website-validator/assets/93941624/77493b30-b868-4c2b-8ff0-dc45803c3437)
