### ISSUE TITLE
Scuole - Localizzazione IP - Utilizzo CDN AWS

### ISSUE THREAD

**Issue by Sonic0** [italia/pa-website-validator#106]
Ciao a tutti,
Sto pubblicando alcuni siti di tipo 'scuola' tramite il cloud AWS e sto avendo problemi con la validazione dell'IP.
Per migliorare velocità, sicurezza e praticità sto utilizzando delle CDN CloudFront di fronte ai servizi che servono i contenuti, i quali sono localizzati in Europa. Tuttavia ho notato che per i database MaxMind tutti gli IP CloudFront sono localizzati in US (per esempio IPStack li localizza in Italia).
In questo caso, dove il datacenter è in territorio Europeo, è corretto che il controllo si fermi all'IP della CDN, facendo fallire il controllo?

Grazie

**Comment by Sonic0** [comment]
Ciao ragazzi, sapreste darmi una risposta per capire come dovrei muovermi al riguardo? Capisco che lato tecnico è una questione davvero complicata.

Sul fronte GDPR è un problema avere una CDN distribuita su territorio Europeo e Americano?

**Comment by tensor5** [comment]
Ciao @Sonic0, se è possibile dovresti configurare il CDN per replicare solo su regioni nel territorio europeo. Strano comunque una richiesta proveniente dall'Italia sia servita da un IP in USA.

**Comment by Sonic0** [comment]
Ciao @tensor5, grazie per la risposta.

Cerco di spiegare velocemente ed in breve: il servizio AWS Cloudfront essendo di tipo globale ha assegnati dei range di IP che AWS categorizza come "global" e registrati da AWS U.S. . Questi IP poi vengono assegnati agli Edge Location in giro per il mondo, compresi quelli in Europa, ed è per questo che ho problemi con il test.

Ora mi sto muovendo per cambiare infrastruttura in modo da evitare AWS CloudFront.
