### ISSUE TITLE
SCUOLE - Criterio C.SC.1.5: Voci di secondo livello

### ISSUE THREAD

**Issue by OProf77** [italia/pa-website-validator#123]
Le voci vengono rilevate con un risultato del 100%, ma restituisce un errore sull'ordinamento in quanto l'applicativo non rileva la voce PRESENTAZIONE all'interno dell'ordine

**Comment by tensor5** [comment]
Ciao @OProf77, l'audit relativo all'ordinamento sarà rimosso prossimamente.

**Comment by tensor5** [comment]
Fissato in c0ce054871eec4b907ce25d8cb3d7bbbeb1f5b30.
