### ISSUE TITLE
Criterio C.SI.1.4 CMS non utilizzato

### ISSUE THREAD

**Issue by LucaMonda** [italia/pa-website-validator#127]
Buongiorno,
In questo momento non sto utilizzando un tema CMS ma ottengo comunque un errore di colore giallo come da immagine
![image](https://user-images.githubusercontent.com/37303551/204764821-04062023-0ce1-4650-8a30-08815add2efb.png)
Il tema CMS non è obbligatorio giusto? Se non è obbligatorio, perchè ottengo l'errore?
Grazie!

**Comment by Giaimo-DTD** [comment]
Buongiorno, i risultati di colore giallo sono indicati come ["tolleranze"](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/report-e-risultati.html#legenda), quindi nella valutazione dei criteri di conformità ancora considerabili come "successo". Come correttamente indicato non è obbligatorio l'uso del tema CMS del modello, è solo una questione di rappresentazione del risultato.
