### ISSUE TITLE
SCUOLE - Voci di secondo livello non riconosciute con descrizione

### ISSUE THREAD

**Issue by OProf77** [italia/pa-website-validator#129]
Se nelle voci di secondo livello vengono inserite le descrizioni, l'app restituisce come mancanti le voci di secondo livello.

<img width="500" alt="Schermata 2022-12-05 alle 13 32 41" src="https://user-images.githubusercontent.com/58259159/205638207-f0ad01ca-5af6-49bf-a949-6cc10125fcc2.png">

**Comment by tensor5** [comment]
Ciao @OProf77, questo problema potrebbe essere stato risolto in 95cadba143b64712cdb4e3680ab24b4832b516a3, ti invito a provare. Grazie.
