### ISSUE TITLE
App si chiude istantaneamente quando si tenta di validare sito in ambiente di produzione.

### ISSUE THREAD

**Issue by Jhndo** [italia/pa-website-validator#130]
Buongiorno. quando cerchiamo di validare il sito inserendo il link https://icbrentonico.it e selezionando "ambiente di produzione" l'applicazione si chiude automaticamente. Se invece eseguiamo il programma con lo stesso link ma selezionando "Ambiente locale" la verifica va a buon fine e ci da i risultati ma ovviamente non verifica la conformita di cookies e https. Sapreste darci qualce suggerimento? Grazie mille.

**Comment by Sonic0** [comment]
Ciao, ho provato il test sul dominio indicato e non mi sembra ci siano errori se non per il fatto che _Lighthouse_ indica che è attivo un redirect (301) a https://www.icbrentonico.it/. Provando direttamente con record _www._ sparisce anche questo errore.

**Comment by Jhndo** [comment]
Buongiorno, rifacendo il test da un'altra postazione è andato tutto ok. Chiedo scusa per il disturbo e grazie per la disponibilità.

**Comment by Sonic0** [comment]
Nessun disturbo @Jhndo, ero di passaggio nel repo. Perfavore chiudi questa issue.
