### ISSUE TITLE
SCUOLE - 4.1 Criterio C.SC.1.1: Font non riconosciuti

### ISSUE THREAD

**Issue by OProf77** [italia/pa-website-validator#137]
Seguendo le indicazioni, ho inserito il data-element=”service-type” nelle sotto-voci del menù servizi (Famiglie e studenti - Personale Scolastico - Percorsi di studio) e il data-element="service-link" nella pagina che restituisce tutti i servizi, ma non rileva comunque i font.
Uso Drupal9 e gli URL delle pagine indicate sono: /servizi/famiglie-e-studenti, /servizi/personale-scolastico, /servizi/percorsi-di-studio

Potete controllare qui: beta.drupal9pasw.it

i data-element sono presenti nel tag

**Comment by tensor5** [comment]
Ciao @OProf77, ho provato a fare `document.querySelectorAll('[data-element="service-link"]')` dall'inspector in una pagina di servizi (https://beta.drupal9pasw.it/servizi/famiglie-studenti), e restituisce lista vuota. Un ulteriore problema è il fatto che https://beta.drupal9pasw.it/servizi/personale-scolastico non contiene link a pagine di servizi, quindi se l'app dovesse pescare quella pagina non troverebbe servizi e fallirebbe.

Inoltre, anche se non è relativo all'issue in questione, ti faccio notare che `[data-element="school-submenu"]` deve stare *solo* nel menù “Scuola”.
