### ISSUE TITLE
Scuole - C.SC.1.4: Voci di menù di primo livello

### ISSUE THREAD

**Issue by OProf77** [italia/pa-website-validator#138]
Inserendo una sola voce aggiuntiva al menù di primo livello la spunta diventa gialla e non resta verde. 
Dal controlla risulta che le voci di primo livello sono presenti così come descritte e nell'ordine indicato, quindi, essendo all'interno delle 3 voci aggiuntive previste, la spunta deve restare verde.

Vedi: beta.drupal9pasw.it (sito di riferimento della community DRUPAL Porte Aperte Sul Web)

**Comment by tensor5** [comment]
Il verde viene dato solo se non ci sono altre voci oltre a quelle obbligatorie, vedi https://docs.italia.it/italia/designers-italia/design-scuole-docs/it/versione-corrente/conformita-modello-scuola.html alla sezione “Voci di menù di primo livello”.
