### ISSUE TITLE
Scuole - C.SC.1.5: Validazione delle voci di menù di secondo livello

### ISSUE THREAD

**Issue by OProf77** [italia/pa-website-validator#139]
Nonostante siano inserite le voci di secondo livello così come indicato, la validazione restituisce dei calcoli errati.
Vedere foto allegata.
<img width="817" alt="Schermata 2022-12-09 alle 11 52 53" src="https://user-images.githubusercontent.com/58259159/206687000-b457ca97-7199-49b9-ae31-98c4fca587d6.png">

Le voci sono state inserite tutte, ma la percentuale è al 44%. E nonostante il 44% sia superiore al 30% richiesto, la spunta resta gialla.

Vedi: beta.drupal9pasw.it (sito di riferimento DRUPAL9 community Porte Aperte Sul Web)

**Comment by tensor5** [comment]
Vedi il commento riguardo a `[data-element="school-submenu"]` in #137.

**Comment by dg7dd** [comment]
Anche io ho inserito tutte le voci e ottengo solo 64%.
Specifico che nella versione precedente del validatore ottenevo 100%.
Utilizzo WordPress 6.1 e template Design Scuole Italia v2.1.2

**Comment by tensor5** [comment]
@dg7dd puoi passarmi l'URL del tuo sito? Se vuoi farlo privatamente puoi farlo su [Slack](https://slack.developers.italia.it/).

**Comment by dg7dd** [comment]
Nessun problema, lo pubblico qui: 

https://istitutosignorelli.edu.it

Ho ripetuto il test più volte anche oggi, dopo aver aggiornato il tema a v2.1.4: stesso esito.

Inoltre, anche il criterio C.SC.1.3 (Utilizzo di temi per CMS) mi restituisce flag giallo: ma ho letto che questo sarà corretto in una prossima release..?

**Comment by Giaimo-DTD** [comment]
Ciao, se le voci di "la scuola" sono rimaste invariate allora il risultato attuale è corretto e prima c'era un bug, perché vedo che vengono usate le 7 voci richieste, ma ne sono state usate anche altre 4 che non sono quelle del modello, quindi il risultato non può essere 100%. Si ottiene 100% se "Tutte le voci del menù di secondo livello usate rispecchiano quelle presenti nella documentazione" quindi non sono presenti voci non contemplate.

Riguardo il test sul CMS viene restituito risultato giallo nel caso in cui non venga utilizzato il tema del modello, ma i risultati gialli sono comunque "superati" :)
Diverso è se invece state usando il tema cms del modello e restituisce giallo, in quel caso è un bug

**Comment by Giaimo-DTD** [comment]
Per il risultato ottimale sì, ma sono ammesse comunque un numero di voci aggiuntive fino ad un rapporto del 30%. Attenzione solo che l'app verifica per ora solo la prima voce del menu, ma il calcolo come da criterio di conformità si applica a tutte le voci di secondo livello di tutte le voci di primo livello.

Per il tema sì, allora è un bug, la versione 2.1.4 dovrebbe dare risultato verde :) Può mettere un'immagine del risultato che viene visualizzato?

**Comment by dg7dd** [comment]
Eccolo qua![image](https://user-images.githubusercontent.com/72756285/207112934-90403418-0dd3-4cab-a1d6-f70e700aafce.jpeg)

**Comment by OProf77** [comment]
> Per il risultato ottimale sì, ma sono ammesse comunque un numero di voci aggiuntive fino ad un rapporto del 30%. Attenzione solo che l'app verifica per ora solo la prima voce del menu, ma il calcolo come da criterio di conformità si applica a tutte le voci di secondo livello di tutte le voci di primo livello.
> 
Ma quindi il data-element="school-submenu" deve essere inserito nel tag <ul> di tutti i menù di secondo livello?

**Comment by Giaimo-DTD** [comment]
no, va solo nella prima voce di menu "scuola", il calcolo dell'app viene fatto solo su quella voce, in futuro verrà espanso anche alle altre. Intendevo che il calcolo totale per la verifica del rispetto del criterio invece è da fare su tutti

**Comment by flaggz** [comment]
ho trovato un bug
se è presente un mobile menu oltre al main menu, con lo stesso codice HTML, vengono contate le voci due volte e quindi restituisce un valore non veritiero
l'ho verificato rimuovendo il mobile ed infatti il report restituisce la validità del 100%
template custom ovviamente

**Comment by Giaimo-DTD** [comment]
potresti passarci la url in modo da verificare? anche privatamente su slack se necessario, la mia utenza è @Federico Giaimo

**Comment by Giaimo-DTD** [comment]
Nella [nuova versione 2.0 dell'app](https://github.com/italia/pa-website-validator/releases) questa casistica dovrebbe essere risolta
