### ISSUE TITLE
Le schede dei servizi non vengono validate correttamente

### ISSUE THREAD

**Issue by flaggz** [italia/pa-website-validator#141]
nonostante la scheda dei servizi sia presente con la formattazione corretta non viene né individuata né validata

<img width="787" alt="Screenshot 2022-12-09 alle 16 08 10" src="https://user-images.githubusercontent.com/7655589/206732914-a8eecc6c-c850-4965-956b-212e74516f49.png">

HTML lista schede
<article id="post-4780" class="blog-grid-3 post-4780 post type-post status-publish format-standard hentry category-percorsi-di-studio category-servizi-famiglie-e-studenti category-servizi-personale-scolastico">
	<div class="content-inner">
				<div class="entry-content">
			
			<header class="entry-header">
				<div class="entry-contain">
					<h2 class="entry-title"><a href="https://www.redacted.edu.it/2022/12/07/prova-servizio/" rel="bookmark" data-element="service-link" role="link">Prova servizio</a></h2>							<ul class="entry-meta">
							<li class="entry-date">
					<span>Data</span>
					<span class="value"> 7 Dicembre 2022</span>
				</li>
				
		</ul>
						</div>
			</header>
			<div class="entry-grid-meta">
									<div class="date">
						<i class="fa fa-calendar"></i>7 Dicembre 2022					</div>
								</div>
			<div class="entry-summary">
				<p>prova</p>
			</div>
			<div class="readmore">
				<a href="https://www.redacted.edu.it/2022/12/07/prova-servizio/" role="link">Read More</a>
			</div>
		</div>
	</div>
</article>

HTML scheda
```
<main id="main" class="site-main col-sm-9 alignleft">    
<div class="page-content">
<article id="post-4780" class="post-4780 post type-post status-publish format-standard hentry category-servizi-famiglie-e-studenti category-servizi-personale-scolastico">
<div class="page-content-inner">
<ul data-element="”breadcrumb”"><li>Servizi Famiglie e studenti</li></ul>
<header class="entry-header">
<h1 class="entry-title" data-element="service-title">Prova servizio</h1>			<h5 data-element="service-description"></h5>
</header>
<!-- .entry-header -->
<div class="entry-content">
<h5><a id="cose" role="link">Cos'è</a></h5>
<p>prova</p>
<h5><a id="a_cosa_serve" role="link">A cosa serve</a></h5>
<p data-element="used-for">Boh</p>
<h5><a id="come_si_accede_al_servizio" role="link">Come si accede al servizio</a></h5>
<p>come si accede al servizio</p>
<h5>Luoghi in cui viene erogato il servizio</h5>
<ul data-element="places">
<li>
<div class="location-title">
<span>Indirizzo</span>
</div>
<div class="location-content">
<p>Via Roma, 6, 01000 Roma RM</p>
</div>
</li>
<li>
<div class="location-title">
<span>Orari</span>
</div>
<div class="location-content">
<p>Dalle 8:00 alle 13:00</p>
</div>
</li>
<li>
<div class="location-title">
<span>GPS</span>
</div>
<div class="location-content">
<p>https://goo.gl/maps/2jbwmzys31hJW43c7</p>
</div>
</li>					
<li>
<div class="location-title">
<span>Email</span>
</div>
<div class="location-content">
<p><a href="mailto:redactedv@istruzione.it" role="link">redactedv@istruzione.it</a></p>
</div>
</li>
<li>
<div class="location-title">
<span>PEC</span>
</div>
<div class="location-content">
<p><a href="mailto:redactedv@pec.istruzione.it" role="link">redactedv@pec.istruzione.it</a></p>
</div>
</li>
<li>
<div class="location-title">
<span>Telefono</span>
</div>
<div class="location-content">
<p>+39 02 12345678</p>
</div>
</li>
</ul>
<h5><a id="cosa_serve" role="link">Cosa serve</a></h5>
<p>Carta d'intensità</p>
<h5><a id="tempi_scadenze" role="link">Tempi e scadenze</a></h5>
<p>ND</p>
<h5><a id="struttura_responsabile" role="link">Struttura responsabile del servizio</a></h5>
<p data-element="structures"><a href="https://www.redacted.edu.it" role="link">https://www.redacted.edu.it</a></p>
<p data-element="metadata">Pubblicato: 7 Dicembre 2022</p>
<p>Stato: Attivo</p>
Argomenti 
<a href="#" data-element="topic-list" role="link">Aula informatica</a>
<a href="#" data-element="topic-list" role="link">Bacheca sindacale</a>
<p>Eccetto dove diversamente specificato, questo articolo è stato rilasciato sotto Licenza Creative Commons Attribuzione 4.0 Italia.</p>
<ul data-element="page-index">
<li><a href="#cose" role="link">Cos’è</a></li>
<li><a href="#come_si_accede_al_servizio" role="link">Come si accede al servizio</a></li>
<li><a href="#cosa_serve" role="link">Cosa serve</a></li>
<li><a href="#tempi_scadenze" role="link">Tempi e scadenze</a></li>
<li><a href="#struttura_responsabile" role="link">Contatti</a></li>
<li><a href="#metadata" role="link">Ulteriori informazioni</a></li>
</ul>
</div>
<div class="date">
7 Dicembre 2022						</div>
</div>
</div>
</div>
</article>
</div>
</main>
```

**Comment by tensor5** [comment]
Ciao @flaggz, puoi passarmi l'url del sito in questione (anche privatamente su [Slack](https://slack.developers.italia.it/))?

**Comment by profVRCP2** [comment]
Succede anche al sito su cui sto lavorando in questi giorni. Ho lasciato le impostazioni iniziali del menù servizi e creato i servizi ma la app 1.1 non li trova. Come devo comportarmi? Tutti gli altri test sono superati.

**Comment by profVRCP2** [comment]
https://www.copernicopasoli.edu.it/wp/

**Comment by profVRCP2** [comment]
Grazie mille. Mi serve comunque un po' di assistenza per l'inserimento del data-element in modo corretto. Lo devo inserire direttamente nell'HTML oppure da qualche parte nella bacheca WP?

**Comment by flaggz** [comment]
> 

non ti posso aiutare perché utilizzo un template custom e quindi l'ho inserito nel PHP
nel tuo caso, utilizzando il template ufficiale, ci sarà sicuramente il modo per indicare automaticamente i data element
prova a dare un'occhiata nella sezione Aspetto -> Menu

**Comment by HshMatera** [comment]
Buongiorno, sto avendo anche io lo stesso problema
**Metatag non presenti o errati** 
areaServed.name.,availableChannel.serviceLocation.address.addressLocality
vengono riscontrati errori nei metatag riferiti al post_type “**Luogo**” se non vengono popolati tutti i rispettivi campi, anche non essendo obbligatori come riportato nell’Architettura dell’informazione Modello Comuni Designers Italia.

**Comment by Giaimo-DTD** [comment]
Buongiorno @HshMatera , il problema per cui è stata aperta questa issue è stato risolto, se ce ne sono altri per favore apri una issue apposita così verifichiamo puntualmente il problema
