### ISSUE TITLE
Le opzioni di comando vengono ignorate

### ISSUE THREAD

**Issue by flaggz** [italia/pa-website-validator#142]
Qualsiasi parametro venga passato da linea di comando viene ignorato
Sarebbe comodo poter lanciare la valutazione senza indicare ogni volte l'url del sito e se è local o online

<img width="682" alt="Screenshot 2022-12-09 alle 16 13 19" src="https://user-images.githubusercontent.com/7655589/206733564-130c12ee-57e9-437a-a0c5-c3226787f3ba.png">

**Comment by tensor5** [comment]
Ciao @flaggz, se sei pratico di NodeJS puoi seguire le istruzioni [qui](https://github.com/italia/pa-website-validator#installazione-globale) e usare la storia della riga di comando per evitare di dover riscrivere l'URL ogni volta.

**Comment by flaggz** [comment]
> Ciao @flaggz, se sei pratico di NodeJS puoi seguire le istruzioni [qui](https://github.com/italia/pa-website-validator#installazione-globale) e usare la storia della riga di comando per evitare di dover riscrivere l'URL ogni volta.

utilizzando il validatore anche da PC con restrizioni di amministrazione non è sempre possibile utilizzare NodeJS
sarebbe comodo avere i parametri da passare al CLI anche per i binari compilati

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
