### ISSUE TITLE
Controllo vocabolari 

### ISSUE THREAD

**Issue by Jhndo** [italia/pa-website-validator#150]
Buongiorno, quando eseguiamo la verifica sul nostro sito (https://www.icbrentonico.it/) ci restituisce sempre errore nella sezione R.SC.1.1 - VOCABOLARI CONTROLLATI però tutti gli argomenti non presenti nell'elenco del modello che ci vengono suggeriti sono presenti sia sul nostro sito che sulla documentazione del modello. Qualche suggerimento?

Grazie mille.

![immagine](https://user-images.githubusercontent.com/113902185/208051019-706cbf0d-eba9-4421-bae9-52a88bc7d0aa.png)

**Comment by Giaimo-DTD** [comment]
Buongiorno, le voci riportate non sono in realtà presenti nella [documentazione](https://docs.google.com/spreadsheets/d/1MoayTY05SE4ixtgBsfsdngdrFJf_Z2KNvDkMF3tKfc8/edit#gid=2135815526), quindi vengono indicate come non ammesse
