### ISSUE TITLE
Raccomandazioni progettuali - servizi

### ISSUE THREAD

**Issue by Jhndo** [italia/pa-website-validator#151]
Buongiorno, nella categoria Raccomandazioni Progettuali spesso ci restituisce come problema la mancanza delle voci:
- "orari" in alcuni servizi, ma tale voce non è presente quando si impostano i servizi. 
- Tipologia servizio, anche se è correttamente impostata.

![Screenshot 2022-12-22 at 07-43-45 Lighthouse Report](https://user-images.githubusercontent.com/113902185/209111202-8512d283-a773-46d4-bfa4-2d02e579fc6f.png)
![Screenshot 2022-12-22 at 07-42-41 Lighthouse Report](https://user-images.githubusercontent.com/113902185/209111208-fa602f7d-07e5-48b0-b001-057807c6726e.png)

**Comment by Jhndo** [comment]
Succede anche nei criteri di conformità.

![Screenshot 2022-12-22 at 12-52-24 Lighthouse Report](https://user-images.githubusercontent.com/113902185/209129346-a8c9d3ea-f0d4-42fe-af76-c86dce153285.png)

**Comment by Giaimo-DTD** [comment]
Buongiorno, nella scheda indicata, all’interno della scheda luogo, manca di fatto la voce “orari”. Cosa intende che la voce manca quando si impostano i servizi?
Invece riguardo “Tipologia servizio” è la breadcrumb ad essere errata: Home/Servizi/Personale docente/Posta elettronica DOCENTI non contiene le voci obbligatorie “Famiglie e studenti” o Personale scolastico”

**Comment by Giaimo-DTD** [comment]
Nella [nuova versione dell'app](https://github.com/italia/pa-website-validator/releases) questa casistica dovrebbe essere risolta
