### ISSUE TITLE
 C.SI.1.3 - Schede informative di servizio per il cittadino

### ISSUE THREAD

**Issue by enzobuso** [italia/pa-website-validator#153]
Rispetto ai requisiti:
Cittadino Informato - [C.SI](http://c.si/).1.3 - Schede informative di servizio per il cittadino
Rileviamo che l'app di verifica non riconosce le categorie che contengono il carattere virgola ",".

**Comment by Giaimo-DTD** [comment]
Ciao, l'errore è ancora presente nella nuova versione? Se sì, puoi fornirci l'url della pagina così facciamo una verifica? Grazie
