### ISSUE TITLE
Problema con "Time to Interactive"

### ISSUE THREAD

**Issue by LucaMonda** [italia/pa-website-validator#156]
Buongiorno, generando il report dal sito ho notato che il time to interactive risulta molto più alto di quello aspettato, questo perchè sembra sommare tutte i secondi di ogni risorsa che viene caricata, ma se le risorse in questione vengono caricate in parallelo? Perchè in questo momento mi ritrovo con un TTI molto più alto rispetto alla normale attività del sito (circa 2 secondi).

**Comment by tensor5** [comment]
Ciao @LucaMonda, il nostro tool si affida a LightHouse per il calcolo del TTI, quindi non so dirti di preciso come valuta i tempi delle risorse caricate in parallelo.
