### ISSUE TITLE
C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT controllo non superato

### ISSUE THREAD

**Issue by profVRCP2** [italia/pa-website-validator#157]
<img width="1128" alt="conformit" src="https://user-images.githubusercontent.com/122117209/214152514-667572f6-e83c-4839-80ac-bac5fe6b744f.png">
Pur utilizzando il tema Word Press fornito per le scuole questo criterio di conformità non viene superato. Il sito in questione è https://www.copernicopasoli.edu.it/wp/. Potreste darmi indicazioni su come superarlo?

**Comment by Giaimo-DTD** [comment]
Devono essere presenti i data element come indicato in [documentazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html#criterio-c-sc-1-1-coerenza-dell-utilizzo-dei-font). Le consiglio di effettuare il test con la [nuova versione di App di valutazione](https://github.com/italia/pa-website-validator/releases)
