### ISSUE TITLE
Su Windows l'app si apre e si chiude subito: errore caxa stub con versione 1.1.0 Win64x 

### ISSUE THREAD

**Issue by gguglielmotto** [italia/pa-website-validator#158]
Buongiorno,
eseguendo la versione 1.1.0 del 7/12/2022 sia di Comuni che Scuole, ricevo questo messaggio di errore non appena lancio l'applicazione:

caxa stub: Failed to run command: exec: "C:\\Users\\ggugl\\AppData\\Local\\Temp/caxa/applications/app-valutazione-scuole\\fggviykv7q/0/node_modules/.bin/node": file does not exist

Eseguendo la versione 1.0.13 tutto funziona senza problemi.

 Il SO è Win11 versione 21H2

**Comment by gguglielmotto** [comment]
Il problema si risolve così: svuotando la cartella temp, quindi in questo caso basta cancellare tutto il contenuto di C:\\Users\\ggugl\\AppData\\Local\\Temp e poi rilanciare l'app. In effetti poi funziona. 
Non sarebbe il caso di controllare questo errore e fornire una indicazione più leggibile e utile?

**Comment by malikmalhan** [comment]
> Il problema si risolve così: svuotando la cartella temp, quindi in questo caso basta cancellare tutto il contenuto di C:\Users\ggugl\AppData\Local\Temp e poi rilanciare l'app. In effetti poi funziona. Non sarebbe il caso di controllare questo errore e fornire una indicazione più leggibile e utile?

errore ancora presente su 2.11.1 e risolto con svuotamento temp come indicato

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
