### ISSUE TITLE
Segnalazione errata voce mancante "Tempi e scadenza" - C.SI.3

### ISSUE THREAD

**Issue by NicolaZivago** [italia/pa-website-validator#160]
Il validatore non identifica la voce "Tempi e scadenze" all'interno della scheda servizio.
La voce è presente nell'indice e nel contenuto scheda.

**Comment by Giaimo-DTD** [comment]
Nella [nuova versione dell'app](https://github.com/italia/pa-website-validator/releases) questa casistica dovrebbe essere risolta
