### ISSUE TITLE
App non funziona su Windows

### ISSUE THREAD

**Issue by dg7dd** [italia/pa-website-validator#161]
Buongiorno. Da qualche giorno provo a far partire l'eseguibile (v1.1.0 per Scuole) su Windows (sia 7 che 11) ma senza successo. Si apre per un istante il prompt comandi e si richiude subito.

**Comment by attiliopecora** [comment]
confermo succede anche a me. WINDOWS 11

**Comment by Jhndo** [comment]
è successo anche a me, dopo aver "C:\Users\UTENTE\AppData\Local\Temp" è tornata a funzionare.

**Comment by dg7dd** [comment]
Ok, risolto svuotando la cartella *\Temp

Grazie
