### ISSUE TITLE
Segnalazione criterio C.SI.2.3 (FAQ) non soddisfatto.

### ISSUE THREAD

**Issue by alessandroc75** [italia/pa-website-validator#162]
Pur essendo soddisfatte le relative "condizioni di successo" e i "requisiti tecnici" del criterio, l'app di valutazione dell'adesione per il modello Comuni risponde con triangolo rosso (fallimento).

**Comment by alessandroc75** [comment]
A supporto del criterio non validato allego relativa risposta dell'app di valutazione e codice sorgente (parte della sezione footer del sito) con url alla pagina esistente "domande-frequenti".

![C_SI_2_3](https://user-images.githubusercontent.com/123944426/215479209-cba6ca74-39cf-40c5-8e48-9f6335cb7658.png)

![Sorgente](https://user-images.githubusercontent.com/123944426/215479257-760d38f7-1657-42eb-963b-5397cd4213df.png)

**Comment by Giaimo-DTD** [comment]
casistica analoga a https://github.com/italia/pa-website-validator/issues/163#issuecomment-1451811054
