### ISSUE TITLE
Segnalazione criterio C.SI.3.3 non soddisfatto.

### ISSUE THREAD

**Issue by alessandroc75** [italia/pa-website-validator#163]
Pur essendo soddisfatte relative "condizioni di successo" e "requisiti tecnici" a supporto del criterio non validato (triangolo rosso - fallimento) allego relativa risposta dell'app di valutazione per il modello Comuni e codice sorgente (parte della sezione footer del sito) con url alla pagina esistente "privacy_informative".

![C_SI_3_3](https://user-images.githubusercontent.com/123944426/215503076-7a1fa41d-5eb1-483b-8571-98ac1b673857.png)

![Sorgente_C_SI_3_3](https://user-images.githubusercontent.com/123944426/215503167-d0e05aab-46bb-432c-a7b8-90ae7a7281c8.png)

**Comment by Giaimo-DTD** [comment]
la pagina viene rilevata come non esistente e non sicura come indicato nelle rispettive colonne, può essere il risultato sia dovuto al fatto che è in ambiente di staging. Si consiglia di rieffettuare la verifica in ambiente di produzione e usando la [nuova versione](https://github.com/italia/pa-website-validator/releases) dell'app di valutazione
