### ISSUE TITLE
Scuole - R.SC.1.2

### ISSUE THREAD

**Issue by OProf77** [italia/pa-website-validator#164]
Buongiorno, riporto alcune problematiche in merito alla conformità R.SC.1.2
- Per la sezione del bredcrumb, non viene riconosciuta la TIPOLOGIA SERVIZIO se è presente qualche tag in più dopo il tag <a>.
`<ol class="breadcrumb" data-element="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Home</a>
    <span class="separator">&gt;</span>
  </li>
  <li class="breadcrumb-item">
    <a href="/servizi">Servizi</a>
    <span class="separator">&gt;</span>
  </li>
  <li class="breadcrumb-item">
    <a href="/servizi/famiglie-e-studenti">Famiglie e Studenti</a>
    <span class="separator">&gt;</span>
  </li>
  <li class="breadcrumb-item active" aria-current="page">
    Iscrizioni a Scuola
  </li>
</ol>`

Se all'attuale codice viene tolto il tag <span> con la classe "separator"(Classe della libreria Bootstrap Italia) allora ottengo la validazione.

- Nel controllo dei campi obbligatori della scheda SERVIZIO, se viene inserita una variabile per la label, il campo non viene riconosciuto, se vien inserito il testo specifico(Come si accede, Ulteriori Informazioni, ecc...), allora viene riconosciuto.

**Comment by Giaimo-DTD** [comment]
Buongiorno, ci potresti fornire l'url del sito in modo da riprodurre il caso?

**Comment by OProf77** [comment]
Sembra che il problema sia rientrato con la versione 2.0.2
