### ISSUE TITLE
validazione sito scuola in Joomla

### ISSUE THREAD

**Issue by lia55556** [italia/pa-website-validator#165]
Il mio sito è sviluppato con JOOMLA e utilizza il template zhong. L'app di valutazione scuola funziona correttamente con questo CMS? Ad esempio, ho cambiato il font con uno di quelli indicati (Titillium web), sul sito risulta attivo nella visualizzazione, ma l'app non me lo riscontra.

**Comment by tensor5** [comment]
L'app non supporta JOOMLA, ma non è un problema, puoi tranquillamente ignorare il warning relativo all'uso del CMS.

Il font invece è un requisito, puoi allegare uno screenshot dell'audit fallito?

**Comment by lia55556** [comment]
Ecco lo screenshot del report, inoltre ti mando l'url del mio sito e lo screenshot del pannello di amministratore di joomla dove si vede chiaramente che il font è stato applicato:

https://www.iisspietrosette.edu.it/

**Comment by tensor5** [comment]
Manca il `data-element` necessario a trovare la scheda servizio su cui viene fatto il test. [Qui][1] e [qui][2] trovi la documentazione.

[1]: https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html
[2]: https://designers.italia.it/modello/scuole/

**Comment by lia55556** [comment]
Questo già la so, ho letto e riletto la documentazione, ma come faccio ad inserire questi data-element? Devo mettere mano a tutto il codice generato da joomla? mi sembra un lavoro immane, si fa prima a farlo da capo il sito; oppure c'è un modo per farlo fare automaticamente a joomla? ovviamente la cosa vale anche per tutti gli altri criteri

**Comment by tensor5** [comment]
Non conosco Joomla nello specifico, ma direi che devi mettere mano al template e aggiungere i `data-element` alle tag che lo richiedono.
