### ISSUE TITLE
comuni-1.2.0-pre.1-macOS-arm64 non si avvia su MacBook Pro

### ISSUE THREAD

**Issue by NicolaZivago** [italia/pa-website-validator#167]
Ciao, comuni-1.2.0-pre.1-macOS-arm64 non si avvia su MacBook Pro (16", 2021) macOS Monterey vers. 12.6

A terminale vedo:

Last login: Wed Mar  1 08:53:13 on ttys000
nicola@MacBook-Pro-di-Nicola ~ % /Users/nicola/Desktop/comuni-1.2.0-pre.1-macOS-arm64/app-valutazione-comuni ; exit;
dyld[902]: Library not loaded: '/nix/store/982677wbm4alp9f9hy07f1difhm32y7f-libuv-1.44.2/lib/libuv.1.dylib'
  Referenced from: '/private/var/folders/n6/4zy2fkzs4rq35z_6fcktpr8r0000gn/T/caxa/applications/app-valutazione-comuni/tblm4dmlwi/0/node_modules/.bin/node'
  Reason: tried: '/nix/store/982677wbm4alp9f9hy07f1difhm32y7f-libuv-1.44.2/lib/libuv.1.dylib' (no such file), '/usr/local/lib/libuv.1.dylib' (no such file), '/usr/lib/libuv.1.dylib' (no such file)

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Processo completato]

**Comment by tensor5** [comment]
@NicolaZivago, grazie mille per la segnalazione. Prova a riscaricare il binario, e dovrebbe funzionare.

**Comment by NicolaZivago** [comment]
@tensor5 grazie adesso si avvia correttamente, chiudo.
