### ISSUE TITLE
URGENTE risultati errati app scuole

### ISSUE THREAD

**Issue by pilcom2023** [italia/pa-website-validator#170]
C.SC.1.1 FONT, C.SC.1.2 LIBRERIA , C.SC.23 COOKIE con la versione  [v1.2.0-pre.1] vengono segnalati errori, tutti basati sul messaggio  **"Uno o più data-element necessari per condurre il test non sono stati trovati"** Si precisa che l'errore non coincide con lo stato dei fatti (ad. es. installazione pulita con tema all'ultima versione non trova la libreria bootstrap). La stessa segnalazione avviene con siti precedenti già asseverati e perfettamente adeguati ai criteri di conformità. Si chiede se è un problema legato al fatto che si tratta di una pre release o, in alternativa, si chiedono urgenti spiegazioni a riguiardo. Grazie.

**Comment by Giaimo-DTD** [comment]
Buongiorno, da oggi è disponibile la nuova [versione 2.0](https://github.com/italia/pa-website-validator/releases/tag/v2.0.0) di app di valutazione. Per una conduzione più approfondita dei test sono necessari data element aggiuntivi, che sono indicati nella [Documentazione dell'app di valutazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/).
Quel tipo di messaggio indica che ci sono dei data element necessari che non sono stati trovati, consiglio di guardare le descrizioni e i nuovi esempi inseriti.
