### ISSUE TITLE
C.SI.3.2 - DICHIARAZIONE DI ACCESSIBILITÀ

### ISSUE THREAD

**Issue by NicolaZivago** [italia/pa-website-validator#189]
Il link di dichiarazione accessibilità è correttamente inserito nel footer con relativo data-element, ma otteniamo comunque errore.
Preciso che il sito è in staging e non in produzione, quindi l'url non corrisponde a quello "ufficiale".
Il test è stato lanciato in modalità "locale", l'errore dipende da questo?

**Comment by Giaimo-DTD** [comment]
il test controlla anche che la pagina di destinazione soddisfi dei requisiti propri della dichiarazione di accessibilità AGID, quindi se l'url inserito non è quello della vera dichiarazione è giusto mostri fallimento. Maggiori info sono disponibili nella [documentazione dell'App ](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-3-2-dichiarazione-di-accessibilita)

**Comment by NicolaZivago** [comment]
@Giaimo-DTD ti confermo che l'url di destinazione inserito è quello corretto

**Comment by Giaimo-DTD** [comment]
provo a indagare, potresti passarmi l'url del sito? se preferisci farlo privatamente mi trovi su slack di developers italia come Federico Giaimo

**Comment by NicolaZivago** [comment]
ti ho scritto su slack, il test è stato fatto in ambiente di staging

**Comment by Giaimo-DTD** [comment]
siccome può essere utile ad altri: l'errore sta nel fatto che l'url di un ambiente di staging è differente dall'url inserito nella dichiarazione di accessibilità, che è quello di produzione.
Quando url di provenienza e url inserito nella dichiarazione combaciano, il problema si risolve
