### ISSUE TITLE
C.SI.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA

### ISSUE THREAD

**Issue by NicolaZivago** [italia/pa-website-validator#190]
Il criterio risulta non validato per colpa di un errore identificato su applicativo esterno per la gestione delle prenotazioni

**Comment by Giaimo-DTD** [comment]
L'applicativo del sistema di prenotazione non deve per forza essere una funzionalità interna al sito, ma la sua interfaccia verso l'utente deve rispettare tutti i criteri non essendo diversamente indicato. Questo include il criterio sull'utilizzo di Bootstrap Italia
