### ISSUE TITLE
VOCI DI MENÙ DI SECONDO LIVELLO RIF C.SC.1.5

### ISSUE THREAD

**Issue by pilcom2023** [italia/pa-website-validator#196]
Salve,
nonostante le voci di menu di secondo livello sono corrette, senza aggiunte, il risultato dei crriteri di conformità si ferma al 94% a causa del risultato delle voci di menù di secondo livello che non supera l'81%.

**Comment by tensor5** [comment]
Ciao @pilcom2023, questa issue dovrebbe essere risolta dall'ultima release https://github.com/italia/pa-website-validator/releases/tag/v2.0.2. Puoi verificare?

**Comment by pilcom2023** [comment]
Buongiorno @tensor5  adesso va bene :). Vedi in allegato report. Grazie!!
![IMG-4749](https://user-images.githubusercontent.com/126661148/223401877-3ec5e7bd-a87a-4d59-83bd-d33bb8d776e7.jpg)

**Comment by Giaimo-DTD** [comment]
@pilcom2023 complimenti per l'ottimo punteggio! Posso chiederti l'url del sito? :)

**Comment by pilcom2023** [comment]
@tensor5 https://www.educandatomariadelaide.it saluti!

**Comment by pilcom2023** [comment]
@Giaimo-DTD https://www.educandatomariadelaide.it/ saluti!
