### ISSUE TITLE
Voci aggiuntive | data-element=”custom-submenu”

### ISSUE THREAD

**Issue by TlC123789** [italia/pa-website-validator#200]
Sto provando ad aggiungere delle voci personalizzate nel tema ma ogni volta mi abbassa il voto nell'app di validazione nei criteri di conformità.

Inoltre non ho compreso bene in quale sottomenu o voce singola debba essere inserio il data-element="custom-submenu". Nella documentazione dell'app di valuzione non compare nessun esempio.

MI serve per aggiungere una voce di menù che mi porti direttamente ad una pagina con i pon e nel menu in alto a destra posso mettere fino a 2 voci. 

Grazie in anticipo per la risposta

**Comment by Giaimo-DTD** [comment]
Il criterio richiede siano presenti solo le voci di menu di secondo livello indicati in documentazione, ogni voce aggiuntiva non compresa abbassa la percentuale.
Esempi per l'inserimento di "custom-submenu" sono presenti nella documentazione https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html#criterio-c-sc-1-5-voci-di-menu-di-secondo-livello

**Comment by TlC123789** [comment]
Andando nella documentazione da voi segnalata si comapre la presenza del "custom-submenu", ma non è presente la sezione SU DOVE METTERE questo custom-submenu da voi creato.
https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html#criterio-c-sc-1-5-voci-di-menu-di-secondo-livello sono presenti ovviamente la posizione dei vari submenu (news, teache, ecc). 

Detto questo non c'è scritto da nessun parte nella documentazione che si devono usare solo ed esclusivamente le voci di menù presenti nella documentazione e non si possono mettere altre voci.

**Comment by Giaimo-DTD** [comment]
Corretto, si possono usare anche voci di menu di primo o secondo livello aggiuntive, nella numerica massima indicata nei criteri.
Per le voci di secondo livello aggiuntive si usa il data element "custom-submenu" in un modo analogo agli altri menu di secondo livello relative a voci di primo livello, quindi:

```
<ul data-element="menu">
   <li>
       <a>Voce aggiuntiva di primo livello</a>
       <ul data-element="custom-submenu">
           <li>
               <div>
                   <a href="#" data-element="overview">Panoramica</a>
               </div>
           </li>
           <li><a href="">Voce aggiuntiva di secondo livello 1</a></li>
           <li><a href="">Voce aggiuntiva di secondo livello 2</a></li>
           <li><a href="">Voce aggiuntiva di secondo livello 3</a></li>
       </ul>
   </li>
```

**Comment by TlC123789** [comment]
Ho effettuato delle prove come da voi consigliato, sia mettendolo come voce aggiuntiva di primo livello nel menù principale e lì mi ha dato errore. Ma ovviamente nelle direttive bisogna mettere solo le quattro voci di menù principali e quindi è normale che mi segnala l'errore

![error 01](https://user-images.githubusercontent.com/127135309/223708226-b412ed26-581d-4e1d-b9d8-847820e4266c.jpg)

Poi l'ho messo questo submenu come elmenti di secondo livelo del menu laterale ma anche qui mi dava errore.

![error 02](https://user-images.githubusercontent.com/127135309/223733082-0b86f926-ea33-4cd0-84e9-3dfdce882743.jpg)

Detto questo non userò questo data element per il sito internet

**Comment by Giaimo-DTD** [comment]
Dal report vedo che il risultato è giallo, quindi il test viene superato in condizione di "tolleranza", infatti sia per il test C.SC.1.4 e C.SC.1.5 sono indicati in documentazione dei margini di flessibilità entro cui va bene inserire pagine aggiuntive.
Leggo che fa riferimento al menu laterale, ma questi data element vanno usati per il menu principale, quindi per le voci del menu di primo livello e per le i sottomenu a queste riferite.
Nel caso in cui nel menu principale siano presenti sottomenu aggiuntivi rispetto ai 4 per i quali vanno usati i data-element specifici, l'utilizzo dei data element per le voci obbligatorie (quali "custom-submenu") è obbligatorio.
