### ISSUE TITLE
nuove versioni dell'app

### ISSUE THREAD

**Issue by lia55556** [italia/pa-website-validator#201]
Buonasera, sto lavorando da un mese al mio sito per adeguarlo ai criteri di conformità ed ero finalmente riuscita a raggiungere il risultato che vi allego

![reportIISSPSEtte](https://user-images.githubusercontent.com/125757301/223195456-1bd1ab94-8a60-412d-a008-8fedbb5e4f27.GIF)

Casualmente un mio amico ha scaricato la vostra app e ha fatto una prova oggi, risultati prodotti sono pessimi; io sto lavorando con l'app che ho scaricato un mese fa, cosa dovrei fare, scaricare l'app tutti i giorni e provare? adesso come mi regolo?

**Comment by Giaimo-DTD** [comment]
Buongiorno, sia l'app che i template/CMS ricevono degli aggiornamenti periodici migliorativi. Per rimanere informata su queste evoluzioni le consigliamo di seguire il canale Slack https://developersitalia.slack.com/archives/CQ7J0KANT
Nella nuova versione sono richiesti data-element aggiuntivi, quindi è probabile il risultato sia peggiorato perché questi vanno aggiunti (aggiornando il tema o inserendoli personalmente). Maggiori informazioni sono indicate [nella documentazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html) per ognuno dei criteri e raccomandazioni

**Comment by lia55556** [comment]
Intanto l'ultima versione dell'app va di sicuro revisionata in quanto mi segnala un certificato https scaduto sul mio sito quando invece è ancora valido, e questo è facile da verificare; riguardo al resto vorrei sapere se e quando termineranno questi aggiornamenti, io avevo praticamente finito e stavo per consegnare il lavoro quando mi è piovuto addosso questo aggiornamento che ha rimesso tutto in discussione; il lavoro va consegnato entro il 30 giugno, quando sarà possibile mettere un punto e iniziare a lavorare in tranquillità? Tenete presente che non tutti utilizzano il vostro CMS (non essendo un requisito obbligatorio), e gestire i data element con altri CMS è piuttosto gravoso. Grazie per l'attenzione.
