### ISSUE TITLE
v2.0.2 - Criterio C.SI.1.1 e Criterio C.SI.1.2

### ISSUE THREAD

**Issue by NicolaZivago** [italia/pa-website-validator#202]
Ciao, i due criteri in oggetto con l'ultima versione non risultano più validati, in precedenza erano correttamente verificati. La regressione nel giudizio è determinata dai nuovi rilasci dei data-element o potenziale bug?
Grazie

**Comment by tensor5** [comment]
Ciao @NicolaZivago, sono stati introdotti `data-element` per effettuare gli audit su più pagine. Controlla la documentazione.
