### ISSUE TITLE
Ordine attributi data-element non dovrebbe essere importante

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#204]
I link delle categorie di servizio che devono contenere il data-element="service-category-link" sono correttamente visti se il link è del tipo:
`<a href="#" data-element="service-category-link">`
Ma se il data-element non è in seconda posizione dopo l'href la validazione fallisce, esempio:
`<a href="#" class="..." data-element="service-category-link">`
Forse ci sono anche altri casi simili, a mio parere la validazione dovrebbe essere fatta a prescindere dalla posizione dell'attributo nel tag.
Grazie.

**Comment by Giaimo-DTD** [comment]
Buongiorno, potrebbe fornirmi il link al sito in modo da verificare? Usate tema CMS fornito o soluzione custom?
