### ISSUE TITLE
R.SI.1.1 METATAG

### ISSUE THREAD

**Issue by MassyCare99** [italia/pa-website-validator#206]
con l'ultima versione non mi rileva più i metatag, mentre con tutte le precedenti funzionava

**Comment by Giaimo-DTD** [comment]
Ciao @MassyCare99, anche nel caso dei metatag dai test che abbiamo fatto risulta che ci sono dei problemi a caricare le pagine del sito, per cui di tanto in tanto le pagine caricano molto lentamente e vanno in timeout o vengono caricate solo parzialmente. Questo problema si verifica anche navigando il sito tramite browser per cui non è un bug dello strumento di validazione. Potrebbe invece essere dovuto ad un sovraccarico del server.
