### ISSUE TITLE
Criterio C.SI.1.1 e Criterio C.SI.1.2 - Modalità verifica non adatta ad applicazioni Angular

### ISSUE THREAD

**Issue by mmartinel** [italia/pa-website-validator#216]
Per superare i criteri C.SI 1.1 e C.SI 1.2 è necessario, tra le altre cose, che alcuni button contengano l'attributo onlick con i link alle pagine successive. 

Questo controllo non è adatto alle applicazioni Angular, per le quali il binding su onclick è considerato unsafe. Le applicazioni Angular utilizzano infatti l'event binding (click) e, di conseguenza, l'attribute onclick non è presente e i criteri C.SI 1.1 e C.SI 1.2 non vengono superati.

**Comment by tensor5** [comment]
Potrebbe essere risolto da #249.

**Comment by tensor5** [comment]
Ciao @mmartinel, puoi usare `href` invece di `onclick`, dalla prossima versione diventeranno validi.

**Comment by Giaimo-DTD** [comment]
@mmartinel sei riuscito a risolvere con la modifica suggerita da @tensor5 ?

**Comment by mmartinel** [comment]
Ciao. Confermo che con le modifiche suggerite ora superiamo i controlli
