### ISSUE TITLE
Validatore per tema scuole wordpress

### ISSUE THREAD

**Issue by marcovigan89** [italia/pa-website-validator#217]
Come mai, nell'ultima versione da voi rilasciata, i punteggi sulle performance (pure performance di pagina) sono peggiorati cosi tanto? Facendo i medesimi test con google page speed si hanno punteggi 3 volte superiori. E' un po' penalizzante in quanto non si dovrebbe in alcun modo alterare il tema per migliorare le performance. Sono in programma rilasci per sistemare la cosa?

**Comment by tensor5** [comment]
Ciao @marcovigan89, ti riferisci all'ultima versione del validatore o del tema Wordpress? Nel caso del validatore non è cambiato nulla sul lato del controllo delle performance di pagina.
