### ISSUE TITLE
R.SC.1.1 - VOCABOLARI CONTROLLATI: errore in presenza di più categorie come filtri nella pagina di ricerca

### ISSUE THREAD

**Issue by OProf77** [italia/pa-website-validator#218]
Così come da titolo, se nella pagine della ricerca sono presenti più categorie di filtri, oltre a quella relativa alle PAROLE DELLA SCUOLA, il validatore restituisce errore.

Se è presente solo categoria ARGOMENTI, relativa alle Parole della scuola, il validatore accetta il criterio.

Questo è il link da controllare se volete: https://amaldisraffa.edu.it/pagina-di-ricerca?search_api_fulltext=test

**Comment by Giaimo-DTD** [comment]
Ciao, sembra il problema sia legato al fatto che la query di ricerca sul sito è avviabile solo premendo su cerca e invece se viene premuto "Invio" da tastiera fallisce con messaggio di errore

The website encountered an unexpected error. Please try again later.
TypeError: Cannot access offset of type string on string in Drupal\Component\Utility\NestedArray::setValue() (line 155 of core/lib/Drupal/Component/Utility/NestedArray.php).
