### ISSUE TITLE
bug PEC

### ISSUE THREAD

**Issue by lia55556** [italia/pa-website-validator#222]
Nella pagina di terzo livello Servizio è richiesta la presenza della PEC, ma nel caso in cui nella mia pagina è contenuto questo codice, automaticamente generato dal mio CMS, l'app mi dice che non trova la PEC, se invece faccio il test sul solo codice fornito da voi allora va bene

![Cattura](https://user-images.githubusercontent.com/125757301/225028440-9ab30b3c-6876-4614-a00d-bc9330cc6719.GIF)

**Comment by tensor5** [comment]
Ciao @lia55556, non risulta chiaro quale sia il problema. Puoi darci maggiori informazioni, in particolare qual è il test che fallisce?

**Comment by lia55556** [comment]
mi da questo errore:

![pec](https://user-images.githubusercontent.com/125757301/225350771-edaf323f-8d35-493a-9f5d-7670f50e74ab.GIF)

cosa che non accade se rimuovo quel codice che vi ho evidenziato nel mio precedente commento; la mia ipotesi è che la presenza della sottostringa pec in porzioni qualunque del codice faccia impallare l'app su questo controllo; spero di essere stata chiara

**Comment by tensor5** [comment]
Ciao @lia55556, dovresti inserire un valore vuoto in corrispondenza della voce "GPS", cioè

```html
<div>
  <span>GPS</span>
</div>
<div>
  <p></p>
</div>
```

Con questa correzione dalla prossima versione del validatore il problema dovrebbe sparire.

**Comment by lia55556** [comment]
Ok, però non capisco cosa c'entri questo codice con il bug sulla PEC che vi ho segnalato; inoltre nella mia pagina la sezione relativa al GPS c'è, è anche avvalorata e infatti su questo l'app va bene

**Comment by Giaimo-DTD** [comment]
Risolto con [PR 225](https://github.com/italia/pa-website-validator/pull/225)
