### ISSUE TITLE
test non superato su font, bootstrap, cookies

### ISSUE THREAD

**Issue by lia55556** [italia/pa-website-validator#226]
Buongiorno, la versione 1 dell'app mi dava report positivo su questi tre criteri (in realtà su tutti, infatti pensavo di aver finito il lavoro), la versione 2 no, segnalandomi genericamente su tutti e tre che
"Uno o più data-element necessari per condurre il test non sono stati trovati."
Ma quali sono questi data-element? Come faccio a saperlo? Sono sicura di aver inserito tutti quelli richiesti, tanto è vero che tutto il resto passa il test. Potete aiutarmi per favore?
![report](https://user-images.githubusercontent.com/125757301/226360572-4074e3d5-5b12-45b0-afa5-9864ffe1e517.GIF)

**Comment by Giaimo-DTD** [comment]
Buongiorno, è necessaria sia la presenza dei data element sia la presenza delle pagine di destinazione da analizzare (indicate nel campo "Modalità di verifica" della [documentazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html)). Le consiglio di verificare la presenza delle pagine richieste.

**Comment by lia55556** [comment]
Potreste essere più precisi? Le pagine di destinazione di quali link? Perchè quelle richieste nella documentazione (pagine servizio di secondo e terzo livello, pagine luoghi di secondo e terzo livello) già le ho inserite. Grazie.

**Comment by tensor5** [comment]
Le voci presenti all'interno dei vari sotto menù devono avere link a pagine esistenti (non `href="#"`).

**Comment by lia55556** [comment]
E' già così

**Comment by pietronuzzo** [comment]
Si riscontra la stessa problematica, nonostante i data-element siano presenti ed inseriti all'interno dei tag corretti
