### ISSUE TITLE
Le domande di follow up non sono associate ai valori corretti - C.SI.2.5 - C.SI.2.6

### ISSUE THREAD

**Issue by HshMatera** [italia/pa-website-validator#228]
Buongiorno, sto avendo dei problemi per quanto riguarda la funzionalità di valutazione del servizio (/template-parts/common/valuta-servizio.php). 
Utilizzando la versione del tema Wordpress 1.6.1 (ultima release) mi restituisce i seguenti errori: 
![Cattura](https://user-images.githubusercontent.com/82446929/226638231-c09a54c2-6af2-478e-a7aa-932139c7e87e.PNG)

![Cattura2](https://user-images.githubusercontent.com/82446929/226638052-835072b7-a296-4fd0-af2a-5a4ed9cbec04.PNG)

mentre con la versione 1.4.3 nel quale non sono presenti tutti i data-element richiesti non da alcun errore. 

Come mai?
Grazie

**Comment by Giaimo-DTD** [comment]
Buongiorno, potresti fornirci l'url in modo da effettuare ulteriori verifiche?

**Comment by HshMatera** [comment]
Buongiorno, ecco il link https://hshmatera.it/
Grazie

**Comment by HshMatera** [comment]
Qualche novità in merito?

**Comment by Giaimo-DTD** [comment]
Abbiamo preso in carico la issue e stiamo conducendo verifiche

**Comment by Giaimo-DTD** [comment]
Buongiorno @HshMatera i risultati inconsistenti sembra siano dovuti a Firewall o protezioni DDoS. Consiglio di provare intanto a disattivarli per vedere se i risultati cambiano, poi provare a capire che interventi si possono fare sul server per evitare questi blocchi all'app di valutazione. Se c'è un'opzione sulla frequenza di chiamate al sito prima che un IP venga bloccato, aumentarla potrebbe risolvere il problema pur mantenendo la protezione.
