### ISSUE TITLE
C.SI.1.1 - COERENZA DELL'UTILIZZO DEI FONT

### ISSUE THREAD

**Issue by FAleotti** [italia/pa-website-validator#230]
Quando viene analizzata una pagina il cui url non è raggiungibile viene riportata la dicitura "Protocol error (Page.navigate): Cannot navigate to invalid URL" e lo score dei "criteri di conformità" viene rappresentato con un "?".
Potrebbe essere utile avere dei riferimenti all'url che ha scatenato l'errore in modo da poter verificare velocemente la pagina.
Io personalmente, per venirne a capo, ho aggiunto un explanation contenente "pageToBeAnalyzed" qui https://github.com/italia/pa-website-validator/blob/main/src/audits/municipality/fontsCheckAudit.ts#L226 e ho recuperato l'url estraendo il json del report.
![Errore validazione](https://user-images.githubusercontent.com/40228862/226906082-fa52b52e-7d8f-44da-b251-10a92b8b2636.JPG)

**Comment by Giaimo-DTD** [comment]
potresti fornirci l'url del sito per favore, così facciamo una verifica

**Comment by FAleotti** [comment]
Purtroppo il sito su cui ho riscontrato il problema non è pubblicato in rete

**Comment by fnori77** [comment]
Salve, l'app di validazione continua a fare controlli del path /wp-admin e restituisce esito negativo sul controllo delle font. Non credo sia corretto che la validazione sia eseguita anche sulle pagine di backend.
<img width="840" alt="Screenshot 2023-05-25 alle 11 46 05" src="https://github.com/italia/pa-website-validator/assets/126147260/4338fd80-a271-4d40-873b-b4b4094baa42">

**Comment by fnori77** [comment]
Grazie mille per la risposta solerte.

**Comment by mariantanase** [comment]
> Questo avviene perché viene verificata la pagina raggiungibile dal pulsante "Accedi all'area personale" in homepage (le pagine analizzate vengono indicate in [documentazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-1-1-coerenza-dellutilizzo-dei-font-librerie-di-caratteri)). Immagino quel link invii alla pagina di accesso al backoffice wordpress solo temporaneamente, una volta che lo sostituirete con il link corretto verrà valutata la pagina giusta

"**Solo temporaneamente**" 
Questa non l'ho capita. Perche solo temporaneamente ? Quello e l'accesso all'area riservata di wordpress e di conseguenza quel pulsante dev'essere collegato a `<?php echo admin_url(); ?>`.
Che alternativa abbiamo ?

**Comment by Giaimo-DTD** [comment]
@mariantanase da modello quello è il pulsante per accedere all'area riservata del cittadino, non dell'utente di wordpress interno all'ente.

**Comment by mariantanase** [comment]
> @mariantanase da modello quello è il pulsante per accedere all'area riservata del cittadino, non dell'utente di wordpress interno all'ente.

Tutto chiaro adesso. Grazie!
