### ISSUE TITLE
R.SI.1.1 - METATAG - Nel sito comunale, le voci della scheda servizio devono presentare i metatag descritti dal modello, in base agli standard internazionali.

### ISSUE THREAD

**Issue by HshMatera** [italia/pa-website-validator#232]
Salve,
sto utilizzando l'ultima release del tema Wordpress Comuni 1.6.1 e nella scheda Servizio devo utilizzare solo le voci per le quali viene controllata la presenza nell’indice, il loro ordinamento e il contenuto con il relativo metatag come spiegato nel Criterio C.SI.1.3. 
Se provo ad inserire altri contenuti (Doccumenti, Vincoli, ecc) non obbligatori mi segnala l'errore R.SI.1.1. - METATAG. 
Come mai?

**Comment by Giaimo-DTD** [comment]
Buongiorno, può fornirci l'url per effettuare una verifica?
