### ISSUE TITLE
MAC - Validazione punto C.SI.2.5 - VALUTAZIONE DELL'ESPERIENZA D'USO, CHIAREZZA DELLE PAGINE INFORMATIVE 

### ISSUE THREAD

**Issue by enzobuso** [italia/pa-website-validator#233]
sto riscontrando un problema con l'app di validazione con MAC (che non è presente validando con Windows ): al termine della validazione lo score su "criteri di conformità" è rappresentato mediante il marcatore rosso e relativamente al punto C.SI.2.5 - VALUTAZIONE DELL'ESPERIENZA D'USO, CHIAREZZA DELLE PAGINE INFORMATIVE - Il sito comunale deve consentire al cittadino di fornire una valutazione della chiarezza di ogni pagina di primo e secondo livello.

La segnalazione di errore, presente su tutte  le pagine, è relativa a : Domanda iniziale errata; Domanda negativa di follow up errata

**Comment by enzobuso** [comment]
<img width="803" alt="Screenshot 2023-03-24 alle 22 44 51" src="https://user-images.githubusercontent.com/121640307/227647013-f4e19485-87ed-46c3-886f-afb00ec55b8a.png">

**Comment by Giaimo-DTD** [comment]
![image](https://user-images.githubusercontent.com/105422742/228551871-55b2b465-215c-4a09-a918-0b1daa3a98e9.png)
il problema sta nel fatto che c'è un disallineamento tra come viene visualizzata la domanda in base al sito browser utilizzato, è una casistica da risolvere lato HTML o CSS
