### ISSUE TITLE
C.SC.3.1 - CERTIFICATO HTTPS non valido se il tool viene eseguito in Windows

### ISSUE THREAD

**Issue by mirchaemanuel** [italia/pa-website-validator#234]
Sto utilizzando il tool di validazione siti della pubblica amministrazione per verificare la conformità del sito web di un ente pubblico. Ho notato che quando eseguo il tool su Windows, ottengo l'errore "C.SC.3.1 CERTIFICATO HTTPS non presente", mentre eseguendo lo stesso tool su Linux l'errore non è presente.

Allego schermata output del tool su Windows:
![windows_ko](https://user-images.githubusercontent.com/1971953/228161328-b3ed5b95-f1ac-41b4-8acf-c955bc0efd69.png)

Allego schermata output del tool su Linux:
![linux_ok](https://user-images.githubusercontent.com/1971953/228161316-39955283-18d9-4c5b-968b-9ffd58f57a68.png)

Il sito che sto cercando di validare ha un certificato SSL Let's Encrypt valido.

Da cosa potrebbe dipendere?

**Comment by Giaimo-DTD** [comment]
@mirchaemanuel il problema persiste anche nell'ultima versione di app? Localmente non riusciamo a riprodurre l'errore
