### ISSUE TITLE
Validatore scuole - Problema C.SC.1.1 - Coerenza dell'utilizzo dei font - C.SC.1.2 - Libreria di elementi di interfaccia

### ISSUE THREAD

**Issue by aleko21** [italia/pa-website-validator#235]
Ho eseguito la scansione su due siti realizzati con il template wordpress di Designers Italia (versione template 2.3.1 - versione wordpress 6.1.1). Utilizzando il validatore per MAC ricevo risultati diversi per i punti C.SC.1.1 e C.SC.1.2 come da screenshot mostrati sotto: 

Sito: balillaimbriani.scuolaweb.eu
 
![image](https://user-images.githubusercontent.com/36449858/228454312-ad21332b-e415-4dd6-b08e-d63a86a91b4a.png)

Sito: https://www.icsitalocalvino.edu.it/
![image](https://user-images.githubusercontent.com/36449858/228456937-7886120e-97ab-40aa-9d5b-415cee117c34.png)

Oltre a qualche plugin presente nel primo sito e non nel secondo, la principale differenza è che il primo è stato installato su una versione di Wordpress Multisite. 
Non abbiamo riscontrato differenze sostanziali nel codice e quindi non riusciamo a comprendere i motivi dei due report differenti. 

Utilizzando il template ufficiale Designers Italia non dovrebbe essere automatico l'utilizzo e la rilevazione dei font e delle librerie bootstrap? 

Può essere che la differenza nei report sia dovuta alla mancata rilevazione nella versione multisite e che quindi debba essere aggiornato il validatore ?

**Comment by Giaimo-DTD** [comment]
Sembra che nella sezione "Didattica" manchi la voce "Panoramica" con il relativo URL, in questo modo non è possibile raggiungere le pagine da analizzare e il test fallisce.
