### ISSUE TITLE
Aggiornamento database GeoIP

### ISSUE THREAD

**Issue by mariomenis** [italia/pa-website-validator#236]
Buongiorno, ho notato che il database della libreria geoip-lite non è aggiornato con gli IP del nuovo datacenter Google Cloud di Torino.
E' possibile aggiornarlo?
Grazie

**Comment by Sonic0** [comment]
Ho notato da tempo anche io questa cosa e credo dipenda dalla licenza come spiegato nella issue https://github.com/geoip-lite/node-geoip/issues/245

**Comment by tensor5** [comment]
Il database viene aggiornato ad ogni rilascio dell'app.

**Comment by tensor5** [comment]
Aggiornato in v2.2.0.
