### ISSUE TITLE
Problema con R.SC.2.2 - LICENZA E ATTRIBUZIONE 

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/pa-website-validator#240]
Nelle Raccomandazioni Progettuali, riceviamo questo errore, con l'indicazione che:
"La dicitura sulla licenza dei contenuti è errata o non presente nella pagina delle note legali o questa non è raggiungibile dal footer."
Ma dove possiamo trovare questa pagina oppure il link nel footer per poterla modificare/aggiungere ?

**Comment by HshMatera** [comment]
Basta creare una pagina con il titolo "Note legali" e linkarla nel menu del footer. Verrà associato automaticamente il data-element di riferimento.

**Comment by HshMatera** [comment]
Basta creare una pagina con il titolo "Note legali" e linkarla nel menu del footer. Verrà associato automaticamente il data-element di riferimento.

**Comment by CampusDaVinci** [comment]
> Basta creare una pagina con il titolo "Note legali" e linkarla nel menu del footer. Verrà associato automaticamente il data-element di riferimento.
> 
> https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-3-4-licenza-e-attribuzione

No, ho provato a farlo e non funziona.
https://campusdavinci.edu.it
https://campusdavinci.edu.it/note-legali/ (raggiungibile dal footer)

**Comment by HshMatera** [comment]
Si infatti adesso con la versione ultima dell'app da errore anche a me.

**Comment by Giaimo-DTD** [comment]
@CampusDaVinci @HshMatera siete riusciti a risolvere il problema della mancanza del data element?

**Comment by HshMatera** [comment]
La pagina Note Legali l'ho strutturata in questo modo e la verifica passa. Se provo ad aggiungere altro testo mi restituisce l'errore. Aspettiamo aggiornamenti ma per adesso è così.
```
<div>
<h1 data-element="legal-notes-section">Licenza dei contenuti</h1>
<p data-element="legal-notes-body">In applicazione del principio open by default ai sensi dell’articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con licenza CC-BY 4.0.</p>
<p data-element="legal-notes-body">Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.</p>
</div>
```

**Comment by Giaimo-DTD** [comment]
Nel caso aggiungiate altro testo in pagina assicuratevi solo quei p non contengano i data element, altrimenti l'app analizza anche quei testi e trova difformità rispetto al testo atteso
