### ISSUE TITLE
debug codice app

### ISSUE THREAD

**Issue by lia55556** [italia/pa-website-validator#242]
Sono settimane che non riesco a trovare una soluzione al test non superato su font, bootstrap e cookies, nonostante io mi sia scrupolosamente attenuta a tutte le indicazioni fornite nelle documentazione. Ho ancora un thread aperto i cui vi chiedo aiuto.  Sto provando anche a studiare il codice sorgente dell'app ma non ne vengo a capo; a questo punto vi chiedo se è possibile debuggare il codice dell'app e come.

**Comment by lia55556** [comment]
Finalmente ho risolto, ma ho dovuto studiare in modo approfondito il codice dell'app; spero di non dover rifare tutto da capo nel caso di una  nuova versione, comunque vi suggerisco di integrare la documentazione con indicazioni più precise, grazie.

**Comment by smaraschin** [comment]
> Finalmente ho risolto, ma ho dovuto studiare in modo approfondito il codice dell'app; spero di non dover rifare tutto da capo nel caso di una nuova versione, comunque vi suggerisco di integrare la documentazione con indicazioni più precise, grazie.

Ciao, puoi spiegarci come hai risolto? Direi che è un problema che abbiamo in tanti
Grazie in anticipo

**Comment by LucaDuttoTD** [comment]
> > Finalmente ho risolto, ma ho dovuto studiare in modo approfondito il codice dell'app; spero di non dover rifare tutto da capo nel caso di una nuova versione, comunque vi suggerisco di integrare la documentazione con indicazioni più precise, grazie.
> 
> Ciao, puoi spiegarci come hai risolto? Direi che è un problema che abbiamo in tanti Grazie in anticipo

+1

**Comment by MassyCare99** [comment]
Novità? @lia55556

**Comment by smaraschin** [comment]
Stiamo tutti in attesa

**Comment by lia55556** [comment]
Il link relativo alla voce di menu "Panoramica" non deve nè essere vuoto nè puntare alla stessa pagina: quest'ultima cosa non è specificata nella documentazione; l'ho capita studiandomi il codice sorgente dell'app di valutazione. Ad ogni modo il problema che avevo su bootstrap, font e cookies l'ho risolto così.

**Comment by lia55556** [comment]
é un sottomenu dei quattro menu di primo livello, questo è spiegato bene nella documentazione

**Comment by franzuin** [comment]
> Il link relativo alla voce di menu "Panoramica" non deve nè essere vuoto nè puntare alla stessa pagina: quest'ultima cosa non è specificata nella documentazione; l'ho capita studiandomi il codice sorgente dell'app di valutazione. Ad ogni modo il problema che avevo su bootstrap, font e cookies l'ho risolto così.

Ciao. Io ho esattamente gli stessi problemi e non riesco a individuare dove sta l'inghippo. Sicuramentente non su panoramica perchè l'href è valorizzato correttamente. come hai risolto per font e cookies?
