### ISSUE TITLE
C.SI.3.4 - LICENZA E ATTRIBUZIONE - errore

### ISSUE THREAD

**Issue by NicolaZivago** [italia/pa-website-validator#244]
Il criterio non viene validato nonostante siano presenti tutti i data-element richiesti

**Comment by mariantanase** [comment]
@NicolaZivago scusami, come hai risolto ?

**Comment by NicolaZivago** [comment]
@mariantanase rilanciando i test ora funziona correttamente, forse era un problema di timeout.
