### ISSUE TITLE
C.SI.3.2 - DICHIARAZIONE DI ACCESSIBILITÀ

### ISSUE THREAD

**Issue by andreabaglioni** [italia/pa-website-validator#246]
**Sebbene si stia testando in sviluppo,** il controllo fallisce, probabilmente perchè il controllo che viene fatto sulla pagina di destinazione (url del sito nella dichiarazione di accessibilità) non corrisponde alla url del sito per cui si fa il test.

![image](https://user-images.githubusercontent.com/1468914/229709404-fdb8407f-27c5-45e3-b807-ddf90af3540e.png)

**Comment by HshMatera** [comment]
Dovrebbe essere così. Una volta in produzione dovrebbe sparire l'errore in quanto le pagine coincidono.

**Comment by Giaimo-DTD** [comment]
esatto, url del sito e url riportato sulla dichiarazione devono coincidere, come detto da @HshMatera questo problema sparisce andando in produzione. Corretto però che in ambiente di sviluppo il risultato del test non venga mostrato come per altri, per non trarre in inganno
