### ISSUE TITLE
R.SC.2.2 - LICENZA E ATTRIBUZIONE

### ISSUE THREAD

**Issue by danieledexter** [italia/pa-website-validator#250]
Salve, con l'ultimo aggiornamento del validatore, il mio sito non supera più il requisito **R.SC.2.2 - LICENZA E ATTRIBUZIONE**.

Fino ad un paio di giorni fa non aveva problemi, c'era il data-element="legal-notes" nel file footer-walker.php e avevo messo i contenuti come richiesti nella documentazione.

Questa mattina il controllo non è passato, ho aggiunto un titolo "Licenza dei contenuti" nella pagina ed inserito la dicitura richiesta con i data element che trovo qui https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html nel punto R.SC.2.2

Vorrei sapere quindi cosa devo fare per passare il controllo.
Grazie

**Comment by HshMatera** [comment]
Sarà sicuramente un BUG da risolvere.

**Comment by emanueleempix** [comment]
Ho lo stesso problema. Con l'aggiornamento il requisito **R.SC.2.2 - LICENZA E ATTRIBUZIONE** non viene superato

**Comment by Giaimo-DTD** [comment]
@danieledexter puoi fornirci l'url del sito? Così effettuiamo una verifica

**Comment by danieledexter** [comment]
> @danieledexter puoi fornirci l'url del sito? Così effettuiamo una verifica

Ciao, ormai ho sistemato.
Ho seguito le indicazioni che hanno fornito sulla chat di Slack

<h2 data-element="legal-notes-section">Licenza dei contenuti</h2>
<p data-element="legal-notes-body">
In applicazione del principio open by default ai sensi dell’articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con licenza CC-BY 4.0. Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.
</p>

E nel filem footer-walker.php ho lasciato il data-element con "legal-notes" come avevo già messo per la validazione precedente

**Comment by danieledexter** [comment]
*Avevo messo il codice in html, però me l'ha convertito da solo in testo.
Comunque il titolo è un **h2** con data-element="legal-notes-section" e il contenuto è un **p** con data-element="legal-notes-body"
