### ISSUE TITLE
Validazione note legali

### ISSUE THREAD

**Issue by nicolapippa** [italia/pa-website-validator#255]
Buongiorno,
nonostante ci siano tutti i data-element richiesti per le note legali non capisco perchè il validatore non le rileva. Vi lascio il link del sito demo (https://sogiweb.sogiscuola.com/index.php?idpag=1) per sapere se ci sono suggerimenti per risolvere il problema.

Grazie

**Comment by nicolapippa** [comment]
Risolto. Il "-" nel "data-element" non era un trattino ma un altro carattere, per questo motivo non veniva trovato dal validatore

**Comment by Giaimo-DTD** [comment]
@nicolapippa quel data element lo avete inserito voi o era errato nell'HTML / CMS fornito da Designers Italia?

**Comment by nicolapippa** [comment]
Avevo copiato (sbagliando) la stringa evidenziata nell'immagine, nell'esempio sotto invece il carattere è corretto

![immagine](https://user-images.githubusercontent.com/20949631/231780458-4643068e-5d3c-4a36-a257-b42707936a83.png)
