### ISSUE TITLE
Criterio C.SI.1.3 - contenuto tag <p>

### ISSUE THREAD

**Issue by NicolaZivago** [italia/pa-website-validator#257]
Ciao, nella documentazione delle app viene specificato che:

- «A chi è rivolto»: viene controllata la presenza di un tag p contenuto nel div con data-element="service-addressed" e che questo abbia almeno 3 caratteri;
- «Come fare»: viene controllata la presenza di un tag p contenuto nel div con data-element="service-how-to" e che questo abbia almeno 3 caratteri;
- «Cosa serve»: viene controllata la presenza di un tag p contenuto nel div con data-element="service-needed" e che questo abbia almeno 3 caratteri;
- «Cosa si ottiene»: viene controllata la presenza di un tag p contenuto nel div con data-element="service-achieved" e che questo abbia almeno 3 caratteri;

L'opzione obbligata del tag p a livello redazionale è molto limitante, per esempio nel cosa serve spesso vengono inserite delle liste con elenco puntato (quindi ul con all'interno dei li).
La domanda quindi è, potete prevedere la presenza di altri tag html o semplicemente verificare che il div con data-element non risulti vuoto?

Grazie!

**Comment by Giaimo-DTD** [comment]
Ciao @NicolaZivago temporaneamente potresti inserire gli elenchi in un p, ma prendiamo in carico la issue
