### ISSUE TITLE
C.SI.5.2 - Dominio istituzionale - problema www

### ISSUE THREAD

**Issue by prodigyszonta** [italia/pa-website-validator#259]
Buongiorno,
rispetto alla verifica del tool "C.SI.5.2 - Dominio istituzionale", abbiamo impostato un redirect automatico dal sito web senza "www." a www.
Per tale motivo non è presente il certificato ssl senza "www" e il sistema di verifica fornisce errore.
Lato cittadino e utente però il criterio viene rispettato poichè il redirect automatico rende fruibile la navigazione in entrambi i modi.
E' possibile apportare una modifica alla verifica? O che alternative proponete?
Grazie,
Saluti

**Comment by Giaimo-DTD** [comment]
ci può fornire l'url del sito in modo da condurre un'analisi? grazie

**Comment by prodigyszonta** [comment]
Certo. https://www.comune.ronchis.ud.it/

**Comment by tensor5** [comment]
@prodigyszonta, è necessario includere anche il nome senza www nel certificato.
