### ISSUE TITLE
Validatore scuole - Problema R.SC.2.2 - Licenza e attribuzione

### ISSUE THREAD

**Issue by Vanni-broUser** [italia/pa-website-validator#264]
Quando eseguo il validatore su alcuni siti  realizzati con il template wordpress di Designers Italia (versione template 2.3.1 - versione wordpress 6.1.1) utilizzando l'ultima relase della versione Windows ricevo i seguenti risultati
![Schermata del 2023-04-24 11-01-52](https://user-images.githubusercontent.com/100233261/233950070-dc29bbde-473c-4dec-b116-2b99f27c727c.png)
Sito: balillaimbriani.scuolaweb.eu
La voce "Note legali" è presente nel footer tuttavia sembra non avere il data-element richiesto dal validatore

**Comment by Giaimo-DTD** [comment]
Buongiorno, abbiamo verificato e nella voce nel footer che rimanda alla pagina delle note legali è assente il data-element richiesto. Aggiungendolo il risultato dovrebbe diventare positivo
