### ISSUE TITLE
Validatore scuole - Esiti differenti sullo stesso sito

### ISSUE THREAD

**Issue by Vanni-broUser** [italia/pa-website-validator#265]
Il validatore mi produce esiti contrastanti in base al sistema operativo utilizzato, uso la versione 2.2.1 su un sito con il template wordpress di Designers Italia (versione template 2.3.1 - versione wordpress 6.1.1).

Sito: balillaimbriani.scuolaweb.eu

Usando la versione Mac l'unico Criterio di Conformità mancante risulta:
- C.SC.2.2 - DICHIARAZIONE DI ACCESSIBILITÀ

Runnando la versione Windows risulta anche:
- C.SC.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA
- C.SC.3.1 - CERTIFICATO HTTPS

**Comment by Giaimo-DTD** [comment]
Facendo molteplici test successivi per ognuno dei due OS i risultati rimangono gli stessi? Inviaci per favore il link così facciamo delle verifiche

**Comment by Giaimo-DTD** [comment]
Buongiorno, facendo dei test vediamo che le pagine vengono bloccate nell'analisi dal firewall, probabilmente perché avvengono molteplici richieste di caricamento pagine da parte dell'app e viene bloccata. Consiglio di provare a disabilitare questa opzione e vedere se il problema persiste

**Comment by Giaimo-DTD** [comment]
@Vanni-broUser confermo che deve trattarsi di un problema di firewall o più nello specifico di rate-limiting, provando sia da Mac che da Windows in entrambi i casi dopo un certo numero di chiamate al sito le pagine non risultano più raggiungibili. Fammi sapere se disabilitando temporaneamente il firewall si risolve :)
