### ISSUE TITLE
Problemi esecuzione applicazione

### ISSUE THREAD

**Issue by ToldoDesign128** [italia/pa-website-validator#268]
Buongiorno, come citato nel titolo l'ultima versione dell'applicazione non funziona sul mio PC.
All'avvio del file "app-valutazione-scuole.exe" si apre una schermata del terminale che poi si richiude immediatamente senza darmi nessun messaggio.

**Comment by Giaimo-DTD** [comment]
Buongiorno, è un problema noto che per ora si può risolvere svuotando il contenuto di una cartella come indicato qui https://github.com/italia/pa-website-validator/issues/158
Successivamente verrà comunque sistemata
