### ISSUE TITLE
Esecuzione script per verificare i requisiti del sito comunale

### ISSUE THREAD

**Issue by miannella1** [italia/pa-website-validator#272]
Lo script per la verifica dei requisiti del sito comunale fallisce mostrando il seguente errore:

![image](https://user-images.githubusercontent.com/132355249/235653195-44d2344a-285e-4f64-a8b8-509c4b4223c6.png)

Lo script è stato eseguito con il link del sito sia in locale che in produzione, con gli stessi risultati, successivamente è stato inserito il link di un altro sito comunale e lo script ha concluso l'analisi con successo. 
Da cosa può dipendere?

**Comment by miannella1** [comment]
@Giaimo-DTD posso inviarti l'url del sito via email? per ragioni di sicurezza

**Comment by Giaimo-DTD** [comment]
@miannella1 l'url è quello che era stato inserito precedentemente nel messaggio giusto? in questo caso l'ho recuperato :)
Verifichiamo e ti do feedback

**Comment by miannella1** [comment]
Sisi, ti ringrazio.

**Comment by Giaimo-DTD** [comment]
@miannella1 abbiamo provato a condurre delle scansioni e si concludono sempre con successo. Nella nuova versione di app 2.3.3 il problema persiste?
Ti allego il report generato 
In molti test viene indicato che mancano i data element necessari, se però pensi di aver inserito correttamente tutti quelli richiesti, potrebbe essere che il problema sia in un firewall. Spesso abbiamo visto che per via del numero di richieste in sequenza che fa l'app di valutazione alcuni IP vengano bloccati. Se l'app continua a interrompersi durante la scansione, ti suggerisco di provare temporaneamente a disattivare i firewall per vedere se la scansione così si conclude.

![screencapture-googlechrome-github-io-lighthouse-viewer-2023-05-24-10_26_04](https://github.com/italia/pa-website-validator/assets/105422742/74611c72-e3f2-4a19-a561-0356442edf8a)
![screencapture-googlechrome-github-io-lighthouse-viewer-2023-05-24-10_26_04-2](https://github.com/italia/pa-website-validator/assets/105422742/db929a6f-e800-4d80-b749-27dd68490052)

**Comment by Giaimo-DTD** [comment]
Ciao @miannella1 come hai risolto il problema?

**Comment by miannella1** [comment]
Praticamente se viene eseguito lo script con il link del portale in produzione funziona, mentre quello in locale no. Per ora stiamo procedendo aggiornando quello in produzione e testando lo script su quest'ultimo.
