### ISSUE TITLE
C.SI.3.4 - LICENZA E ATTRIBUZIONE - titolo della sezione non corretto

### ISSUE THREAD

**Issue by mariantanase** [italia/pa-website-validator#273]
Buongiorno,
Non passa la validazione nonostante l'inserimento corretto del titolo e dei tutti i data-element secondo:
 https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-3-4-licenza-e-attribuzione.
Ho eseguito il test con l'ultima versione del tool, la v. 2.3.1

Perché dice che il titolo della sezione e la dicitura non sono corrette ?
Che significa ?

![licenza-e-attribuzione-ko](https://user-images.githubusercontent.com/3976174/235862636-27fcdc57-4cb0-4b80-8cfe-67122f88de66.png)

**Comment by mariantanase** [comment]
Purtroppo non cambia nulla.
Erano già inseriti ma i tag `h3` al posto di `h1`. Adesso ho provato sostituendo con `h1` ma l'errore è lo stesso.
Tutti i `data-element` sono correttamente inseriti. Verificato e riverificato.
Non capisco più dove operare ?

**Comment by Giaimo-DTD** [comment]
non so se usavi il <p> per entrambi i paragrafi, penso in altri casi sia quello il problema. In ogni caso ottimo che sei riuscito a risolvere!

**Comment by mariantanase** [comment]
Come non detto.
Senza fare nessuna modifica, ripetendo il test (sempre con l'ultima versione del validatore per comuni 2.3.3), la validazione C.SI.3.4. **non passa**.
L'errore ricompare. Lo stesso. Il titolo della sezione non è corretto. Ma perché ? Il titolo è corretto. Come anche la dicitura.
A questo punto mi sembra un inconsistenza del validatore. Spero che va risolta presto.

**Comment by Giaimo-DTD** [comment]
@mariantanase ho fatto una verifica sul sito, il problema è che i data element richiesti sono stati inseriti in tutti gli h di tutti i titoli della pagina e in tutti i p della pagina, invece vanno solo sul titolo e sul corpo del messaggio richiesto
<img width="661" alt="image" src="https://github.com/italia/pa-website-validator/assets/105422742/f0b30b4d-ae04-4616-ac27-3c91819fa50d">
Se levate quelli in eccesso il test dovrebbe diventare verde :)

**Comment by mariantanase** [comment]
@Giaimo-DTD grazie mille! 
Non ci avevo pensato che solamente su qulla sezione vanno inseriti i data-element.
Problema risolto!
