### ISSUE TITLE
C.SI.2.6 - VALUTAZIONE DELL’ESPERIENZA D’USO, CHIAREZZA INFORMATIVA DELLA SCHEDA DI SERVIZIO

### ISSUE THREAD

**Issue by mariantanase** [italia/pa-website-validator#274]
Che significa "_Le domande di follow up non sono associate ai valori corretti_" ?
Effettuato il test con la versione 2.3.1

NOTA: Lo stesso errore con le domande di follow up esce anche al punto C.SI.2.5 - VALUTAZIONE DELL'ESPERIENZA D'USO, CHIAREZZA DELLE PAGINE INFORMATIVE

![csi26](https://user-images.githubusercontent.com/3976174/235865139-5785d53a-4110-456e-849e-208fb2c51806.png)

**Comment by Giaimo-DTD** [comment]
Indica che successivamente alla selezione del punteggio (da 1 a 5) non viene mostrata la domanda corretta quando viene selezionato da 1 a 3 o l'altra domanda quando viene selezionato 4 e 5

**Comment by mariantanase** [comment]
> Indica che successivamente alla selezione del punteggio (da 1 a 5) non viene mostrata la domanda corretta quando viene selezionato da 1 a 3 o l'altra domanda quando viene selezionato 4 e 5

Invece le vengono mostrate le domande giuste sia quanto viene selezionato da 1 a 3 che dopo quando viene selezionata da 4 a 5

**Comment by mariantanase** [comment]
@Giaimo-DTD puoi verificare anche questa issue per favore ? Ho verificato e riverificato tutte le possibili risposte in quella pagina ed e tutto corretto.

**Comment by marcumarras** [comment]
Salve, anche io continuo ad avere lo stesso problema

**Comment by mariantanase** [comment]
Può essere collegata a [questa issue](https://github.com/italia/pa-website-validator/issues/293#issuecomment-1571446889) ?
Ci sono le novità al riguardo ?
Grazie
