### ISSUE TITLE
Tema Child Wordpress Sito Web Scuole fallimento C.SC.1.1 e C.SC.1.2

### ISSUE THREAD

**Issue by ettoreperri** [italia/pa-website-validator#275]
Buongiorno,
sto completando la realizzazione di un portale basato sul tema wordpress del modello sito web scuole. 
Sebbene si tratti di un Convervatorio e pertanto mi aspetto che la validazione sulla struttura dei menù fallisca, questo però non dovrebbe accadere negli audit per la verifica della presenza di Bootstrap Italia e per la verifica dei font. 

![image](https://user-images.githubusercontent.com/36436650/235875583-15072d57-3749-462e-93e4-f43cc8c1579a.png)

L'errore riportato sembrerebbe causato dall'assenza di alcuni data-element necessari, tuttavia, ho verificato e dovrebbero essere rispettati per come specificato nella documentazione tecnica. C'è modo di ottenere un report dettagliato per capire quale/i data-element non riesce ad identificare?

Sto utilizzando l'ultima versione della build per Linux. 

Di seguito il link al portale:
https://cons.cz.it

@acattaneoacn 
@tensor5 

Saluti

**Comment by ettoreperri** [comment]
Aggiungo che fallisce anche la verifica del Criterio C.SC.1.3 a causa della presenza nello style del tema child della stringa "Template: ....."

**Comment by Giaimo-DTD** [comment]
Buongiorno @ettoreperri, la struttura della pagine dei servizi come indicato dai requisiti nell'uso dei data element non è rispettata, vengono utilizzati i link “service-type” direttamente come servizi e non come pagine che contengono servizi
