### ISSUE TITLE
C.SI.1.6 & C.SI.1.7

### ISSUE THREAD

**Issue by RiccardoMarino008** [italia/pa-website-validator#276]
Salve, abbiamo necessità di dar modo di aggiungere ulteriori voci di menu al menu principale del sito (municipality).
Come visibile da screen è stato inserito un "prova" avente, come da documentazione, data-element="custom-submenu".
Non ci è chiaro dove porre il successivo link <a data-element="custom-category-link">, dal momento che, avendolo inserito nella pagina di destinazione del menuItem avente  data-element="custom-submenu", ci fallisce sia il controllo 1.6 che l'1.7 come visibile in screen.
![Immagine 2023-05-08 095821](https://user-images.githubusercontent.com/52958490/236776097-56d739f8-d1ab-4259-9ca0-10830bc97595.png)

Ringraziamo in anticipo per qualsiasi delucidazione in merito.

**Comment by Giaimo-DTD** [comment]
Voci aggiuntive sono ammesse entro le percentuali indicate dal criterio, quindi in realtà entrambi i test risultano in condizione di tolleranza (quadrato giallo), ovvero non fanno esattamente quanto richiesto dal criterio, ma comunque si avvicinano a sufficienza. Se il test fosse fallito sarebbe indicato con il cerchio rosso.
Se volete avere il verde (100%) l'unica soluzione è mettere esattamente e solo le voci richieste in documentazione
