### ISSUE TITLE
Errore C.SI.1.1 in v2.3.2 mac arm

### ISSUE THREAD

**Issue by NicolaZivago** [italia/pa-website-validator#281]
Ciao, con l'ultima versione di validatore per Mac arm non mi valida il criterio C.SI.1.1, mentre con test lanciato su Windows passa regolarmente.
Con la precedente versione il criterio veniva correttamente validato.

**Comment by NicolaZivago** [comment]
Ciao, ti ho scritto su Slack

**Comment by Giaimo-DTD** [comment]
Non riusciamo a riprodurla, avviene ancora?
