### ISSUE TITLE
C.SC.1.1 evitare il controllo dei font su file non html

### ISSUE THREAD

**Issue by emafer** [italia/pa-website-validator#282]
Gent.mi,
usando delle estensioni per la gestione della cache accade che l'app possa mal interpretare i link a file non html: 
ad esempio
![image](https://github.com/italia/pa-website-validator/assets/2566181/a4c78287-c4c1-47ad-be25-7c50cf244f60)

Come vedete in questo caso l'app prova a leggere il file pdf, andando poi in errore.

E' possibile fare in modo che l'app riconosca che il file non è un html e quindi non lo parsi?
Grazie!

**Comment by Giaimo-DTD** [comment]
Non mi è chiarissimo il problema, intendi che la destinazione di una delle pagine analizzate è un pdf invece che una pagina oppure che in una delle pagine analizzate è presente il link a un pdf che fa fallire il test?
Nel primo caso, la destinazione di link a pagine non dovrebbero essere pdf ma piuttosto pagine che introducono l'argomento e all'interno della quale è presente il link al pdf. Se invece è il secondo caso il test non dovrebbe fallire, se mi fornisci il link alla pagina provo a verificare

**Comment by emafer** [comment]
Salve,
provo a spiegarmi meglio, anche se mi pare tu abbia chiarito 
Il rimando era diretto dal menù di secondo livello quindi direi che rientriamo nel primo caso. 
quindi faccio aggiornare i link nel caso in cui utilizzino il rimando diretto al pdf.
Grazie.
