### ISSUE TITLE
problema con R.SC.2.2 LICENZA E ATTRIBUZIONE 

### ISSUE THREAD

**Issue by GiuseppeBronty** [italia/pa-website-validator#285]
Buonasera, anche l'ultima versione dell'app, come le precedenti, continua a produrmi l'errore su R.SC.2.2 LICENZA E ATTRIBUZIONE 
![licenzaeattribuzione](https://github.com/italia/pa-website-validator/assets/133392133/79d61bfa-b205-4774-8921-758d312f6435), per quanto il codice con i data element sia prodotto seguendo la documentazione corretta:

![codice1](https://github.com/italia/pa-website-validator/assets/133392133/a95aee28-ea8c-4e37-b9b3-62da8473858c)
![codice2](https://github.com/italia/pa-website-validator/assets/133392133/e67493eb-533d-41e1-aeaf-e669ca848884)

potrei avere supporto in merito?

**Comment by Giaimo-DTD** [comment]
prova a inserire il testo in due <p> con entrambi il data element come l'esempio qui sotto (aggiungendo l'url), dovrebbe risolvere il problema
```
<div>
   <h1 data-element="legal-notes-section">
       Licenza dei contenuti
   </h1>
   <p data-element="legal-notes-body">
      In applicazione del principio open by default ai sensi dell’articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con licenza CC-BY 4.0.
   </p>
   <p data-element="legal-notes-body">
      Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.
   </p>
</div>
```

**Comment by Giaimo-DTD** [comment]
@GiuseppeBronty inserendo il codice indicato il problema è stato risolto?

**Comment by GiuseppeBronty** [comment]
si scusa se non ho risposto più, ma mi è passato di mente; copiando il testo che mi hai suggerito il sito web supera la validazione per il criterio R.SC.2.2 LICENZA E ATTRIBUZIONE; grazie mille per il supporto
