### ISSUE TITLE
Problema con C.SI.2.1

### ISSUE THREAD

**Issue by hal-berto** [italia/pa-website-validator#286]
Buongiorno, anche l'ultima versione dell'app, come le precedenti, continua a produrmi il seguente errore al punto C.SI.2.1:
![immagine](https://github.com/italia/pa-website-validator/assets/18208387/719c50f1-fe6c-49cd-8c81-6ca04b7ca08a)

L'errore è causato dal confronto che viene fatto all'interno dell'app di verifica tra il link del pulsante in cima alla pagina del servizio e il link del pulsante presente nei dettagli del servizio, che vengono visti come non uguali, anche se in realtà sono identici (per esempio: https://demopnrr.comune-openweb.it/form/prenotazione-appuntamento?id=2).
A seguito di alcune prove ho potuto verificare che se il link non presenta parametri, la valutazione del punto da esito positivo.
Per una verifica potete fare riferimento ai pulsanti di prenotazione appuntamento presenti alla pagina:
https://demopnrr.comune-openweb.it/servizio/servizi-sociali-anziani
E' una scelta "di design" o si tratta effettivamente di un problema dell'app di verifica?

**Comment by hal-berto** [comment]
Ho provato a togliere il codice commentato ma ottengo ugualmente un punteggio negativo. Per superare il test devo proprio togliere i parametri dall'url

**Comment by hal-berto** [comment]
Qualcuno ha riscontrato lo stesso problema?

**Comment by Giaimo-DTD** [comment]
Abbiamo identificato il problema, verrà rilasciata a breve una nuova versione che lo risolve https://github.com/italia/pa-website-validator/pull/311
