### ISSUE TITLE
Errori multipli eseguendo app verifica scuole versione 2.3.3

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/pa-website-validator#287]
Utilizzando l'app di verifica versione 2.3.3, quando eseguita, riporta numerosi errori del tipo:
"Il caricamento della pagina è stato troppo lento e non è stato completato entro il limite di tempo. I risultati potrebbero essere incompleti."
Con la versione 2.2.1 tutto funziona correttamente
![Errori2 3 3](https://github.com/italia/pa-website-validator/assets/115779224/3614627e-7571-484a-b7a9-c943744f775c)
![Errori2 3 3_1](https://github.com/italia/pa-website-validator/assets/115779224/854ff3f9-9103-49ea-9062-a61c7528a1e2)

**Comment by Giaimo-DTD** [comment]
E' molto probabile il problema sia dovuto a un firewall che blocca la richiesta dell'app, ti consiglio di riprovare dopo aver disattivato il firewall per verificare se il problema è effettivamente quello.
In ogni caso se ci fornisci l'url proviamo a fare una verifica

**Comment by CampusDaVinci** [comment]
Salve, il problema sembra essere la gestione dell'accesso se è presente un plugin per la gestione dei cookie e privacy policy tipo Iubenda.
Disattivando questi plugin l'app funziona di nuovo.
https://campusdavinci.edu.it/
Questa è la URL, se volete potete provare voi stessi
Grazie per il supporto
