### ISSUE TITLE
Errori nel C.SC.1.2 da sito con PWA abilitato e ServiceWorker

### ISSUE THREAD

**Issue by giovannicaini** [italia/pa-website-validator#288]
Se c'è un ServiceWorker che fa il fetch delle pagine, il controllo C.S.C.1.2 fallisce perchè non trova la libreria bootstrap-italia (ovviamente il problema è che è il service-worker che fa da proxy per la richiesta ed evidentemente il validatore non recepisce questo response mediato)

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
