### ISSUE TITLE
Nel validatore per le scuole, nelle "schede servizio" il validatore richiede obbligatorio il campo "Ulteriori informazioni" che nelle specifiche tecniche non è segnato come obbligatorio

### ISSUE THREAD

**Issue by giovannicaini** [italia/pa-website-validator#289]

**Comment by sviluppoRobyone** [comment]
Buongiorno, riapriamo il ticket, in quanto il modello di architettura v1.0 segna le "Ulteriori informazioni" come informazione facoltative. Di conseguenze il controllo di quella proprietà non dovrebbe esserci. 
Chiediamo chiarimenti.
