### ISSUE TITLE
R.SI.1.1 - Warnings segnalati in metatag ma validatore schema.org non riporta problemi

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#290]
Sto migrando il sito di un comune, all'interno della scheda servizio all'url qui sotto sono presenti i meta tag richiesti:

https://montescano.epublic.it/it-it/servizi/anagrafe-e-stato-civile/accesso-civico-654-6170-1-aa930119350bed54d6622a399b7d4d9b

Con l'ultima versione del validatore (2.3.3) ottengo questo warning:

Metatag non presenti o errati: 
audience.name, availableChannel.serviceLocation.address.object

Il validatore schema.org invece non riporta problemi: https://validator.schema.org/#url=https%3A%2F%2Fmontescano.epublic.it%2Fit-it%2Fservizi%2Fanagrafe-e-stato-civile%2Faccesso-civico-654-6170-1-aa930119350bed54d6622a399b7d4d9b

Riguardo audience.name nella documentazione non è specificato che debba avere alcun valore, l'unico dato riportato obbligatorio per audience è:  "il testo a chi è rivolto nell’attributo json audience>audienceType;", però nell'esempio poco sotto con la struttura del json nella documentazione è riportato anche l'attributo name = ""...
Invece availableChannel.serviceLocation.address.object come si vede dal validatore schema.org è correttamente presente.

Errata documentazione o bugs del validatore?
Grazie.

**Comment by MarcoTesta-EP** [comment]
Buongiorno, vedo che la fix per questo problema c'è già da tempo ed è presente anche una pull request, si sa quando verrà inserita nella release? Grazie

**Comment by tensor5** [comment]
La #337 è già nella release, qual è il problema?

**Comment by MarcoTesta-EP** [comment]
Rifarò i test allora grazie.

**Comment by MarcoTesta-EP** [comment]
Buongiorno,
ho rifatto i test il warning su audience.name è risolto ma permane quello su:

availableChannel.serviceLocation.address.object

Il mio metadato è fatto così:

{"serviceOperator":{"name":"Comune di Montescano","@context":"http://schema.org","@type":"Organization"},"areaServed":{"name":"Comune di Montescano (PV)","@context":"http://schema.org","@type":"AdministrativeArea"},"audience":{"audienceType":" A tutti i cittadini\r","@context":"http://schema.org","@type":"Audience"},"availableChannel":{"serviceLocation":{"address":[{"addressLocality":"Montescano","postalCode":"27040","streetAddress":"Via Roncole, 1","@context":"http://schema.org","@type":"PostalAddress"}],"name":"Servizio Segreteria e Demografico","@context":"http://schema.org","@type":"Place"},"serviceUrl":"https://www.comune.montescano.pv.it/it-it/servizi/ambiente/raccolta-rifiuti-107-6149-1-bd8cae4290c8747fd6653f465b6d667e","name":"Dove rivolgersi","@context":"http://schema.org","@type":"ServiceChannel"},"serviceType":"Ambiente","name":"Raccolta Rifiuti","@context":"http://schema.org","@type":"GovernmentService"}

Che validato con Schema.org non da alcun problema e come si vede availableChannel.serviceLocation.address è presente.
Sbaglio io o è un bug?
Grazie!

**Comment by MarcoTesta-EP** [comment]
Buongiorno, segnalo che questo problema è sempre aperto... grazie

**Comment by MarcoTesta-EP** [comment]
Buongiorno, risegnalo la cosa, il problema è sempre aperto. Grazie.

**Comment by MarcoTesta-EP** [comment]
Buongiorno, segnalo nuovamente se è possibile risolvere questo problema, grazie!

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
