### ISSUE TITLE
Prenotazione appuntamento

### ISSUE THREAD

**Issue by MassyCare99** [italia/pa-website-validator#292]
Salve, ci chiediamo come mai la prenotazione appuntamenti, che è una pagina normale a tutte le altre, impieghi dai 5/10 minuti per essere analizzate.
Aggiungiamo che la pagina NON va in timeout, perchè è di 20 secondi, mentre quì stiamo impiegando minuti e minuti

attendo
![cattura (6)](https://github.com/italia/pa-website-validator/assets/102411343/5e199652-63d0-4956-8996-1a2393c46855)

**Comment by Giaimo-DTD** [comment]
C'è una latenza dovuta al fatto che l'app naviga il sito usando la libreria puppeteer che lancia un processo Chrome, che è già pesante di per sé, e tutto questo viene ripetuto più volte per le varie pagine.
