### ISSUE TITLE
C.SI.2.5 - VALUTAZIONE DELL'ESPERIENZA D'USO, CHIAREZZA DELLE PAGINE INFORMATIVE

### ISSUE THREAD

**Issue by fnori77** [italia/pa-website-validator#293]
Salve, il tool restituisce questo errore:
<img width="814" alt="Screenshot 2023-05-25 alle 13 54 25" src="https://github.com/italia/pa-website-validator/assets/126147260/5d09443e-8862-4d7e-9976-f00ad1093bbd">

I data-element sono stati inseriti.
Grazie.

**Comment by fnori77** [comment]
Grazie per aver risposto. Abbiamo provato ad eseguire l'asseverazione da un altro ip, ma il risultato è lo stesso.
Il sito in questione è https://comune.godrano.pa.it
Grazie

**Comment by marcumarras** [comment]
stesso errore anche per noi

**Comment by marcumarras** [comment]
debuggando il tool di validazione aggiungendo un wait di qualche secondo alla riga 290 del fle /scr/utils/municipality/utils.ts passo la validazione. 
sembra quindi che le pagine dei servizi (implementate come indicato nei mokup) siano troppo pesanti per il componente.

**Comment by Giaimo-DTD** [comment]
Grazie @marcumarras facciamo dei test e vi facciamo sapere

**Comment by Giaimo-DTD** [comment]
Abbiamo identificato il problema, verrà rilasciata a breve una nuova versione che include il fix https://github.com/italia/pa-website-validator/pull/315
Fateci sapere se poi dovesse ancora essere presente per favore
