### ISSUE TITLE
Assicurati che il testo rimanga visibile durante il caricamento dei caratteri web

### ISSUE THREAD

**Issue by fnori77** [italia/pa-website-validator#297]
Salve, il font-display è impostato su swap ma il tool continua a restituire un punteggio non conforme.

**Comment by Giaimo-DTD** [comment]
Buongiorno, potresti fornirci l'url del sito per comprendere meglio il caso? Grazie

**Comment by fnori77** [comment]
Salve, ad esempio sul sito comune.godrano.pa.it <http://comune.godrano.pa.it/>.
 <https://www.we-com.it/>	
Francesco Nori
Webmaster

Email: ***@***.*** ***@***.***>
Mobile: +39.334.684.5816
Viale dei Caduti nella Guerra di Liberazione 446 Roma
 <https://www.facebook.com/wecom.vt>    <https://www.linkedin.com/company/we-com-s-r-l->  
Questa e-mail, nonché qualsiasi file allegato alla presente, è destinata esclusivamente ai destinatari indicati in indirizzo o a chi sia stato da quelli autorizzato. Se avete ricevuto per errore questa e-mail, vi chiedo cortesemente di avvisarmi immediatamente e di distruggere permanentemente l’originale e qualsiasi copia della presente nonché qualsiasi stampa di questa.

**Comment by tensor5** [comment]
Buongiorno @fnori77, la diagnostica a cui fai riferimento è propria di [Lighthouse](https://developer.chrome.com/docs/lighthouse/) su cui noi non abbiamo controllo. Dubito però che sia sbagliata, e comunque non fa parte dei nostri criteri.
