### ISSUE TITLE
Errore su C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - App valutazione SCUOLE

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/pa-website-validator#307]
Salve,
ogni volta che eseguiamo il test con l'app (ora in versione 2.3.4) 
https://campusdavinci.edu.it/
otteniamo sempre la non conformità sull'utilizzo dei font, nonostante noi usiamo esclusivamente il tema fornito dal ministero .
![image](https://github.com/italia/pa-website-validator/assets/115779224/8a21ee60-1328-4b4a-af05-8018f96d9032)
Guardando i .CSS i font sono indicati in modo corretto.
Cosa sta succedendo ?

**Comment by Giaimo-DTD** [comment]
I "nomi" dei font, come buona pratica per assicurarsi che siano esattamente gli stessi, viene richiesto che rispettino tutte le maiuscole del nome stesso. Quindi i font dovrebbero essere nominati "Titillium Web", "Lora" e "Roboto Mono"

**Comment by CampusDaVinci** [comment]
Pienamente d'accordo, ed infatti nei CSS i nomi sono scritti tutti correttamente es:
.calendar-vertical .calendar-date .calendar-date-day p {
    font-family: "Roboto Mono", monospace;

.article-wrapper .in-evidence p {
    margin: 0 0 15px 0;
    font-family: "Titillium Web", Geneva, Tahoma, sans-serif;
    font-size: 1.13rem
}

.text-border-left {
    font-family: Lora, Georgia, serif;
    margin: 0 0 40px 40px;
    padding: 0 0 0 30px;
    border-left: 4px solid #51758d
}
quindi, mi sa che è un problema dell'app di verifica no ?

**Comment by Giaimo-DTD** [comment]
Ciao @CampusDaVinci dalle nostre scansioni non identifichiamo più il problema. Come avete risolto?

**Comment by CampusDaVinci** [comment]
> Ciao @CampusDaVinci dalle nostre scansioni non identifichiamo più il problema. Come avete risolto?

Salve, il problema è legato a tools e plugin di mimificazione del javascript/html che rinominano sempre tutti i tag/nomi dei font in lettere minuscole.
Essendo l'app case-sensitive, questo fa si che tutti i controlli falliscono anche se il font ha in origine il nome corretto.
Capisco che "formalmente" l'avere un nome con lettere minuscole sia un errore, ma se si suggerisce (nella prima parte dell'app di verifica) l'uso di questi tools per velocizzare le prestazioni e poi gli stessi tools fanno fallire le verifiche (della seconda parte) essere così stringenti non ha molto senso.
