### ISSUE TITLE
C.SI.1.3: mancata verifica di tutte le schede servizi

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#308]
Utilizzando l'ultima versione del validatore 2.3.4 che fornisce il log delle pagine esaminate mi sono reso conto che soltanto le schede dei servizi presenti nella pagina di primo livello servizi sono validate (i primi 5 visibili sotto la ricerca come richiesto da modello), questo nonostante nella pagina sia presente il bottone (ajax) che permette il caricamento di altri servizi nell'elenco con il data-element corretto.
Mi sarei comunque aspettato che tutte le schede dei servizi fossero validate, considerato il requisito stringente indicato, o tramite questo elenco o passando dalle categorie di servizi.
Posso fornire url in privato.
Grazie.

**Comment by Giaimo-DTD** [comment]
Sì grazie, mi trovi su slack come "Federico Giaimo".
Siete sicuri di aver implementato il load degli ulteriori elementi nella lista come indicato?

**Comment by MarcoTesta-EP** [comment]
To ho scritto grazie.

**Comment by Giaimo-DTD** [comment]
A breve rilasciamo una nuova versione per risolvere il problema https://github.com/italia/pa-website-validator/pull/315
