### ISSUE TITLE
Errore su C.SI.3.1 - COOKIE a causa di cookie per l'autenticazione tramite shibboleth

### ISSUE THREAD

**Issue by mluigi** [italia/pa-website-validator#312]
Implementiamo l'autenticazione SPID e CIE tramite proxy Shibboleth, presente su un sottodominio del sito (idp.dominio.it), e durante la fase di autenticazione viene creato un cookie con il sottodominio come origine, il quale fa fallire C.SI.3.1.
Credo che il validator rilevi il cookie poiché segue il link di login (/saml/login), il quale fa il redirect verso la pagina di login del proxy.

Ci sono delle indicazioni per casi di questo genere?

**Comment by tensor5** [comment]
Ciao @mluigi, ci puoi condividere l'url?

**Comment by mluigi** [comment]
Ciao @tensor5, come posso condividertelo per via privata?

**Comment by tensor5** [comment]
@mluigi, mi puoi trovare sul [canale Slack](https://slack.developers.italia.it/).

**Comment by tensor5** [comment]
@mluigi , dovresti evitare il redirect nella pagina di login perché stai di fatto aggirando il criterio C.SI.5.2 sul dominio istituzionale.

**Comment by mluigi** [comment]
Il bando SPID/CIE prevede la realizzazione di un proxy IAM, che di fatto prevede il redirect su un altro dominio/sottodominio. Come si gestisce in questo caso?

**Comment by Giaimo-DTD** [comment]
@mluigi in questo caso specifico si dovrebbe risolvere con questa PR che rilasceremo a breve https://github.com/italia/pa-website-validator/pull/320
