### ISSUE TITLE
Criterio C.SI.1.3 - Data-element service-area duplicato per contatti e unità organizzativa

### ISSUE THREAD

**Issue by lucabertoni** [italia/pa-website-validator#314]
Buongiorno,  
scrivo in merito al requisito [5.3. Criterio C.SI.1.3 - Schede informative di servizio per il cittadino](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-1-3-schede-informative-di-servizio-per-il-cittadino).  

Nella documentazione è riportato:
«Contatti»: viene controllata la presenza di un tag \<div\> con data-element="service-area" che identifica i contatti.  

«Unità organizzativa responsabile»: viene controllata la presenza di un tag HTML con data-element="service-area" che identifica l’area responsabile del servizio e che questo abbia almeno 3 caratteri;  

È corretto che il data-element _service-area_ sia duplicato per entrambe le sezioni?

**Comment by Giaimo-DTD** [comment]
Buongiorno, è corretto, nel senso che l'unità organizzativa responsabile è un dettaglio di contatti, quindi va bene abbiano lo stesso data element. Riporto l'esempio:
```
<h2>Contatti</h2>
   <div><p>
           <a href="#" data-element="service-area">Unità organizzativa</a>
       </p>
       <div class="card-text"><p>. . .</p></div>
   </div>
```
