### ISSUE TITLE
R.SC.1.1 non validato

### ISSUE THREAD

**Issue by flaggz** [italia/pa-website-validator#318]
Versione app: 2.3.4
Analisi: Approfondita
URL: lamc.edu.it
Errore: Uno o più data-element necessari per condurre il test non sono stati trovati. Verifica il capitolo sui Requisiti tecnici nella Documentazione delle App di valutazione per risolvere il problema.

Pulsante cerca
```<button type="button" class="d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#search-modal" data-element="search-modal-button"><i class="fab fa-sistrix fa-lg"></i></button>```

Form
```
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
<h2 class="modal-title h5 " id="cercaTitle">Cerca nel sito</h2>
<button type="button" class="close dismiss" data-bs-dismiss="modal" aria-label="Chiudi">
<i class="fa fa-close"></i>
</button>
</div>
<div class="modal-body">
<form method="get" action="https://lamc.edu.it/">
<div class="row mb-3 align-items-center"><div class="col-10">
<input type="text" value="" name="s" placeholder="Cerca servizi, notizie o documenti" autocomplete="off" data-element="search-modal-input" class="focus--mouse" data-focus-mouse="true"></div><div class="col-2">
<button type="submit" data-element="search-submit"><i class="fa fa-search fa-xl"></i></button>
</div></div>
</form>
</div>
</div>
</div>
```

Pagina risultati

```
<div class="col-9">
    <h2 class="mb-4">Risultati di ricerca</h2> 
    Argomenti 
    <ul id="voc_controllato" data-element="all-topics">
            <li>
          <div>
             <label>Registro elettronico</label>
          </div>
        </li>
        </ul>
...

```

**Comment by flaggz** [comment]
La 2.4.1 valida le raccomandazioni progettuali ma invalida tutti i criteri di conformità

`ERROR https://lamc.edu.it/il-liceo-artistico-g-cantalamessa/: TimeoutError: Navigation timeout of 20000 ms exceeded`

**Comment by tensor5** [comment]
Ciao @flaggz, ho fatto una prova e non ho riscontrato errori.

**Comment by Petrillo96** [comment]
Con la 2.4.1 i criteri di conformità erano al 100%, mentre con la 2.5.0 siamo scesi all'88%. Mi da l'errore nella parte C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT linkandomi il sito esterno dell'Albo.

**Comment by Giaimo-DTD** [comment]
@Petrillo96 In base ai criteri C.SC.1.4 e 1.5 non devono essere presenti nel menu di primo e secondo livello voci che rimandano a pagine esterne al dominio del sito. Se "Albo" rimanda a una pagina esterna, l'errore da te segnalato dovrebbe essere dovuto al fatto che questa pagina poi non rispetta i criteri
