### ISSUE TITLE
Crash validatore windows 2.4.0

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#321]
Buongiorno,
lanciando l'ultima release del validatore (windows x-64) va in crash, l'errore è:

2023/06/29 16:39:37 caxa stub: Failed to run command: exec: "env": executable file not found in %PATH%

Grazie.

**Comment by Petrillo96** [comment]
Confermo, ho provato ad eliminare la cartella in questione ma da lo stesso risultato
