### ISSUE TITLE
Versione bootstrap

### ISSUE THREAD

**Issue by MassyCare99** [italia/pa-website-validator#325]
Ho aggiornato bootstrap italia alla 2.3.5 ma da app continua a segnalare quella vecchia.

allego 
![Cattura](https://github.com/italia/pa-website-validator/assets/102411343/1fb362b5-ff2a-4a33-9483-5f0204d9e040)
![Cattura](https://github.com/italia/pa-website-validator/assets/102411343/bbf6f114-0a17-47aa-9872-b5ecfa90dba9)

**Comment by tensor5** [comment]
L'applicazione controlla prima il valore della variabile `window.BOOTSTRAP_ITALIA_VERSION`. Può essere che non hai aggiornato la parte JS di Bootstrap Italia.
