### ISSUE TITLE
Errore app di valutazione v2.4.1 comuni

### ISSUE THREAD

**Issue by Leonardoquinto** [italia/pa-website-validator#329]
Buongiorno,
ho notato che con la nuova versione dell'app di valutazione comuni (v2.4.1. Windows) si apre correttamente però appena si tenta di eseguire un test con sito in produzione, dopo pochi secondi, l'applicativo si chiude.

Chiedo cortesemente di avere maggiori informazioni e, se è già stata evidenziata la problematica, quali potrebbero essere i tempi di attesa per una nuova versione.

Ringrazio
Buona giornata

**Comment by tensor5** [comment]
Ciao @Leonardoquinto, qual è la tua versione di Windows?

**Comment by Leonardoquinto** [comment]
Ciao @tensor5, utilizziamo la versione di Windows server 2012.

**Comment by tensor5** [comment]
Nel rilascio 2.4.0 abbiamo aggiornato Chrome (che viene utilizzata in background dall'app di valutazione) alla versione 113, per cui temo che Windows Server 2012 non sia più supportato. È richiesto almeno Windows 10 o Windows Server 2016.
https://support.google.com/chrome/a/answer/7100626?hl=en
