### ISSUE TITLE
regress sui cookies della versione 2.5

### ISSUE THREAD

**Issue by lia55556** [italia/pa-website-validator#331]
Buongiorno, ho consegnato il lavoro alla mia scuola a fine giugno come previsto dal bando, con report pienamente positivo sia sui criteri che sulle raccomandazioni; oggi vengo chiamata dalla segreteria e mi dicono che è stata rilasciata una nuova versione i primi di luglio, l'ho provata e mi va in regress sul criterio dei cookies. Mi spiegate cosa caspita avete cambiato sul controllo dei cookies? Mi date indicazioni su come posso rimediare?  E soprattutto vi sembra corretto continuare a cambiare la carte in tavola anche dopo i termini di scadenza del progetto? 
L'indirizzo del mio sito è https://www.iisspietrosette.edu.it/
Di seguito l'ultimo report

![cookies](https://github.com/italia/pa-website-validator/assets/125757301/b7dae81b-e602-42d7-9ca2-5b0c27c95c50)

Grazie.

**Comment by Giaimo-DTD** [comment]
Le notifiche che vedi significano che abbiamo identificato un bug nell'app che è stato risolto e verrà rilasciato nella prossima versione, il problema sui cookie pertanto non era imputabile al sito o a un cambio delle regole.
