### ISSUE TITLE
TEMA

### ISSUE THREAD

**Issue by MassyCare99** [italia/pa-website-validator#335]
Salve,
noi usiamo CMS proprietario, per quale motivo però dobbiamo perdere del punteggio passando da 100% a  97% ?
Il tema NON è obbligatorio, deve semmai essere segnalato ma assolutamente NON togliere punteggio. 

![Cattura](https://github.com/italia/pa-website-validator/assets/102411343/5c25012b-4e0e-4a9d-a5da-ecb6ce2adfb7)

**Comment by Giaimo-DTD** [comment]
Come indicato in [documentazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/report-e-risultati.html#barra-superiore-report), il punteggio nella barra superiore non ha alcun valore ai fini della valutazione di qualità di un sito, tranne nel caso del punteggio sulle performance.
Tenendo solo conto del punteggio sulle performance, potete ignorare qualsiasi altro punteggio. E' una caratteristica di lighthouse che non è possibile eliminare.
Ciò che va invece valutato è il risultato ai singoli test, che influenzano le valutazioni tecniche in fase di asseverazione, ma non combaciano con queste. Si ricorda che il risultato "tolleranza" corrisponde comunque con il [superamento del test](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/report-e-risultati.html#legenda).
