### ISSUE TITLE
Problemi nella verifica usando i modelli per pagine statiche

### ISSUE THREAD

**Issue by CarImp64** [italia/pa-website-validator#336]
Buongiorno.
Sto sviluppando il sito della scuola a partire dalle pagine statiche per vari motivi. Attualmente sto creando i modelli con dreamweaver e scrivendo delle pagine che poi i miei colleghi riempiranno con i contenuti.  https://www.itiomar.it
Fin dall'inizio ho cominciato ad usare l'app per la validazione.  Ho cercato di seguire scrupolosamente le linee guida ma, non sono mai riuscito ad superare il valore 0 (zero) nelle "Raccomandazioni progettuali" sia in R.SC.1.1 VOCABOLARI CONTROLLATI  e neppure nella R.SC.1.2 schede informative di servizio. 
In pratica ho preso la parte centrale del modello fornito su https://italia.github.io/design-scuole-pagine-statiche/ e copiato il contenuto in un modello di base in cui ho predefinito intestazioni preload, javacript ...
L' app per il test mi fornisce dei suggerimenti (Voci mancanti o senza contenuto: Come si accede al servizio, Cosa serve, Tempi e scadenze, Ulteriori informazioni), ma in realtà sono presenti (solito copia / incolla, mancavano due voci nel modello CAP e GPS e le ho aggiunte) ma non capisco cos'altro possa mancare.
per R.SC.1.1 suggerisce "Uno o più data-element necessari per condurre il test non sono stati trovati. Verifica il capitolo sui Requisiti tecnici nella Documentazione delle App di valutazione per risolvere il problema."  non dice dove o cosa non avrebbe trovato.
Non esiste un modo per fare il solo test R.SC.1.1 in modo più analitico?
Anche per quanto riguarda i criteri progettuali Non riconosce l'uso dei font e nemmeno di bootstrap 1.6.4 .
Cosa posso fare?
Grazie

**Comment by tensor5** [comment]
> L' app per il test mi fornisce dei suggerimenti (Voci mancanti o senza contenuto: Come si accede al servizio, Cosa serve, Tempi e scadenze, Ulteriori informazioni), ma in realtà sono presenti (solito copia / incolla, mancavano due voci nel modello CAP e GPS e le ho aggiunte) ma non capisco cos'altro possa mancare.

Mancano i relativi `data-element="service-booking-access"`, `data-element=“service-calendar-text”`, etc., come da documentazione.

**Comment by CarImp64** [comment]
Buongiorno. Grazie per avermi risposto. Ho provato a consultare il file "architettura dell'informazione" e nella documentazione online ma non sono riuscito a trovare nulla.
Non riesco a trovare all'interno dei modelli online ( e nemmeno nei modelli della distribuzione locale che ho appena aggiornato e ricostruito https://github.com/italia/design-scuole-wordpress-theme.git) l'uso di questi metadati. Le dispiacerebbe dirmi cosa consultare in particolare? Grazie anticipatamente

**Comment by CarImp64** [comment]
Trovato
