### ISSUE TITLE
Problema verifica conformità

### ISSUE THREAD

**Issue by carlettone96** [italia/pa-website-validator#339]
Buongiorno
chiedo un aiuto.
Ho aggiornato il sito da v2.3.2 a v2.4.0. Dopo l'aggiornamento l'app di validazione v2.5.1 non valida più e restituisce molti "Uno o più data-element necessari per condurre il test non sono stati trovati...." che secondo me sono ingiustificati.
www.icpine.eu
Potete aiutarmi a capire? Grazie

**Comment by tensor5** [comment]
Ciao @carlettone96, mancano i `data-element="service-type"`, come da documentazione.

**Comment by carlettone96** [comment]
Grazie mille, ho corretto!
