### ISSUE TITLE
Errore validazione criterio C.SI.3.3 - Informativa privacy modello comuni

### ISSUE THREAD

**Issue by lucabertoni** [italia/pa-website-validator#341]
Buongiorno,

sto usando la versione 2.5.1 dell'app.

Per quanto riguarda il criterio menzionato il report è il seguente:

| Risultato | Testo del link | Pagina di destinazione del link | Pagina esistente | Pagina sicura |
|--------|--------|--------|--------|--------|
| Il link non è nel footer o non invia a una pagina esistente o sicura. | Privacy policy | [/info/privacy-e-cookie-policy](https://localhost:5001/info/privacy-e-cookie-policy) | No | No | 

Il test è effettuato in locale. 

Cliccando sul link aggiunto al valore della terza colonna ("Pagina di destinazione del link") la pagina aperta è corretta ed esistente. Il report però riporta che non esiste.

**Comment by tensor5** [comment]
Ciao @lucabertoni, è possibile avere un link ad una versione di produzione? In questo modo potremmo verificare anche il #342 e #343.

**Comment by lucabertoni** [comment]
Buongiorno @tensor5,

grazie per la disponibilità. Appena riesco ti preparo un ambiente in produzione.
Mi puoi scrivere un tuo contatto dove inviarti il link?

**Comment by tensor5** [comment]
Mi trovi sul [canale Slack di Developers Italia](https://slack.developers.italia.it/).

**Comment by lucabertoni** [comment]
Buongiorno @tensor5,

ti segnalo che in produzione funziona tutto correttamente per quanto riguarda #341 e #342.

Lascio a te la scelta di chiudere oppure di investigare ulteriormente questi due issues.

Ti ho inviato su slack il link per verificare #343.
