### ISSUE TITLE
R.SC.1.1 Vocabolari controllati

### ISSUE THREAD

**Issue by CarImp64** [italia/pa-website-validator#344]
Buona sera
Sto sempre preparando il sito della scuola https://www.itiomar.it Ho ancora un ostacolo che non riesco a superare il test. L'errore dichiara che: Meno del 50% degli argomenti appartengono alle voci del modello o l'elenco degli argomenti non è presente nella pagina dei risultati di ricerca.
% di argomenti presenti nell'elenco del modello: 43%
Argomenti non presenti nell'elenco del modello: documenti, luoghi, strutture, le persone.
Grazie per qualunque indicazione.

**Comment by tensor5** [comment]
Almeno il 50% delle voci che compaiono sulla sinistra in [questa pagina](https://www.itiomar.it/struttura/risultati-ricerca.php?) devono far parte delle cosiddette "Parole della scuola", la cui lista trovi [qui](https://github.com/italia/pa-website-validator/blob/main/src/storage/school/controlledVocabulary.ts).

**Comment by CarImp64** [comment]
Ok. Grazie mille.

**Comment by CarImp64** [comment]
Perché segnala la mancanza di documenti se la parola documenti non è presente nella lista di controllo?

**Comment by tensor5** [comment]
È proprio questo il punto: la parola "documenti" è presente in pagina, ma non è nel vocabolario controllato fornito da noi. L'applicativo segnala i termini di ricerca che non sono nel nostro vocabolario.

**Comment by CarImp64** [comment]
Perbacco!
