### ISSUE TITLE
R.SC.1.2 - SCHEDE INFORMATIVE DI SERVIZIO

### ISSUE THREAD

**Issue by camillo860** [italia/pa-website-validator#346]
Buongiorno, ho cercato sui vecchi post ma non ho trovato niente, il sistema in uso è un OS X 11.6.1 e uso Chrome 114.0.5735.198 
Quando eseguo l'applicazione di validazione, al test R.SC.1.2 mi verifica solamente due servizi ( ce ne sono di più), il primo dice che manca "A cosa serve" e il secondo non da errore.
Credo che l'applicazione non scarichi sempre i dati dal sito ma usa i dati in cache ( il sito non la cache attiva).
sito https://www.isiss-magarotto.edu.it/
[Allego screen del problema
](https://www.isiss-magarotto.edu.it/img/schermata1.png)

**Comment by tensor5** [comment]
Ciao @camillo860, devi aver cambiato qualcosa perché ho rifatto il test in locale e rileva 4 schede servizio che passano l'`R.SC 1.2`.
