### ISSUE TITLE
Impossibile analizzare correttamente gli errori

### ISSUE THREAD

**Issue by peppelr1** [italia/pa-website-validator#348]
Salve, per come è impostato il validatore, non è possibile risalire all'errore principale, sarebbe possibile avere a disposizione lo stack di errori completo? In modo da poter risolvere prima eventuali problemi.

**Comment by sjpagan** [comment]
Salve, ho lo stesso problema, è possibile modificare il codice in modo rapido per ottenere ciò ? abbiamo l'esigenza di effettuare la validazione e il tool così com'è fa uscire matti, per poter ottenere la lista degli errori.

Al momento non c'interessa della bellezza, basta che tira fuori un report.

In ogni caso tra quanto è prevista la nuova release ?

**Comment by tensor5** [comment]
Non abbiamo una data precisa, ma faremo rilasci incrementali, quindi appena avremo qualcosa di usabile ve la condivideremo.
