### ISSUE TITLE
C.SC.1.1 e C.SC.1.2 non trovano data-element

### ISSUE THREAD

**Issue by paolagan** [italia/pa-website-validator#351]
Ciao a tutti, sto usando l'ultima versione della app e mi da problemi nei "criteri di conformità".  Io vedo font corretti e libreria bootstrap 1.6.2. Vedo anche i data-element richiesti dalla guida, per cui non riesco a capire dove possa essere il problema. Se riuscite a darmi una mano vi do il link della scuola ancora in dev: https://dijak.staging-2.codingduck.cloud/it/ 
Please aiuto.

**Comment by tensor5** [comment]
@paolagan, puoi riprovare con v2.6.0? Dovrebbe darti errori più dettagliati

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
