### ISSUE TITLE
R.SC.1.1 - Il recupero della lista di argomenti può fallire per le SPA

### ISSUE THREAD

**Issue by mmartinel** [italia/pa-website-validator#359]
Nel file ControlledVocabularyAudit.ts le seguenti righe dovrebbero caricare la pagina con la lista degli argomenti:
``` typescript 
    await button?.evaluate((b: any) => b.click());
    await page.waitForNavigation();
```
Il problema è che il metodo waitForNavigation() va in timeout per le SPA (https://github.com/puppeteer/puppeteer/issues/1412).

Per risolvere il problema si consiglia di sostituire le righe sopra con:
``` typescript 
    await button?.evaluate((b) => b.click()),
    await page.waitForSelector('[data-element="all-topics"]')
```

**Comment by tensor5** [comment]
Grazie @mmartinel. Potresti gentilmente fare una PR (anche per #355)?

**Comment by tensor5** [comment]
Risolto da #374.
