### ISSUE TITLE
Impossibile rispettare i requisiti del Validator scuole

### ISSUE THREAD

**Issue by gbfactory** [italia/pa-website-validator#360]
Buongiorno,
sto effettuando il controllo di un sito web per una scuola utilizzando la versione 2.6.0 del validator scuole. Nonostante il sito web sia realizzato utilizzando i template HTML disponibili qui su GitHub, mi risulta impossibile passare i controlli sui punti C.SC.1.1 e C.SC.1.2, nonostante il sito web utilizzi chiaramente i font indicati e la versione di Bootstrap Italia sia successiva alla 1.6. Gli stessi template HTML "ufficiali" non superano la verifica con il validator.

Inoltre riscontro incongruenze anche su altri punti, come C.SC.2.1 (Informativa privacy), C.SC.2.2 (dichiarazione di accessibilità), C.SC.2.3 (cookie). Per i primi due punti la pagina è presente ma non rilevata, già controllato data element, per i cookie semplicemente non ce ne sono sul sito.

Il problema sembra essere riscontrato anche da altri utenti (#351), come posso procedere per trovare una soluzione? Grazie!

**Comment by tensor5** [comment]
I link del menù devono essere interni al sito. Per maggiori dettagli mi serve l'url della pagina.

**Comment by gbfactory** [comment]
Buongiorno, grazie per le risposte. I link indicati sono interni al sito, e i data element dovrebbero essere indicati correttamente. Segue immagine del codice: 
![image](https://github.com/italia/pa-website-validator/assets/37420179/f0fee250-f1d7-4463-9037-570e737e84d2)
Uno dei siti web che presenta problemi è https://euganeo.edu.it

**Comment by gbfactory** [comment]
Buongiorno @emafer @tensor5, ci sono aggiornamenti? Mi scuso se scrivo nuovamente, tuttavia stiamo cercando da svariati mesi ormai una soluzione al problema.

**Comment by MarcoTesta-EP** [comment]
Premesso che non ho esperienza diretta con le scuole ma solo con i comuni e non sono un manutentore del progetto, in ogni caso il data-element della privacy guardando il sorgente ha le virgolette curve, non penso vadano bene:

![image](https://github.com/italia/pa-website-validator/assets/20684428/e0083bbe-8e48-4c5d-bceb-b91dc9e42e0d)

**Comment by gbfactory** [comment]
> Premesso che non ho esperienza diretta con le scuole ma solo con i comuni e non sono un manutentore del progetto, in ogni caso il data-element della privacy guardando il sorgente ha le virgolette curve, non penso vadano bene:
> 
> ![image](https://user-images.githubusercontent.com/20684428/266657438-e0083bbe-8e48-4c5d-bceb-b91dc9e42e0d.png)

Buonasera, grazie per il suggerimento. Ho provveduto ora a fare un nuovo test sostituendo le virgolette ma sfortunatamente il problema sembra persistere.

**Comment by tensor5** [comment]
Ciao @gbfactory, prova la nuova versione del validatore, ti dirà quali sono i `data-element` mancanti.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
