### ISSUE TITLE
Coerenza campi Architettura dell'Informazione Modello Comuni

### ISSUE THREAD

**Issue by danielepecoraro** [italia/pa-website-validator#361]
Buongiorno, non so se è stato già segnalata questa cosa:
volevo segnalare delle discrepanze all'interno del documento di Architettura dell'informazione. Precisamente: nel content type **Punto di contatto, Valore punto di contatto**, viene indicato come campo **obbligatorio** ma con cardinalità _0..n_ (quando sarebbe più consono a mio avviso un 1..n data l'obbligatorietà). Ho riscontrato questa incongruenza anche nel content type **Persona pubblica, voce Incarichi, e in Evento, voce Luogo**. Vorrei quindi chiedere, in base a questi elementi, se va corretta la cardinalità o se gli elementi non sono più obbligatori?
Inoltre vorrei chiedere, per il content type **Persona pubblica, voce Altri incarichi**, che tipo di slot è previsto, poichè non è indicato nel documento.
Grazie.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
