### ISSUE TITLE
Le Domande di Follow-Up non sono associate ai valori corretti: C.SI.2.5 - VALUTAZIONE DELL'ESPERIENZA D'USO, CHIAREZZA DELLE PAGINE INFORMATIVE

### ISSUE THREAD

**Issue by dave1508** [italia/pa-website-validator#365]
Utilizzando l'ultima versione dell'app di validazione (2.6.0) otteniamo il seguente messaggio di errore per la misura C.SI.2.5
 
![Follow-up](https://github.com/italia/pa-website-validator/assets/134056045/3278331c-1cb9-4bfb-b088-869261b8b92a)

abbiamo controllato le domande di follow-up e queste vengono restituite correttamente associate alle stelle da 1 a 3 e da 4 a 5.
Sembrerebbe che si sia riproposto lo stesso problema delle issue già chiuse #293 e della issue #274  degli scorsi mesi di maggio e giugno, risolta poi con una nuova versione dell'app di validazione.
Il sito di riferimento è: https://comune.santaelisabetta.ag.it/

Grazie per qualsiasi suggerimento o aggiornamento in merito

**Comment by dave1508** [comment]
Non ci sono novità? Abbiamo testato con la nuova versione dell'app di validazione (2.7.0), ma non ci sono miglioramenti sulla misura C.SI.2.5 otteniamo sempre lo stesso risultato, le domande di Follow-up non sono associate ai valori corretti, potreste confermarci che avete in lavorazione la problematica?

**Comment by tensor5** [comment]
Ciao @dave1508, stiamo verificando.

**Comment by enrimk** [comment]
Vedo che [il check sulla visibilità dei blocchi](https://github.com/italia/pa-website-validator/blob/ea52f704f826370073e7b979b368c1a2053bf716/src/utils/municipality/utils.ts#L559) di risposte avviene immediatamente dopo il click simulato. Fa sempre in tempo il browser ad aggiornare lo stato del dom prima della verifica? Sempre che al click qualcosa avvenga - non so se viene controllato l'esito... e se il js non viene scaricato bene? [^*]

In fondo l'errore esce solo [su questo check](https://github.com/italia/pa-website-validator/blob/ea52f704f826370073e7b979b368c1a2053bf716/src/utils/municipality/utils.ts#L784); dando per scontato che i blocchi esistano (perché se no ci sarebbero altri errori), rimane il punto della visibilità, e l'unico check a riguardo è quello detto.

[^*]: Si spiegherebbe anche l'"erraticità" del problema... Io ad es. non lo riscontro.

**Comment by farapeppe** [comment]
Con la vecchia versione dell'app di valutazione (2.6.0) ottenevo errore sulle pagine di primo livello e nessun problema sulle pagine di secondo livello.
Con la versione 2.7.0 ottengo errore su tutte le pagine, di primo e secondo livello.
Il sito è https://www.web3volution.it/democomuni/

**Comment by tensor5** [comment]
Risolto in #392.

**Comment by dave1508** [comment]
Dobbiamo Attendere il rilascio della nuova versione dell'app di validazione quindi!?

**Comment by tensor5** [comment]
Esatto.
