### ISSUE TITLE
Regress versione 2.7 scuole

### ISSUE THREAD

**Issue by lia55556** [italia/pa-website-validator#378]
Avevo consegnato il lavoro a giugno, ma ancora oggi vedo che rilasciate nuove versioni dell'app, quella di oggi tra l'altro mi è andata in regress sul terzo parametro, ma proprio non capisco l'errore, mi potete dare qualche indicazione?
![regress2](https://github.com/italia/pa-website-validator/assets/125757301/0d244eba-af46-40d4-8769-3c93dd061eef)
![regress1](https://github.com/italia/pa-website-validator/assets/125757301/d7341785-4f11-49aa-9dfb-bda299d3a7ee)

**Comment by rmpaolillo** [comment]
E' chiaramente un "bug".
L'errore, che ho anche io, dice che nella "home" del sito si aspetta di trovare i "data-element" tipici della sezione "servizi"...il che mi sembra impossibile.
A meno che li non abbia troncato, nel suo screenshot, altro testo dove specifica cosa manca nelle varie pagine dei servizi.

**Comment by tensor5** [comment]
Abbiamo bisogno del sito per verificare.

**Comment by rmpaolillo** [comment]
Buongiorno,
issue aperta da un altro utente...
il sito su cui sto lavorando e' il seguente.
https://staging.icfranceschi.edu.it/

Ruggiero Marco Paolillo
================================
IT Freelance Consultant and Web Artisanmobile +39 345.39.40.792
================================ 

    Il lunedì 25 settembre 2023 alle ore 10:51:09 CEST, Nicola Squartini ***@***.***> ha scritto:  
 
 


Abbiamo bisogno del sito per verificare.

**Comment by GiuseppeBronty** [comment]
dà anche a me lo stesso errore su diversi siti web; chiede i data element delle schede informative di servizio nella home page; probabile bug
