### ISSUE TITLE
Modello Comuni: problema nella validazione sezione Servizi dalla versione 2.7

### ISSUE THREAD

**Issue by LucaDuttoTD** [italia/pa-website-validator#380]
Testando un sito con la nuova versione 2.7 dell'app di validazione, riscontriamo un fallimento nella validazione dei Servizi che fino alla versione 2.6 non avevamo.

"Non sono presenti almeno 10 schede servizio o in almeno una delle pagine analizzate più di 2 voci obbligatorie o i relativi contenuti non sono presenti o più di 1 voce non è nell'ordine corretto."

I servizi nel sito sono più di 10, e altri problemi che implichino fallimento non sono riscontrati.

I siti a cui facciamo riferimento sono https://comune.sarconi.potenza.it/ e https://comune.almese.to.it/ 

p.s.: non troviamo, nelle linee guida e documenti correlati, questo vincolo sui 10 servizi pubblicati nel sito, dove si trova?

**Comment by tensor5** [comment]
Ciao @LucaDuttoTD, nei tuoi siti manca `data-element="load-other-cards"` nel bottone "Carica altri risultati". Vedi gli snippet di esempio [qui](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html).

**Comment by LucaDuttoTD** [comment]
> Ciao @LucaDuttoTD, nei tuoi siti manca `data-element="load-other-cards"` nel bottone "Carica altri risultati". Vedi gli snippet di esempio [qui](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html).

Grazie @tensor5 ma anche aggiungendo il data-element da te suggerito l'errore è sempre lo stesso: c'è modo di capire dai log del validatore cos'è precisamente che non gli piace?

**Comment by tensor5** [comment]
Ho provato e su https://comune.sarconi.potenza.it/  il criterio C.SI.1.3 che prima falliva, ora passa.

**Comment by LucaDuttoTD** [comment]
> Ho provato e su https://comune.sarconi.potenza.it/ il criterio C.SI.1.3 che prima falliva, ora passa.

Ho riprovato or ora: con la validazione "veloce" pare che il validatore continui a segnalare il problema, mentre con la scansione "approfondita" non mi ha più dato errore.

**Comment by tensor5** [comment]
È così perché con la validazione veloce valuta solo 3 servizi.
