### ISSUE TITLE
Errore C.SI.1.2 - Almeno 50% di classi di bootstrap italia

### ISSUE THREAD

**Issue by AndrewCortDev** [italia/pa-website-validator#381]
Buongiorno,
dall'ultima versione dell'app (2.7) riscontro un errore mai presentato prima riguardo il C.SI.1.2.
Non viene superato perchè non trova abbastanza classi di bootstrap italia, in media ne ho 48%.
Ho provato a cercare nella documentazione questa regola ma non la trovo. Viene solo specificata la versione minima di bootstrap italia ma non di usare almeno il 50% delle classi.

E' un bug?

**Comment by tensor5** [comment]
Non è un bug, in ogni pagina almeno il 50% delle classi CSS usate deve appartenere a Bootstrap Italia. La documentazione sarà aggiornata a breve.

**Comment by fnori77** [comment]
Salve, ho lo stesso problema. Avete novità?

**Comment by tensor5** [comment]
https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-1-2-libreria-di-elementi-di-interfaccia

**Comment by fnori77** [comment]
Salve, sto usando il template design-comuni-wordpress-theme e non riesco onestamente a trovare un senso a:
*******************
Inoltre, viene verificato che almeno il 50% delle classi CSS uniche trovate nella pagina appartiene all’elenco delle classi CSS di Bootstrap Italia.
*******************
Non dovrebbe essere già così?

**Comment by fnori77** [comment]
Salve, per passare il test ho dovuto eliminare il plugin per l'accessibilità. Scusate ma non sarebbe opportuno alzare la soglia e permettere l'utilizzo del sito alla persone con disabilità? Grazie.
