### ISSUE TITLE
 C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO

### ISSUE THREAD

**Issue by lrosso-leonardoweb** [italia/pa-website-validator#384]
Nonostante abbiamo provveduto a far creare più di 10 schede servizio al Comune in questione, l'esito dell'App di Valutazione presenta la seguente (e unica) difformità:

 _C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO_
**Non sono presenti almeno 10 schede servizio o in almeno una delle pagine analizzate più di 2 voci obbligatorie o i relativi contenuti non sono presenti o più di 1 voce non è nell'ordine corretto.** 

Da tenere presente che sono presenti tutti i data-element, e che le schede servizio sono tutte disposte in modo corretto e in ordine (infatti nella precedente versione dell'App non vi erano difformità).

**Comment by tensor5** [comment]
Ciao @lrosso-leonardoweb, il fallimento si verifica anche nella modalità "Approfondita"?

**Comment by lrosso-leonardoweb** [comment]
Ciao, sì, io ho provato proprio in modalità Approfondita, ho anche rifatto il test per scrupolo ma stesso report

**Comment by tensor5** [comment]
Puoi condividere l'URL (anche privatamente su Slack)?

**Comment by lrosso-leonardoweb** [comment]
Sì certo, a chi posso inviarlo su Slack?

**Comment by tensor5** [comment]
https://developersitalia.slack.com/team/U033P26PSPP

**Comment by Simsimus** [comment]
Buonasera, segnalo lo stesso problema anche per le scuole. 
Tutte le schede presenti sono corrette e con tutti i data-element, ma l'app 2.7.0 (con la 2.6.0 era tutto ok) segnala quanto presente nello screen-shot allegato portando le raccomandazioni al 67% invece del 100%.

![Screen](https://github.com/italia/pa-website-validator/assets/108821309/0c28431e-97f7-4249-a0d9-ef93c4e3b4e0)

**Comment by carlo-prodigys** [comment]
Buongiorno,
stesso problema che riceviamo noi da questa versione.
https://www.comune.cormons.go.it/it/servizi-186353

**Comment by tensor5** [comment]
@Simsimus, il caso segnalato da te è il #378.

**Comment by tensor5** [comment]
@carlo-prodigys, per i siti che usano il paginatore nella pagina "Servizi" è necessario usare il `data-element="pager-link"`, come riportato nella [documentazione dell'app per il modello scuole][1]. A breve l'uso di questo data-element sarà documentato anche per i Comuni.

[1]: https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html

**Comment by Cyberciro** [comment]
> Buonasera, segnalo lo stesso problema anche per le scuole. Tutte le schede presenti sono corrette e con tutti i data-element, ma l'app 2.7.0 (con la 2.6.0 era tutto ok) segnala quanto presente nello screen-shot allegato portando le raccomandazioni al 67% invece del 100%.
> 
> ![Screen](https://user-images.githubusercontent.com/108821309/270403247-0c28431e-97f7-4249-a0d9-ef93c4e3b4e0.jpg)

Confermo stesso problema

**Comment by tensor5** [comment]
@Cyberciro, #378.

**Comment by HshMatera** [comment]
Buongiorno,
anche io ho lo stesso problema. 
Inseriti 12 servizi con tutte le voci obbligatorie e nell'ordine corretto. 
Qualcuno ha risolto il problema? Grazie

**Comment by HshMatera** [comment]
Buongiorno, il problema è dovuto al numero delle card servizi che viene caricato, sarà un bug.
Io per ora ho risolto modificando il file tutti-servizi.php modificando $max_posts e $load_posts in questo modo:

```
$max_posts = isset($_GET['max_posts']) ? $_GET['max_posts'] : 10;
$load_posts = 5;
```
effettuando la verifica non restituisce più l'errore.

**Comment by tensor5** [comment]
Nella nuova [documentazione di Comuni][1] è riportato come si utilizza il `data-element="pager-link"` per i siti che usano la paginazione dei servizi.

[1]: https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
