### ISSUE TITLE
 C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO :Anomalia su verifica del criterio 

### ISSUE THREAD

**Issue by fabbiant** [italia/pa-website-validator#387]
Utilizzata nuova versone 2.7.1 dell'APP- Per i Comuni con un numero di schede di servizio  pari o maggiori a 10  l'esito dell'App di Valutazione presenta la seguente (e unica) difformità:

C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO
Non sono presenti almeno 10 schede servizio o in almeno una delle pagine analizzate più di 2 voci obbligatorie o i relativi contenuti non sono presenti o più di 1 voce non è nell'ordine corretto.

A titolo di esempio si fornisce il seguente link 

https://www.comune.rivedarcano.ud.it/

( sono presenti 14 schede di servizio)

Tutte le condizioni di successo previste dal C.S.I 1.3 sono presenti. Si richiede un chiarimento urgente o il rilascio di una nuova versione con il BUGFIX

**Comment by tensor5** [comment]
Nella [pagina servizi](https://www.comune.rivedarcano.ud.it/servizi/) manca il `data-element="load-other-cards"` nel bottone "Carica altri risultati".
