### ISSUE TITLE
Raccomandazione progettuale "R.SC.3.1 - Velocità e tempi di risposta" 

### ISSUE THREAD

**Issue by m3-develop** [italia/pa-website-validator#388]
Buongiorno,
stiamo cercando di aumentare il punteggio di "Raccomandazione progettuale" (R.SC.3.1 - Velocità e tempi di risposta), utilizziamo il plugin di Wp-Rocket per minimizzare i file Css e Javascript.
Facendo il test abbiamo un punteggio che si aggira sui 70-75, ma alcune cose sul sito non funzionano più, per esempio l'apertura del menù principale in versione mobile e l'apertura di alcune tab che venivano aperte tramite funzioni Javascript.
Escludendo dalla minimizzazione i file con all'interno le funzioni, il menu e le tab tornano a funzionare correttamente, ma il punteggio scende a 45-50.
C'è qualche modo per bilanciare il punteggio e la funzionalità di javascript?
Grazie

**Comment by Petrillo96** [comment]
> Buongiorno, stiamo cercando di aumentare il punteggio di "Raccomandazione progettuale" (R.SC.3.1 - Velocità e tempi di risposta), utilizziamo il plugin di Wp-Rocket per minimizzare i file Css e Javascript. Facendo il test abbiamo un punteggio che si aggira sui 70-75, ma alcune cose sul sito non funzionano più, per esempio l'apertura del menù principale in versione mobile e l'apertura di alcune tab che venivano aperte tramite funzioni Javascript. Escludendo dalla minimizzazione i file con all'interno le funzioni, il menu e le tab tornano a funzionare correttamente, ma il punteggio scende a 45-50. C'è qualche modo per bilanciare il punteggio e la funzionalità di javascript? Grazie

Ciao, io sto provando NitroPack versione gratuita, ma lascia un badge nel footer del sito che credo non vada bene. Hai trovato qualche soluzione nel frattempo?

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
