### ISSUE TITLE
Criterio C.SI.2.1 - Prenotazione appuntamenti

### ISSUE THREAD

**Issue by AndrewCortDev** [italia/pa-website-validator#394]
Con la versione dell'app 2.7.2 viene rilevato un problema sul criterio Criterio "C.SI.2.1 - Prenotazione appuntamenti".
Mi segnala che non è presente il pulsante delle prenotazioni ma contemporaneamente nella lista della pagina che trova sia nella colonna "Componente individuato" sia nella colonna " "Nella sezione "Accedi al servizio" della scheda servizio è presente il pulsante di prenotazione appuntamento" " scrive "SI". Ho ricontrollato il codice e sono presenti in tutte le parti che lo richiedono i data-attribute corretti.

Anche se l'app mi trova il pulsante e mi scrive SI in tutte le pagine lo segnala come un criterio non superato e non capisco dove sia l'errore.
E' un bug?

**Comment by tensor5** [comment]
@AndrewCortDev, puoi inviarmi l'url (anche in privato su [Slack](https://developersitalia.slack.com/team/U033P26PSPP)).

**Comment by AndrewCortDev** [comment]
Non posso entrare in Slack in quanto non ho un account nella vostra area di lavoro.
Posso inviarle un messaggio privato in un altro modo? Grazie

**Comment by AndrewCortDev** [comment]
Questo è un esempio del problema.. il sito ha 14 schede servizio, vengono tutte rilevate correttamente. All'interno di ogni pagina, da come si vede anche nell'immagine viene rilevato sia il componente sia pulsante. In tutte le pagine servizio ho SI da entrambe le parti ma l'applicazione lo segnala come errore. Ho ricontrollato tutto i data-elements richiesti e sono tutti presenti. Questo errore non era presente nelle versioni precedenti dell'app.

![Screenshot 2023-10-10 alle 16 53 03](https://github.com/italia/pa-website-validator/assets/92526685/59965258-5622-489a-99c8-f454aa05fcf8)

**Comment by tensor5** [comment]
@AndrewCortDev, puoi riprovare il test con l'ultima release?

**Comment by AndrewCortDev** [comment]
Buonasera, ora funziona correttamente e il criterio viene superato. 
Grazie

**Comment by tensor5** [comment]
Fissato in ef3b73e.
