### ISSUE TITLE
C.SI.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA -

### ISSUE THREAD

**Issue by 95AlessiaC95** [italia/pa-website-validator#395]
Buongiorno,

eseguendo il test su un sito comunale (fatto con wordpress), questo criterio va in errore in quanto risulta che meno del 50% delle classi CSS usate appartiene alle classi CSS di Bootstrap Italia. Disattivando il plugin per la gestione dei cookie (complianz), l'errore sparisce.

Come si può procedere per evitare questo problema? C'è un plugin per i cookie consigliato che si può mettere? Oppure é possibile alzare la soglia di tolleranza?

Grazie
Alessia

**Comment by mariantanase** [comment]
Essattamente lo stesso problema l'ho riscontrato anch'io. E sempre con lo stesso plugin Complianz per cookie. 
In effetti , disabilitando quel plugin, il test passa.
Peccato che era interessante quel plugin.
A questo punto sarebbe meglio che qualcuno dei sviluppatori del tema ci può fornire una soluzione o una alternativa per l'argomento cookie.

Seguo...
