### ISSUE TITLE
Errori in caso manchi il link alla pagina prenotazione appuntamenti

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#397]
Buongiorno,

nel caso in cui il data-element "appointment-booking" manchi o il link con il metadato corretto ci sia con l'href vuoto vengono riportati diversi errori:

C.SI.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA - Il sito comunale deve utilizzare la libreria Bootstrap Italia.
C.SI.2.1 - PRENOTAZIONE APPUNTAMENTI - Il sito comunale deve consentire di prenotare un appuntamento presso lo sportello di competenza.
C.SI.3.1 - COOKIE - Il sito comunale deve presentare cookie tecnici in linea con la normativa vigente.
C.SI.5.2 - DOMINIO ISTITUZIONALE - Il sito comunale utilizza un dominio istituzionale secondo le modalità indicate nella documentazione del modello di sito comunale.

Il C.SI.2.1 è corretto ma gli altri 3 sono solo fuorvianti e non giustificati considerando che non falliscono più se si sistema il link agli appuntamenti.
Grazie.

**Comment by tensor5** [comment]
Ciao @MarcoTesta-EP , è così perché quei criteri devono essere verificati anche nella pagina di prenotazione appuntamento. Per ogni criterio viene controllato che tutte le pagine in cui esso deve essere verificato esistano e siano raggiungibili (data-element e href valido); se questo controllo fallisce l'app lo [segnala][1] riportando la lista dei data element mancanti e non procede oltre con la verifica del criterio.

[1]: https://github.com/italia/pa-website-validator/blob/72cca611bd58cae2307014c1379f286ee1dd5fc3/src/config/commonAuditsParts.ts#L156

**Comment by MarcoTesta-EP** [comment]
Ciao, capito grazie.
