### ISSUE TITLE
C.SI.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA - ERRORE RICERCA CLASSI UNICHE

### ISSUE THREAD

**Issue by WEMAPP** [italia/pa-website-validator#400]
Buongiorno
facendo un debug su bootstrapItaliaDoubleCheckAudit sembra che il controllo effettuato non sia corretto. 
Se abbiamo capito bene la validazione deve controllare che almeno il 50% dellle classi uniche trovate appartenga alla libreria bootstrap.
A noi sembra, facendo debugging, che il codice non prenda le classi uniche ma tutte anche se duplicate (non troviamo nel codice un groupby per esempio).

 const foundClasses = await page.evaluate(async () => {
          const used = new Set<string>();
          const elements = document.getElementsByTagName("*");
          for (const element of elements) {
            const elementClasses = element.getAttribute("class") ?? "";
            for (const cssClass of elementClasses.split(" ")) {
              if (cssClass) {
                used.add(cssClass);
              }
            }
          }
          return [...used];
        });

Cordiali Saluti

**Comment by tensor5** [comment]
Buongiorno @WEMAPP, la stuttura dati [Set][1], usata [qui][2], si fa carico della deduplicazione delle classi. Ti chiedo di verificare facendo due scansioni, una con molte classi non BI duplicate e una rimuovendo a mano i duplicati, se le percentuali differiscono, nel qual caso sarebbe un bug.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
[2]: https://github.com/italia/pa-website-validator/blob/72cca611bd58cae2307014c1379f286ee1dd5fc3/src/audits/municipality/bootstrapItaliaDoubleCheckAudit.ts#L231

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
