### ISSUE TITLE
Righe valorizzate con "undefined undefined"

### ISSUE THREAD

**Issue by gvalter** [italia/pa-website-validator#402]
Buongiorno,
eseguendo il test su di un sito comunale (fatto in joomla 4) ottengo un certo numero di righe valorizzate con "undefined undefined". 
tali righe risultano posizionate dopo:
LH:status Auditing: C.SI.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - Il sito comunale deve utilizzare i font indicati dalla documentazione del modello di sito comunale.
e prima di:
LH:status Auditing: C.SI.3.1 - COOKIE - Il sito comunale deve presentare cookie tecnici in linea con la normativa vigente.
Sembrerebbe inoltre che i test vengano ripetuti almeno 2 volte.

Alla fine del processo ottengo comunque dei risultati acccettabili senza alcun riferimento agli undefined riscontrati durante il test.
Come posso procedere per evitare questo problema?  
Grazie, Valter

**Comment by corrado1975** [comment]
Confermo la problematica anche sulla versione 2.7.4

**Comment by farapeppe** [comment]
Confermo anche su 2.7.6

**Comment by lightuono** [comment]
Confermo anche sulla 2.8.0 per le scuole

**Comment by d79** [comment]
Confermo anche su 2.8.3 per scuole, su Windows (10 e 11), Mac OS e Linux, durante gli auditing:
- C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT
- C.SC.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA

L'app di validazione restituisce 100 sia nei criteri di conformità che nelle raccomandazioni progettuali (nessun problema rilevato), ma l'asseveratore riscontra delle difformità (non rilevate dall'app di validazione).

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
