### ISSUE TITLE
La finestra cmd in cui gira la procedura prende il focus

### ISSUE THREAD

**Issue by luigibugliani** [italia/pa-website-validator#403]
Nella versione WIndows, per le Scuole, la procedura ogniqualvolta esegue il test e scrive una riga dell'operazione che fa in quel momento, prende il focus del sistema e di fatto non permette di utilizzare il computer su cui gira il test,per fare altre cose nel frattempo.
La cosa è molto fastidiosa.
Nelle prime versioni questo non accedeva.

**Comment by Cam-al** [comment]
Pure io riscontro lo stesso problema, questo succede solo dalle ultime versioni

**Comment by Cam-al** [comment]
Nessuna soluzione? Così diventa impossibile usare il computer mentre gira il validatore, prima non faceva così.

**Comment by mrnooz** [comment]
a febbraio 2024 ancora succede e continua ad essere fastidioso

**Comment by MarcoTesta-EP** [comment]
Concordo...

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
