### ISSUE TITLE
Regress versione 2.7.4

### ISSUE THREAD

**Issue by lia55556** [italia/pa-website-validator#410]
Buonasera, segnalo l'ennesimo regress dell'ultima versione per il modello scuole: va in errore sul controllo della libreria bootstrap a quanto ho capito. Il mio sito è 

https://www.iisspietrosette.edu.it/

e fino alla versione 2.7.3 era tutto ok

**Comment by MarcoTesta-EP** [comment]
Segnalo lo stesso errore anche sui comuni a quanto sembra: C.SI.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA.
Con la 2.7.3 nessun problema.

**Comment by corrado1975** [comment]
Segnalo anch'io problema libreria bootstrap su sito scuole e sempre **C.SC.1.3 - UTILIZZO DI TEMI PER CMS** anche se il tema è quello indicato

![Lighthouse-Report](https://github.com/italia/pa-website-validator/assets/140151788/b5e1d09a-46a0-4fdb-b12c-c27fcfbe6692)

**Comment by lrosso-leonardoweb** [comment]
Segnalo anch'io lo stesso problema per quanto riguarda i Comuni. Sottolineo che nella versione precedente non dava problemi. Buon lavoro!

**Comment by Simsimus** [comment]
Segnalo anche io lo stesso problema sopra riportato...

**Comment by mattiadevigus** [comment]
Stesso problema capitato anche a me

**Comment by LucaDuttoTD** [comment]
+1, stesso problema

**Comment by tensor5** [comment]
Provare la [v2.7.5](https://github.com/italia/pa-website-validator/releases/tag/v2.7.5), grazie.

**Comment by techdesignadmin** [comment]
> Provare la [v2.7.5](https://github.com/italia/pa-website-validator/releases/tag/v2.7.5), grazie.

Con la nuova versione il problema è rientrato, grazie
