### ISSUE TITLE
URGENTE NON LEGGE LIBRERIA BOOTSTRAP

### ISSUE THREAD

**Issue by pilcom2023** [italia/pa-website-validator#411]
Come da oggetto si segnala che con la 2.7.4 la libreria bootstrap per i siti scuole non viene letta. Attendiamo un urgente riscontro onde evitare che le asseverazioni vengano respinte per cause non imputabili agli sviluppatori ma a degli errori introdotti con la versione di cui sopra.

**Comment by tensor5** [comment]
La [v2.7.5](https://github.com/italia/pa-website-validator/releases/tag/v2.7.5) dovrebbe risolvere questo problema.
