### ISSUE TITLE
C.SC.1.3 - UTILIZZO DI TEMI PER CMS SCUOLE - ANOMALIA

### ISSUE THREAD

**Issue by loky62** [italia/pa-website-validator#414]
Versione 2.7.5: errore il sito non utilizza il tema cms del modello invece il sito utilizza il tema corretto, senza modifiche. 

L'errore è segnalato sia sulla versione del tema 2.5.1 che sulla versione 2.6.

Potete risolvere?

Grazie.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
