### ISSUE TITLE
Anomalia su versione app 2.7.5

### ISSUE THREAD

**Issue by corrado1975** [italia/pa-website-validator#415]
Salve, sto riscontrando un'anomalia sull'ultima versione dell'app, quando lancio la scansione vengo visualizzate molte righe con la scritta **undefined undefined** è normale?

![errore1](https://github.com/italia/pa-website-validator/assets/140151788/63e0716f-bd69-4973-b33d-5e6a410a7890)

![errore2](https://github.com/italia/pa-website-validator/assets/140151788/7c07cb60-e5f9-4f4e-a0f8-56a4f8351d2d)

**Comment by lightuono** [comment]
Confermata anche sulla 2.8.0

**Comment by peppeinutile** [comment]
Salve, confermo stessa problematica su versione 2.8.2 versione scuole.
Wordpress è aggiornato, il tema anche. Ci sono solo plugin di cache e non di defer/async per css/js.

È un problema del tema per wordpress o del tool?

Vedendo la pull request https://github.com/italia/pa-website-validator/pull/446, ci sarebbe questa soluzione, perchè non viene aggiunta?

Qualcuno ha risolto diversamente?

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
