### ISSUE TITLE
Errore "R.SC.1.2 - SCHEDE INFORMATIVE DI SERVIZIO" per servizi privati / limitati a determinate utenze (Wordpress - Tema Scuole)

### ISSUE THREAD

**Issue by MaxiStarling56** [italia/pa-website-validator#423]
Salve, vorrei chiedere se fosse possibile ovviare al problema indicato nel titolo.
Attualmente alcune delle pagine presenti nel sito scolastico sono limitate alla sola visualizzazione da parte di alcune tipologie di utenze (vedi esempio in immagine).
Sarebbe possibile indicare al validatore tale informazione? Magari tramite una tag della pagina o tramite una lettura dello specifico messaggio in immagine?

![Configurazione del servizio](https://github.com/italia/pa-website-validator/assets/35599704/b2e48524-2bdd-4ee6-8631-c040dff98574)
_Configurazione del servizio_

![Servizio visualizzato in incognito](https://github.com/italia/pa-website-validator/assets/35599704/2d87035d-35f4-4bc8-972a-fcd2209f0bf2)
_Servizio visualizzato in incognito_

Grazie per l'attenzione, buon proseguimento.

**Comment by MaxiStarling56** [comment]
Un'altro questito che vorrei porre è se la verifica fatta lato istituzionale passerebbe con un voto 50 sulla categoria "Raccomandazioni Progettuali", grazie.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
