### ISSUE TITLE
Anomalie riscontrate app 

### ISSUE THREAD

**Issue by SaraMataloni** [italia/pa-website-validator#424]
Salve, sto riscontrando delle anomalie relativamente ad alcuni controlli, di cui allego screen.
Siamo ancora in una fase di sviluppo quindi il sito del comune è ancora su di un server non pubblico.

![image](https://github.com/italia/pa-website-validator/assets/132647506/3d57c57a-89b5-419f-bad6-3ee33041fd49)
Riguardo al tema abbiamo l'ultima versione del tema Comuni ed abbiamo creato un child.

![image](https://github.com/italia/pa-website-validator/assets/132647506/31b84729-494c-4cd8-82e5-f9b0c1abf0db)
![image](https://github.com/italia/pa-website-validator/assets/132647506/9aaf5475-bace-4246-8d5c-3fa3831760ef)

Riguardo agli altri controlli, mi viene indicato come errore che le pagine sono inesistenti, mentre sono perfettamente create, linkate e funzionanti, oppure "segnalazione disservizio" la pagina c'è e viene utilizzato il servizio dedicato.

**Comment by tensor5** [comment]
Ciao @SaraMataloni, se hai un server di sviluppo puoi passarmi il link su [Slack](https://slack.developers.italia.it/).

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
