### ISSUE TITLE
R.SC.1.2 - SCHEDE INFORMATIVE DI SERVIZIO - Errore | Maximum call stack size exceeded

### ISSUE THREAD

**Issue by emanueleempix** [italia/pa-website-validator#428]
Sto riscontrando un problema sulla sezione **Raccomandazioni progettuali**. Nel risultato della validazione sulla voce **R.SC.1.2 - SCHEDE INFORMATIVE DI SERVIZIO** ho come output: "**Errore**". Come posso risolvere? Cercando nel json la stringa riguardante questa voce riporta:
`"school-servizi-structure-match-model": {
      "id": "school-servizi-structure-match-model",
      "title": "R.SC.1.2 - SCHEDE INFORMATIVE DI SERVIZIO ............",
      "description": "CONDIZIONI DI SUCCESSO: .............",
      "score": null,
      "scoreDisplayMode": "error",
      "errorMessage": "Maximum call stack size exceeded"
    },` 

il problema dovrebbe essere questo: **"errorMessage": "Maximum call stack size exceeded"**.

Ho caricato il risultato della valutazione qui: https://www.ipsiafermo.edu.it/pa-validator/report-www.ipsiafermo.edu.it-20231116T102328Z.html

![r_sc_1_2](https://github.com/italia/pa-website-validator/assets/115455366/b3364e30-ed61-48ef-8042-c39d9a3401fe)

Il sito www.ipsiafermo.edu.it è stato pubblicato con tema [design-scuole-wordpress-theme](https://github.com/italia/design-scuole-wordpress-theme) versione 2.0.3 e aggiornato manualmente all'ultima versione 2.6.0.

Qualcuno può aiutarmi a capire come risolvere?

**Comment by makakrap** [comment]
ho lo stesso identico problema
