### ISSUE TITLE
Validatore web non scansiona le pagine

### ISSUE THREAD

**Issue by corrado1975** [italia/pa-website-validator#429]
Salve stiamo asseverando due siti web per due istituti scolastici (https://www.isisstaddeodasessa.edu.it - https://www.convittonifo.edu.it/) entrambi i siti hanno gli stessi plugin e le stesse configurazioni sono praticamente uguali, sul primo però viene scansionato dal validatore in tutte le pagine ed ottengo il valore di 100 sui criteri di conformità mentre per il secondo vengono scansionate solo tre pagine ed ottengo il valore di 66 con errori su i seguenti criteri:
C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - Il sito della scuola deve utilizzare i font indicati dalla documentazione del modello di sito della scuola.
C.SC.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA - Il sito della scuola deve utilizzare la libreria Bootstrap Italia in una versione più recente di 1.6.
C.SC.2.3 - COOKIE - Il sito della scuola deve presentare cookie tecnici in linea con la normativa vigente.

La cosa strana è che su quest'ultimo l'ultima volta che l'avevo scansionato avevo avuto 100 come l'altro, adesso però non ne vuole sapere di scansionare tutte le pagine del sito. Qualcuno ha avuto lo stesso problema? Allego log delle due scansioni
![StatOk](https://github.com/italia/pa-website-validator/assets/140151788/3c2b1f2b-8ecc-4e0e-b90d-23df906d5d2e)
![Stat](https://github.com/italia/pa-website-validator/assets/140151788/f3954197-6fc7-4bc6-bb8d-96385c6f7b36)
Come potete vedere sul primo sito vengono scansionate tutte le pagine più volte sul secondo no.

Questi i risultati
Primo sito
![Lighthouse-Report_OK](https://github.com/italia/pa-website-validator/assets/140151788/0ff00509-7df3-4c53-9494-55b1f5c22384)

Secondo sito
![Lighthouse-Report_KO](https://github.com/italia/pa-website-validator/assets/140151788/85c7fd41-2f17-4d23-b804-cbea9f4966eb)

Spero che qualcuno possa darmi una mano a risolvere, perchè sto da due giorni e non riesco a capire quale può essere il problema.

**Comment by tensor5** [comment]
Ciao @corrado1975, prova a mettere "Panoramica" con `data-element="overview"` anche nel menù di "Didattica".

**Comment by corrado1975** [comment]
Ciao tensor5, grazie grazie grazie di vero cuore, era proprio quello il problema ho inserito la voce panoramica ed ecco il risultato:

![Lighthouse-Report (1)](https://github.com/italia/pa-website-validator/assets/140151788/e1db5487-37bf-4699-8422-5fa8ac2eb02b)

La cosa strana è com'è scomparsa la voce di menu visto che nella gestione dei menu del wordpress non c'è?
Per ripristinarla ho dovuto inserire il record all'interno della tabella wp_postmeta andando ad indicare il template didattica.
Questo è veramente un mistero.

Grazie ancora.
