### ISSUE TITLE
test interrotto

### ISSUE THREAD

**Issue by assistenzatecnica94** [italia/pa-website-validator#431]
Buongiorno, con questa nuova versione tutti i test di  tutti i siti vengono interrotti con tre tentativi goto.
Come mai? 
Anche su siti già fiunanziati pure

**Comment by tensor5** [comment]
Questo avviene quando il sito, o una pagina, non è raggiungibile.

**Comment by assistenzatecnica94** [comment]
Purtroppo su tutti i siti. Da cosa è dipeso? Anche i siti già controllati e finanziati

**Comment by assistenzatecnica94** [comment]
> Questo avviene quando il sito, o una pagina, non è raggiungibile.

Come possiamo risolvere. Su tutti i siti fa questo

**Comment by eb-ai4** [comment]
Il problema si verifica **sistematicamente** alla validazione dei font su tutti i siti comunali perfettamente funzionanti e veloci nel caricamento. Il problema si verifica su windows. Su mac non va in timeout. 
Questo va sistemato al più presto. 

`LH: status Auditing: C.SI.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - Il sito comunale deve utilizzare i font indicati dalla documentazione del modello di sito
comunale. +254ms
https://www.comune.xxxxxxxxxxxxxxx/carta-dei-servizi/ 200
https://www.comune.xxxxxxxxxxxxxxx/amministrazione/politici/ goto tentative: 0
https://www.comune.xxxxxxxxxxxxxxx/amministrazione/politici/ goto tentative: 1
https://www.comune.xxxxxxxxxxxxxxx/amministrazione/politici/ goto tentative: 2
ERROR https://www.comune.xxxxxxxxxxxxxxx/amministrazione/politici/: TimeoutError: Navigation timeout of
30000 ms exceeded
LH:municipality-ux-ui-consistency-fonts-check: warn Caught exception: Il test è stato interrotto perché nella prima pagina analizzata https://www.comune.xxxxxxxxxxxxxxx/amministrazione/politici/ si è verificato l'errore
"TimeoutError: Navigation timeout of 30000 ms exceeded"
Verificarne la causa e rifare il test. +2m`

**Comment by srizzati** [comment]
Buongiorno, confermo di aver riscontrato la stessa problematica su più siti in ambiente di produzione. 

Aprendo le pagine con Chrome si aprono rapidamente, ma avviando la validazione restituisce sempre errore di timeout nel raggiungimento della pagina /amministrazione/politici/ (prima pagina analizzata). 

Confermo anche che il problema si verifica solamente su Windows, mentre con il validatore per MAC non siamo mai riusciti a riprodurlo.

**Comment by fabioneri-modena** [comment]
Buongiorno, confermo di aver riscontrato la stessa problematica su più siti in ambiente di produzione.

Aprendo le pagine con Chrome si aprono rapidamente, ma avviando la validazione restituisce sempre errore di timeout nel raggiungimento della pagina /amministrazione/politici/ (prima pagina analizzata).

Confermo anche che il problema si verifica solamente su Windows, mentre con il validatore per MAC non siamo mai riusciti a riprodurlo.

**Comment by tensor5** [comment]
Problema risolto in conversazione privata.
