### ISSUE TITLE
C.SI.3.2 - DICHIARAZIONE DI ACCESSIBILITÀ - Criterio OK con link errato

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#437]
Buongiorno,
ho un comune che ha effettuato la dichiarazione di accessibilità ma con l'url del comune errato (ha omesso la provincia nell'url), nonostante ciò il test è passato - versione del vaidatore 2.8.0

**Comment by tensor5** [comment]
È possibile avere il link al sito, anche in privato?

**Comment by MarcoTesta-EP** [comment]
Il comune ha sistemato il problema perchè doveva andare in asseverazione... risegnalo in caso ricapiti grazie
