### ISSUE TITLE
I link non possono essere sottoposti a scansione

### ISSUE THREAD

**Issue by Plinio2000** [italia/pa-website-validator#438]
Segnala errore nei link agli indirizzi di studio, ma li genera direttamente il Template Wordpress. Quindi non posso intervenire. Come si può risolvere?
Grazie
![Errori](https://github.com/italia/pa-website-validator/assets/131682507/a0cc5634-b8e4-4e5b-be8f-15751c31b3ee)

**Comment by tensor5** [comment]
Qual è il criterio che va in fallimento o restituisce esito negativo?

**Comment by Plinio2000** [comment]
Scusami ma non capisco cosa mi chiedi, comunque l'errore lo evidenzia l'app per il controllo. Come puoi vedere dalla foto avvisa che l'attributo href è sbagliato. Ma i link che segnala errati li genera direttamente il Template di Wordpress versione. 2.8.1. Quindi come posso sistemare l'errore?
Grazie

**Comment by tensor5** [comment]
Puoi mandarmi l'url? (https://developersitalia.slack.com/team/U033P26PSPP)

**Comment by tensor5** [comment]
L'errore si riferisce al fatto che alcuni tag `<a>` non ha come `href` un link navigabile. Comunque quell'errore fa parte della sezione "Test aggiuntivi", non rientra nei criteri nella misura 1.4.1.

**Comment by Plinio2000** [comment]
Ma io posso sistemarli?

**Comment by tensor5** [comment]
Immagino di sì, ma non conosco Wordpress quindi non saprei dirti come.
