### ISSUE TITLE
App dà errori solo in alcuni casi

### ISSUE THREAD

**Issue by farapeppe** [italia/pa-website-validator#439]
Salve, il validatore ci ha respinto asseverazione di https://www.14comprensivosr.edu.it/
Motivazione: Non rispettato il criterio C.SC.2.3 COOKIE (Il sito deve avere cookie tecnici in linea con la normativa)

Ho lanciato l'app da 3 computer diversi:

1. PC Windows (App 2.8.0 e App 2.8.1) -> Tutto Ok -> 93 94 100 93
2. Mac (App 2.8.1) -> Tutto Ok -> 93 94 100 93
3. Altro PC Windows (App 2.8.1) -> ERRORE! 93 ? 100 93
Dà errore su C.SC.2.3 COOKIE. Guardando il terminale restituisce un "Execution context was destroyed, most likely because of a navigation".

Può essere questo il motivo della mancata asseverazione?
Perché al momento io lo rimetterei in asseverazione esattamente così com'è

**Comment by AlessioPellegrini** [comment]
L'errore citato a quanto pare non dipende dal sito, ma dall'app di valutazione. Anche sul sito che sto facendo spesso appare quell'errore ed i risultati dei test di conformità diventano inaffidabili.

Vedi:  [https://github.com/italia/pa-website-validator/issues/432](https://github.com/italia/pa-website-validator/issues/432)

**Comment by AlessioPellegrini** [comment]
Vedo che usi litespeed, puoi provare a disabilitare il Guest Mode? Ho notato che disabilitandolo l'app non da più l'errore:

Execution context was destroyed, most likely because of a navigation".

**Comment by tensor5** [comment]
Chiudo in favore di #432.
