### ISSUE TITLE
 LH:method <= browser ERR:error DOM.pushNodeByPathToFrontend

### ISSUE THREAD

**Issue by eb-ai4** [italia/pa-website-validator#443]
Cosa significa questo errore? 

 LH:method <= browser ERR:error DOM.pushNodeByPathToFrontend

**Comment by Pitsoftsas** [comment]
> LH:method <= browser ERR:error DOM.pushNodeByPathToFrontend

nessuno ha risposto?

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
