### ISSUE TITLE
C.SI.5.2 - DOMINIO ISTITUZIONALE - dominio non valido 

### ISSUE THREAD

**Issue by Opencontent** [italia/pa-website-validator#454]
Buongiorno
il dominio **romeno.tn.it** non viene considerato come dominio valido riservato

<img width="812" alt="immagine" src="https://github.com/italia/pa-website-validator/assets/972033/d487e8ab-1f8b-47d1-8328-e65a4b9b4376">

(il codice istat del comune è 022155)

**Comment by tensor5** [comment]
Aggiunto in #455.
