### ISSUE TITLE
Voci del submenu "Scuola" riconosciute come di primo livello

### ISSUE THREAD

**Issue by renatadurighello** [italia/pa-website-validator#459]
La validazione del sito mostra un comportamento anomalo nei Criteri di conformità. Infatti nel submenù "scuola" tutte le voci dopo la prima, vengono intese come voci di primo livello e vanno quindi ad abbassare il punteggio.
Ho fatto varie prove:
- con downgrade del tema a precedente versione le voci vengono interpretate correttamente.
- Se lascio nel menù una sola voce, qualunque essa sia, il punteggio sale a 100 in quanto le voci di primo livello vengono individuate correttamente e nessun errore viene rilevato nelle voci di secondo livello.
(https://liceodalpiaz.edu.it/)
N.B. Ho aperto simile issue anche nel repository del tema, nel caso il problema sia legato alla versione (design-scuole 2.9.0)
![image](https://github.com/italia/pa-website-validator/assets/9787217/d9300597-d868-465a-b139-2d4306648388)
![image](https://github.com/italia/pa-website-validator/assets/9787217/e084fd11-09b2-44ef-9dbe-937e67755add)

**Comment by tensor5** [comment]
Nel menù mobile del sito indicato le voci di secondo livello appaiono direttamente sotto l'`<ul>` con `data-element="menu"` (vedi screenshot) per cui la valutazione dell'app è corretta.

![Screenshot from 2024-02-28 12-07-25](https://github.com/italia/pa-website-validator/assets/1545895/48ba3214-f5cb-4aef-90b0-6f6d0f483311)

**Comment by renatadurighello** [comment]
@tensor5 grazie per la risposta. 
Nella mia console questo non appare (vedi screen) e nemmeno nella visualizzazione via telefono. Sulla scia della tua segnalazione però ho controllato in vari dispositivi/browser (es. iPad/Safari) e alcuni vedono in effetti il menù scuola come composto di voci di primo livello. 
Da quel che ho capito quindi il problema risiede comunque nel tema, o a un malfunzionamento nella mia installazione. 
Grazie
![ispezione-mobile](https://github.com/italia/pa-website-validator/assets/9787217/826639d9-3cf8-4c6c-95c4-0bd8b6d649ee)

**Comment by renatadurighello** [comment]
Ho trovato il problema: era il plugin Ginger - EU Cookie Law
