### ISSUE TITLE
Anomalia Versione 2.8.2 - Controllo Note Legali - C.SI.3.4 - Licenza e attribuzione

### ISSUE THREAD

**Issue by doximo** [italia/pa-website-validator#462]
Sono col la presente a segnalare un'anomalia che non mi fa passare il controllo relativo alla pagina di Note Legali ( C.SI.3.4 - Licenza e attribuzione )

Vedo di spiegarmi di seguito ...

Vostro file: "src/storage/common/legalNotes.ts"
Il testo su cui viene fatta la verifica ed indicato nel sucitato file presenta, nel body, uno spazio alla fine "... senza apporre restrizioni aggiuntive. "

Vostro file: "src/audits/municipality/licenseAndAttributionAudit.ts"
In riga 117 >122 andate a verificare la presenza ed il contenuto degli elementi identificati come "legal-notes-body"
Tale verifica ed identifica tali elementi andandone a trimmare il contenuto:
$(bodyElement)?.text().trim().toLowerCase().replaceAll(/\s+/g, " ")

In riga 123 andate a verificare poi l'uguaglianza di tale testo trimmato con il testo presente nel file legalNotes.ts senza però trimmarlo:
if (textBody === legalNotes.body.text.toLowerCase())  ....

Altra piccola cosa, nella prima parte del vostro testo, secondo vostro file legalNotes.ts, è indicato ".. dell’articolo .." con l'utilizzo dell'entity html al posto del semplice apostrofo che nella maggior parte degli editor wysiwyg web viene tradotto in "... dell&rsquo;articolo ..." , non sarebbe meglio utilizzare un singolo apice che non viene tradotto dagli editor di testo ?

Stante così le cose, mi sembra difficile che il controllo possa mai aver successo, infatti il software restituisce errore come "titolo della sezione non corretto" e "dicitura non corretta"

Questo il testo presente nella mia versione di pagina di Note Legali
<h3 data-element="legal-notes-section">Licenza dei contenuti</h3>
<p data-element="legal-notes-body">In applicazione del principio open by default ai sensi dell&rsquo;articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con licenza CC-BY 4.0. Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.</p>

Nell'attesa di leggere vostre in merito con possibili soluzioni

Flavio Dore

**Comment by rosario-pellecchia** [comment]
Ciao . H o problema simile. Alla fine come risolto ?

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
