### ISSUE TITLE
app scuole 2.8.2 crash - windows 11

### ISSUE THREAD

**Issue by AlessioPellegrini** [italia/pa-website-validator#463]
Buon giorno, ultimamente l'app per le scuole, versione 2.8.2. non parte. Si apre una finestra, simile a windows power shell, e poi si richiude senza messaggi di errore. La solita versione per linux funziona senza problemi.

Mi aiutate a risolvere?  Forse devo cancellare la cache da qualche parte?

Grazie

**Comment by MarcoTesta-EP** [comment]
Prova con questa: https://github.com/italia/pa-website-validator/issues/158

**Comment by AlessioPellegrini** [comment]
Funziona, grazie.

Giusto per la cronaca, se non trovate la vostra cartella AppData premete Windows key + R ed inserite %AppData% ,

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
