### ISSUE TITLE
App Valutazione 2.8.4 - Errore note legali

### ISSUE THREAD

**Issue by TlC123789** [italia/pa-website-validator#476]
Salve non capisco perchè ma nell'ultimo rilascio del validatore, mi stia generando un errore nelle note legali che precedentemente non mi dava.
Nel footer è correttamente presente il data-element corretto e nella pagina di note legali sono presenti tutt'ora i due data-element per la licenza dei contenuti e pe il testo interessato. A cosa è dovuto questo errore che prima non appariva?

**Comment by tensor5** [comment]
Risolto in [v2.8.5](https://github.com/italia/pa-website-validator/releases/tag/v2.8.5).
