### ISSUE TITLE
Passaggio di "Lighthouse Scoring Calculator" all'ultima versione v10

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#479]
Buongiorno, 
il "Lighthouse Scoring Calculator" utilizzato per l'indice di velocità è alla versione v8, è previsto un aggiornamento all'ultima versione v10? Nell'ultima versione sono cambiati alcuni criteri di velocità e il punteggio finale è di solito più elevato rispetto alle versioni precedenti...
Grazie.

**Comment by tensor5** [comment]
Sarebbe sicuramente utile aggiornare Lighthouse, ma è piuttosto laborioso e al momento non è previsto.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
