### ISSUE TITLE
L'app entra in un loop infinito quando è presente paginatore XHR in home page

### ISSUE THREAD

**Issue by arturu** [italia/pa-website-validator#480]
Se nella home page è presente almeno un paginatore asincrono l'app di valutazione entra in un loop infinito. Rimuovendo tutti i paginatori l'app non si blocca. 

In tutte le pagine diverse dalla home, usando lo stesso identico componente, l'app riesce a muoversi tra i paginatori.

L'app che ho usato: `scuole-2.8.5-Linux-x64`

Il cms usato è [Ouitoulía](https://github.com/ouitoulia) (Drupal 10 che implementa la v2.4.1 delle pagine statiche), un'installazione di test si trova qua: https://scuola.cmsdrupal.it 

Rif. ouitoulia/diagraphe#10

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
