### ISSUE TITLE
Tool di validazione fallisce quando ci sono molti servizi

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#482]
Il tool di validazione spesso fallisce quando ci sono molti servizi nel comune (più di 100) dando spesso errori a caso. 
Questo comporta peraltro che i siti in fase di asseverazione sono rigettati.
Altri hanno avuto lo stesso problema?
E' prevista una fix?

**Comment by NicolaZivago** [comment]
Ciao @MarcoTesta-EP 
confermo che anche io ho lo stesso problema, con tante schede servizio il validatore non riesce a chiudere il giro.

**Comment by danimog** [comment]
@MarcoTesta-EP  seguo anchío..

**Comment by frayber** [comment]
@MarcoTesta-EP succede anche a noi

**Comment by NicolaZivago** [comment]
Confermo anche io, che nonostante il timeout alzato, i siti con molte schede servizio tutt'ora non riescono ad essere verificati correttamente.

**Comment by smaraschin** [comment]
Stessa cosa succede anche a noi anche talvolta con messaggi di errore differenti.
Servirebbe dagli sviluppatori del tool la risoluzione del problema oppure una rassicurazione che l'asseveratore non bocci il sito per queste tipologie di errori magari proponendogli report più piccoli generati da scansioni spezzettate che dovrebbero evitare questo problema.

**Comment by tensor5** [comment]
Potete condividere l'url di un sito in fallimento per troppi servizi?

**Comment by NicolaZivago** [comment]
Ciao @tensor5 è variabile, te ne condivido un paio in privato

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
