### ISSUE TITLE
Test aggiuntivi source mapping di bootstrap-italia.bundle.min.js

### ISSUE THREAD

**Issue by marcelmastel** [italia/pa-website-validator#483]
Mancano le mappe di origine per il file JavaScript proprietario di grandi dimensioni

…js/bootstrap-italia.bundle.min.js?ver=6.5.2
Nel file JavaScript di grandi dimensioni manca una mappa di origine

Dove posso trovare il  sourceMappingURL di questo js?

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
