### ISSUE TITLE
Anomalia v2.8.5 - Falliscono i criteri C.SI.2.5 e C.SI.2.6

### ISSUE THREAD

**Issue by tommaso326** [italia/pa-website-validator#484]
Con la presente segnalo un'anomalia dell'App di Valutazione versione Win 2.8.5 che determina il fallimento dei criteri di conformità in oggetto. 
Sono stati condotti numerosi test su diverse macchine e nulla sono valsi i tentativi di svuotamento della cache del browser né, tantomeno, della cartella Users/AppData/local/temp/caxa.
Allego di seguito il codice html che interessa i criterio C.SI.2.5 e gli screenshot del report incriminato:

<div class="card shadow card-wrapper" data-element="feedback">

	<div class="cmp-rating__card-first">
	
		<div class="card-header border-0">
			
			<h2 class="title-medium-2-semi-bold mb-0" data-element="feedback-title">
				Quanto sono chiare le informazioni su questa pagina?
			</h2>
			
		</div>
		
		<div class="card-body">
			
			
			<fieldset class="rating">
				<legend class="visually-hidden sr-only"> Valuta da 1 a 5 stelle la pagina </legend>
				
				<input type="radio" id="star5a" name="ratingA" value="5" class="ng-untouched ng-pristine ng-valid">
				
				<label class="full rating-star" for="star5a" data-element="feedback-rate-5">
					<svg class="icon icon-sm" role="img" aria-labelledby="5-star">
						<use href="#it-star-full"></use>
					</svg>
					<span class="visually-hidden" id="5-star">Valuta 5 stelle su 5</span>
				</label>
				
				<input type="radio" id="star4a" name="ratingA" value="4" class="ng-untouched ng-pristine ng-valid">
				<label class="full rating-star" for="star4a" data-element="feedback-rate-4">
					<svg class="icon icon-sm" role="img" aria-labelledby="4-star">
						<use href="#it-star-full"></use>
					</svg>
					<span class="visually-hidden" id="4-star">Valuta 4 stelle su 5</span>
				</label>
				
				<input type="radio" id="star3a" name="ratingA" value="3" class="ng-untouched ng-pristine ng-valid">
				<label class="full rating-star" for="star3a" data-element="feedback-rate-3">
					<svg class="icon icon-sm" role="img" aria-labelledby="3-star">
						<use href="#it-star-full"></use>
					</svg>
					<span class="visually-hidden" id="3-star">Valuta 3 stelle su 5</span>
				</label>
				
				<input type="radio" id="star2a" name="ratingA" value="2" class="ng-untouched ng-pristine ng-valid">
				<label class="full rating-star" for="star2a" data-element="feedback-rate-2">
					<svg class="icon icon-sm" role="img" aria-labelledby="2-star">
						<use href="#it-star-full"></use>
					</svg>
					<span class="visually-hidden" id="2-star">Valuta 2 stelle su 5</span>
				</label>
				
				<input type="radio" id="star1a" name="ratingA" value="1" class="ng-untouched ng-pristine ng-valid">
				<label class="full rating-star" for="star1a" data-element="feedback-rate-1">
					<svg class="icon icon-sm" role="img" aria-labelledby="1-star">
						<use href="#it-star-full"></use>
					</svg>
					<span class="visually-hidden" id="1-star">Valuta 1 stelle su 5</span>
				</label>
				
			</fieldset>
		</div>
	</div>
	
	
	
	<div class="cmp-rating__card-second d-none" data-step="3">
		<div class="card-header border-0">
			<h2 class="title-medium-2-bold mb-0" id="rating-feedback">
				Grazie, il tuo parere ci aiuterà a migliorare il
				servizio!
			</h2>
		</div>
	</div>
	<div class="form-rating d-none">
		<div class="d-none rating-shadow" data-step="1">
			<div class="cmp-steps-rating">
				
				<fieldset class="fieldset-rating-one d-none" data-element="feedback-rating-positive">
					
					<h3 class="step-title d-flex align-items-center justify-content-between drop-shadow">
						<legend class="iscrizioni-header w-100" data-element="feedback-rating-question">
							Quali sono stati gli aspetti che hai preferito? <span class="step">1/2</span>
						</legend>
					</h3>
					
					<div class="cmp-steps-rating__body">
						<div class="cmp-radio-list">
							<div class="card-teaser shadow-rating">
								<div class="card-body">
									<div class="form-check m-0">
										
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating1" type="radio" id="radio-1">
											<label for="radio-1" data-element="feedback-rating-answer">Le indicazioni erano chiare</label>
										</div>
										
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating1" type="radio" id="radio-2">
											<label for="radio-2" data-element="feedback-rating-answer">Le indicazioni erano complete</label>
										</div>
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating1" type="radio" id="radio-3">
											<label for="radio-3" data-element="feedback-rating-answer">Capivo sempre che stavo procedendo correttamente</label>
										</div>
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating1" type="radio" id="radio-4">
											<label for="radio-4" data-element="feedback-rating-answer">Non ho avuto problemi tecnici</label>
										</div>
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating1" type="radio" id="radio-5">
											<label for="radio-5" data-element="feedback-rating-answer">Altro</label>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</fieldset>
				
				
				
				<fieldset class="fieldset-rating-two d-none" data-element="feedback-rating-negative">
					
					<h3 class="step-title d-flex align-items-center justify-content-between drop-shadow">
						<legend class="iscrizioni-header w-100" data-element="feedback-rating-question">
							Dove hai incontrato le maggiori difficoltà?<span class="step">1/2</span>
						</legend>
					</h3>
					
					<div class="cmp-steps-rating__body">
						<div class="cmp-radio-list">
							<div class="card-teaser shadow-rating">
								<div class="card-body">
									<div class="form-check m-0">
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating2" type="radio" id="radio-6">
											<label for="radio-6" data-element="feedback-rating-answer">A volte le indicazioni non erano chiare</label>
										</div>
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating2" type="radio" id="radio-7">
											<label for="radio-7" data-element="feedback-rating-answer">A volte le indicazioni non erano complete</label>
										</div>
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating2" type="radio" id="radio-8">
											<label for="radio-8" data-element="feedback-rating-answer">A volte non capivo se stavo procedendo correttamente</label>
										</div>
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating2" type="radio" id="radio-9">
											<label for="radio-9" data-element="feedback-rating-answer">Ho avuto problemi tecnici</label>
										</div>
										<div class="radio-body border-bottom border-light cmp-radio-list__item">
											<input name="rating2" type="radio" id="radio-10">
											<label for="radio-10" data-element="feedback-rating-answer">Altro</label>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</fieldset>
				
			</div>
		</div>
		
		
		<div class="d-none" data-step="2">
			<div class="cmp-steps-rating">
				
				<fieldset>
					<legend class="iscrizioni-header w-100">
						<h3 class="step-title d-flex align-items-center justify-content-between drop-shadow mb-4">
							<span class="d-block d-lg-inline">Vuoi aggiungere altri dettagli?</span>
							<span class="step">2/2</span>

						</h3>
					</legend>
					<div class="cmp-steps-rating__body">
						<div class="form-group shadow-rating">
							<label for="formGroupExampleInputWithHelp">Dettaglio</label>
							<input class="form-control" id="formGroupExampleInputWithHelp" aria-describedby="formGroupExampleInputWithHelpDescription" maxlength="200" type="text" data-element="feedback-input-text">
							<small id="formGroupExampleInputWithHelpDescription" class="form-text">Inserire massimo 200 caratteri</small>
						</div>
					</div>
				</fieldset>
				
				
			</div>
		</div>
		<div class="d-flex flex-nowrap pt-4 w-100 justify-content-center">
			<button class="btn btn-outline-primary fw-bold me-4 btn-back" type="button">
			Indietro
			</button>
			<button class="btn btn-primary fw-bold btn-next" type="submit" form="rating">
			Avanti
			</button>
		</div>
	</div>
</div>
								
								
								
![C SI 2 5](https://github.com/italia/pa-website-validator/assets/139881085/843a59ed-d62c-4bc0-b62a-36f711f571a1)
![C SI 2 6](https://github.com/italia/pa-website-validator/assets/139881085/27cac08b-81e7-4099-8ba8-899607efc6bd)

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
