### ISSUE TITLE
Chiusura automatica del validatore al lancio dell'applicazione

### ISSUE THREAD

**Issue by NevisMenegatti** [italia/pa-website-validator#485]
Buongiorno!

Ho sempre avuto questo problema. A volte passa da solo, altre volte rimane per settimane e questa è una di queste. Ho appena scaricato la versione aggiornata del software (mezz'ora fa). Clicco sull'icona per lanciarlo e sia con avvio normale che come amministratore, la finestra si apre per un istante (meno di un secondo) e si chiude subito dopo. A volte mostra una schermata nera, a volte un errore che sparisce troppo in fretta per intercettarlo.
Ho effettuato una registrazione video e sono riuscita ad isolare il fotogramma in cui si vede l'errore:

![image](https://github.com/italia/pa-website-validator/assets/170412058/537cec2f-4811-47f1-b118-11174c723720)

Ci tengo a sottolineare che l'applicazione va in shutdown da sola in una frazione di secondo, quindi non ho la possibilità di seguire le istruzioni dell'ultima riga dell'immagine.

Ho: 
- riavviato il computer
- eliminato la versione vecchia del validatore
- tentato di lanciarlo come amministratore
- l'errore accade anche su più dispositivi. Lo screenshot viene da un laptop, ma il desktop si comporta nella medesima maniera.

Qualcuno sa come risolverlo?
Grazie!

**Comment by VincenzoUrso** [comment]
prova questo
https://github.com/italia/pa-website-validator/issues/158

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
