### ISSUE TITLE
Il repository è ancora attivo?

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#486]
Buongiorno,
vedo che non ci sono modifiche nel repository dal 10/04/2024 e che l'ultima fix non è ancora stata rilasciata. A mio parere alcune delle issue pendenti andrebbero sistemate considerato che le asseverazioni PNRR dipendono da questo tool.
Ci sono fix previste per il futuro? Se si quali?
Grazie.

Marco Testa

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
