### ISSUE TITLE
LOCALIZZAZIONE IP v2.9.0 error ?

### ISSUE THREAD

**Issue by Nonnopanda** [italia/pa-website-validator#491]
Il validatore nella nuova versione riporta che la localizzazione IP è al di fuori dell'unione europea nonostante gli IP risultano essere geolocalizzati in Italia .
Il portale in questione è pubblicato tramite AWS nella regione eu-south-1 (Milano).

**Comment by srizzati** [comment]
Mi accodo... stesso identico problema.

**Comment by claudiopizzillo** [comment]
Il validatore mi fornisce l'ip localizzato fuori dall'unione europea (RU) quando è ospitato presso l'OpenHub di Carini (Sicilia).

**Comment by SCLService** [comment]
Segnalo lo stesso problema,  l'ip localizzato in finlandia e  segnalato come se fosse in US

**Comment by tensor5** [comment]
Risolto in 639f31cc7fd8eb0e2377e4167e33aa0d1dcb21f7.
