### ISSUE TITLE
 Il rapporto di contrasto tra i colori di sfondo e primo piano non è sufficiente.

### ISSUE THREAD

**Issue by RaffaelP** [italia/pa-website-validator#501]
<img width="759" alt="Screenshot 2024-07-03 at 15 11 59" src="https://github.com/italia/pa-website-validator/assets/68069934/74a52639-d626-43ae-b422-45cfa5819350">
Abbiamo in uso il tema originale: https://www.tfo-bruneck.it/, come mai mi da questo problema?

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
