### ISSUE TITLE
Errore con puppeteer - configuration.experiments

### ISSUE THREAD

**Issue by ilbassa** [italia/pa-website-validator#503]
Dopo l'installazione dei pacchetti con 
`npm install`
mi esce questo errore
` node dist --type school --destination traces --report traces_report --website MY_WEBSITE --scope online
>>
file:///C:/Users/Michele/Progetti/pa-website-validator/node_modules/puppeteer/lib/esm/puppeteer/getConfiguration.js:98
    configuration.experiments ??= {};
                              ^^^
SyntaxError: Unexpected token '??='`

Avete suggerimenti?

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
