### ISSUE TITLE
Note legali non viene rilevata dall’APP di validazione

### ISSUE THREAD

**Issue by rosario-pellecchia** [italia/pa-website-validator#505]
Salve a tutti.
Sto procedendo alla validazione tramite l’app e fino ad ieri andava bene la terza voce “Raccomandazioni Progettuali” ora da due giorni non riesco a risolvere il problema relativo alle note legali.
Inserisco i data-element secondo quanto indicato ed ho inserito il testo indicato ma il risultato risulta essere sempre questo che allego

![git](https://github.com/user-attachments/assets/1f43f8f6-6884-4eee-9adb-cd56c06cc1dc)

il sito è il seguente: www.itimedi.edu.it

HELP HELP
Sto impazzendo. Non trovo l’anomalia.
PS ho anche azzerato l’app ma nulla di nulla

**Comment by picomiles** [comment]
Ciao, ho provato a dare un'occhiata e mi sembra si faccia riferimento ad una licenza CC-BY 4.0 Italia che ho la sensazione non esista.
Il riferimento dovrebbe a mio avviso essere CC-BY 4.0 International o semplicemente CC BY 4.0 
Io proverei entrambe le diciture per verificare quale delle due vada bene

**Comment by rosario-pellecchia** [comment]
Ciao. Fatto ma purtroppo non funziona.
La pagina è questa https://www.itimedi.edu.it/note-legali/
ed ho seguito tutte le indicazioni per avere una corretta validazione ma nulla.
Sono davvero in difficoltò a comprendere il perchè :(

**Comment by MarcoTesta-EP** [comment]
Ciao,
la dicitura deve essere esattamente questa:

In applicazione del principio open by default ai sensi dell’articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con <a href="https://creativecommons.org/licenses/by/4.0/legalcode.it" target="_blank">licenza CC-BY 4.0</a>.
Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.

Compreso il link esterno sulle parole "licenza CC-BY 4.0" come specificato nell'allegato 2.

**Comment by rosario-pellecchia** [comment]
> Ciao, la dicitura deve essere esattamente questa:
> 
> In applicazione del principio open by default ai sensi dell’articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con [licenza CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode.it). Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.
> 
> Compreso il link esterno sulle parole "licenza CC-BY 4.0" come specificato nell'allegato 2.

@MarcoTesta-EP ho fatto come da te indicato. **Nulla**. Continua a dire testo mancante o errrato

**Comment by Shero08** [comment]
Buongiorno, mi da lo stesso identico errore quando poi la valutazione l'ho fatta anche per altri istituti con la stessa dicitura senza problemi.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
