### ISSUE TITLE
Eseguibili mancanti in v2.10.1

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator#507]
Nella release di ieri v2.10.1 i soliti file eseguibili per Windows, MAC, Linux sono mancanti. E' possibile generarli?
Grazie.

**Comment by MarcoTesta-EP** [comment]
Un aggiornamento, è arrivata nuovamente la notifica ma la release ora è sparita, l'ultima disponibile è la v2.10.0

**Comment by tensor5** [comment]
Abbiamo tolto la release per un problema di build.
