### ISSUE TITLE
C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO

### ISSUE THREAD

**Issue by pditomass** [italia/pa-website-validator#518]
Per il requisito 'C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO' vengono riportati nel report gli errori su 3 servizi senza segnalare il dettaglio di quanto rilevato. Riporto di seguito la parte de report interessata.
<img width="418" alt="image" src="https://github.com/user-attachments/assets/9a975b9b-9944-4217-9986-5ec9f0c1438b">

Abbiamo effettuato verifiche su tutte le pagine delle schede di servizio:
•	I dati (tutti presenti) e il loro ordinamento sono corretti;
•	Tutti i “data-element” necessari sono presenti;
•	Il contenuto del JSON all’interno del codice della scheda servizio è formalmente corretto e valorizzato.

Il numero dei servizi presenti è > di 10.

Non capiamo proprio come risolverlo, non crediamo sia un nostro problema, ed in più è segnalato in rosso!!!

Restiamo in attesa di un vostro riscontro al più presto.

Cordiali saluti
                     Paola Di Tomasso.

**Comment by HshMatera** [comment]
Buongiorno, anche io avevo questo problema e l'ho risolto facendo esporre nell'elenco della pagina 10 servizi invece che 3. 
$max_posts = isset($_GET['max_posts']) ? $_GET['max_posts'] : 10; 
in /template-parts/servizio/tutti-servizi.php

Fai questa prova.

Ciao

**Comment by fabricius4** [comment]
> Per il requisito 'C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO' vengono riportati nel report gli errori su 3 servizi senza segnalare il dettaglio di quanto rilevato. Riporto di seguito la parte de report interessata. <img alt="image" width="418" src="https://private-user-images.githubusercontent.com/134497188/361451251-9a975b9b-9944-4217-9986-5ec9f0c1438b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTcxOTYsIm5iZiI6MTcyODk5Njg5NiwicGF0aCI6Ii8xMzQ0OTcxODgvMzYxNDUxMjUxLTlhOTc1YjliLTk5NDQtNDIxNy05OTg2LTVlYzlmMGMxNDM4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMjU0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yjk3MzMxZGYyYTAyM2FlNTU3OTMwMDViMDNkNzZkMGYyOTYwMzU4ZWY2OWE1OTU4M2FiN2NmMDFhMDQzZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oWZj1_YBY71r3lYyfOAEaz1G4gX-j2NPAO_1BBh4WSo">
> 
> Abbiamo effettuato verifiche su tutte le pagine delle schede di servizio: • I dati (tutti presenti) e il loro ordinamento sono corretti; • Tutti i “data-element” necessari sono presenti; • Il contenuto del JSON all’interno del codice della scheda servizio è formalmente corretto e valorizzato.
> 
> Il numero dei servizi presenti è > di 10.
> 
> Non capiamo proprio come risolverlo, non crediamo sia un nostro problema, ed in più è segnalato in rosso!!!
> 
> Restiamo in attesa di un vostro riscontro al più presto.
> 
> Cordiali saluti Paola Di Tomasso.

avete trovato una soluzione a questo problema? Perché anche con il suggerimento di @HshMatera il problema persiste.

**Comment by fabricius4** [comment]
> L'immagine non si riesce a scaricare del report. Il sito è in produzione è questo https://www.comune.lappano.cs.it? Perchè nella pagina servizi se ne visualizzano ancora solo 3.

no perdonami... questa è l'immagine
![Uploading servizi.jpg…]()

**Comment by HshMatera** [comment]
> Buongiorno, anche io avevo questo problema e l'ho risolto facendo esporre nell'elenco della pagina 10 servizi invece che 3. $max_posts = isset($_GET['max_posts']) ? $_GET['max_posts'] : 10; in /template-parts/servizio/tutti-servizi.php
> 
> Fai questa prova.
> 
> Ciao

Questo sicuro che lo hai inserito?

**Comment by HshMatera** [comment]
Secondo me perchè alcuni servizi, tipo "Agevolazioni scolastiche", non hanno la scheda servizio e puntano alla pagina di autenticazione SPID. Dovresti comunque fare una pagina di presentazione del servizio (scheda) e poi tramite il pulsante Accedi al servizio online puntare alla pagine autenticazione https://www.myspidcie.it/?servizio=?????

**Comment by fabricius4** [comment]
> Secondo me perchè alcuni servizi, tipo "Agevolazioni scolastiche", non hanno la scheda servizio e puntano alla pagina di autenticazione SPID. Dovresti comunque fare una pagina di presentazione del servizio (scheda) e poi tramite il pulsante Accedi al servizio online puntare alla pagine autenticazione https://www.myspidcie.it/?servizio=?????

avevo pensato la stessa cosa ma anche qui mi esce lo stesso problema, eppure le singole schede sono complete 
![ser](https://github.com/user-attachments/assets/d9604b98-43ca-4436-9145-ae599ffa0194)

**Comment by HshMatera** [comment]
https://www.comune.spezzano-albanese.cs.it/servizi/ ci sono le stesse schede non compilate.

**Comment by fabricius4** [comment]
> https://www.comune.spezzano-albanese.cs.it/servizi/ ci sono le stesse schede non compilate.

non capisco. in che senso?

**Comment by HshMatera** [comment]
[Iscrizione al trasporto scolastico](https://www.comune.spezzano-albanese.cs.it/servizio/iscrizione-trasporto-scolastico/)
[Iscrizione alla Mensa Scolatica](https://www.comune.spezzano-albanese.cs.it/servizio/iscrizione-alla-mensa-scolatica/)
[Richiedere l’accesso agli atti](https://www.comune.spezzano-albanese.cs.it/servizio/richiedere-laccesso-agli-atti/)

Questi non hanno la scheda dettaglio del servizio

**Comment by fabricius4** [comment]
> [Iscrizione al trasporto scolastico](https://www.comune.spezzano-albanese.cs.it/servizio/iscrizione-trasporto-scolastico/) [Iscrizione alla Mensa Scolatica](https://www.comune.spezzano-albanese.cs.it/servizio/iscrizione-alla-mensa-scolatica/) [Richiedere l’accesso agli atti](https://www.comune.spezzano-albanese.cs.it/servizio/richiedere-laccesso-agli-atti/)
> 
> Questi non hanno la scheda dettaglio del servizio

ma il problema lo riscontra su gli altri servizi e non su questi tre

**Comment by HshMatera** [comment]
Secondo me fai questa prova inserendo ogni scheda perchè il report quando genera quell'errore è generico quindi non ha un ordine di verifica sulle schede servizio.

**Comment by fabricius4** [comment]
> Secondo me fai questa prova inserendo ogni scheda perchè il report quando genera quell'errore è generico quindi non ha un ordine di verifica sulle schede servizio.

ah ok. provo e ti aggiorno. ok?

**Comment by pditomass** [comment]
Eccomi scusare ma è una problematica riscontrata un pò di tempo fa e quindi...
Dove non vedete le schede servizio è perchè c'è un fornitore esterno che se ne occupa. Ma il problema non era quello era il caricamento dei servizi molto lento e quindi il validatore vedeva < di 10 servizi e quindi andava in errore. In breve è stato ottimizzato il pezzo di codice che richiama i servizi esterni e migliorando questa prestazione il validatore non restituisce più l'errore.
 Grazie P@.

**Comment by fabricius4** [comment]
> Eccomi scusare ma è una problematica riscontrata un pò di tempo fa e quindi... Dove non vedete le schede servizio è perchè c'è un fornitore esterno che se ne occupa. Ma il problema non era quello era il caricamento dei servizi molto lento e quindi il validatore vedeva < di 10 servizi e quindi andava in errore. In breve è stato ottimizzato il pezzo di codice che richiama i servizi esterni e migliorando questa prestazione il validatore non restituisce più l'errore. Grazie P@.

e come avete ottimizzato? lo avete pubblicato qui?

**Comment by fabricius4** [comment]
> Secondo me fai questa prova inserendo ogni scheda perchè il report quando genera quell'errore è generico quindi non ha un ordine di verifica sulle schede servizio.

Ti confermo che il problema era questo. Infatti su uno dei due siti, sistemando e facendo visualizzare prima la scheda servizio, il validatore passa. Grazie infinite.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
