### ISSUE TITLE
Tool di validazione fallisce con servizi caricati da Maggioli via API REST tramite chiamata AJAX asincrona

### ISSUE THREAD

**Issue by marco-nanni** [italia/pa-website-validator#523]
Buongiorno,
abbiamo notato che il validatore non "vede" l'eneco dei servizi caricati tramite chiamata AJAX asincrona verso un servizio API REST remoto. In questo caso di Maggioli.
Pur  caricandoli correttamente (103 servizi) con i data-ement necessarie quant'altro, il tool di validazione non li "vede" e quindi indica l'assenza dei servizi, quando in realtà sono ben presenti e funzionanti.

**Comment by tensor5** [comment]
Puoi indicare l'url del sito?

**Comment by marco-nanni** [comment]
@tensor5 https://www.comune.castelmola.me.it/

**Comment by marco-nanni** [comment]
Buongiorno,
potreste cortesemente spiegarmi il significato del parametro "removeExternal"?
Il parametro è utilizzato dal metodo getPages().

Scoperto qualcosa in merito al comune che ho passato?

Grazie.

**Comment by tensor5** [comment]
> potreste cortesemente spiegarmi il significato del parametro "removeExternal"?
> Il parametro è utilizzato dal metodo getPages().

Serve ad eliminare dall'analisi le pagine esterne al dominio.

> Scoperto qualcosa in merito al comune che ho passato?

È ancora in analisi.

**Comment by marco-nanni** [comment]
@tensor5 immaginavo servisse a quello. 
L'ho messo a true e ora le pagine le analizza, ma non si comporta comunque correttamente.
In più, nel comune in questione, proprio non le "vede" perché l'array delle pagine da scansionare risulta vuoto.

**Comment by marco-nanni** [comment]
@tensor5 Tra le altre cose Maggioli, e Halley, sono i maggiori fornitori di servizi per gli enti locali. 
Quindi questo tipo di situazione, con il richiamo di servizi esterni tramite API, è molto comune. 
Il fatto è che se non li "vede" per qualche motivo li segnala come non presenti quando invece ce ne sono circa un centinaio.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
