### ISSUE TITLE
modelComplianceInformation score

### ISSUE THREAD

**Issue by ddmo** [italia/pa-website-validator#528]
Salve, ho eseguito più volte il test da linea di comando su ambiente linux e tutte le volte lo score della categoria modelComplianceInformation (Pacchetto Cittadino Informato: criteri di conformità) è null. 

Questo il comando utilizzato:

`node dist --type municipality --destination /root --report testreport --website https://www.comune.blablalba.it --scope online --accuracy all`

cosa sbaglio? Grazie

**Comment by ddmo** [comment]
Ho lanciato il tool da locale (la versione pacchettizzata) e restituisce risultati e segnalazioni molto diverse sullo stesso sito. Non sono allineate le versioni?

**Comment by ddmo** [comment]
Altra cosa che vedo è questo errore: 
  LH:municipality-legislation-accessibility-declaration-is-present:warn Caught exception: Possibile errore del server AGID, verificare. +24ms
  
Ma il sito di agit, dal server, è correttamente raggiungibile... questo errore c'è sempre.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
