### ISSUE TITLE
C.SI.3.2 - DICHIARAZIONE DI ACCESSIBILITÀ 

### ISSUE THREAD

**Issue by HshMatera** [italia/pa-website-validator#529]
Buongiorno,
ho eseguito la validazione con l'app comuni 2.11.1 e mi restituisce questo errore per la C.SI.3.2 - DICHIARAZIONE DI ACCESSIBILITÀ:
È dichiarata la conformità alle specifiche WCAG 2.1 --> NO

In realtà nella compilazione della dichiarazione su https://form.agid.gov.it/ è stato inserito la specifica WCAG 2.1 ma poi quando viene pubblicata questo dato non c'è e l'app non trova il riscontro. 

Grazie

![Cattura](https://github.com/user-attachments/assets/95d290fe-71ec-4520-b725-bd0ea191ab48)

**Comment by MarcoTesta-EP** [comment]
Replichiamo anche noi questo problema, grave a mio parere perchè il tool di validazione fallisce ed immagino che i progetti da oggi in avanti verranno respinti.

**Comment by tensor5** [comment]
Le pagine di AGID hanno subito degli interventi di recente, potete riprovare?

**Comment by HshMatera** [comment]
L'app di validazione non dà più alcun errore.
