### ISSUE TITLE
C.SI.2.5, C.SI.2.6 - I risultati della valutazione sono aleatori  

### ISSUE THREAD

**Issue by mmartinel** [italia/pa-website-validator#539]
L'app di valutazione (v1.11.3), lanciata più volte di seguito sullo stesso sito (https://www.comune.ceregnano.ro.it), restituisce ogni volta risultati diversi per i criteri C.SI 2.5 e C.SI 2.6.

A volte fallisce uno dei due criteri e l'altro va a buon fine, a volte accade il contrario. Più raramente vanno a buon fine entrambi. In allegato due report dell'app di valutazione, uno in cui entrambi i criteri risultano superati e uno in cui uno dei due fallisce.

[report-segnalazione.zip](https://github.com/user-attachments/files/17540681/report-segnalazione.zip)

In caso di fallimento il report mostra sempre una prima pagina in cui non viene trovato il componente di valutazione; questa pagina cambia ogni volta, può essere una qualunque scheda servizio o una qualunque altra pagina.

![image](https://github.com/user-attachments/assets/9c3d35d7-4ff8-48d7-a63f-e0f6b8179ec7)

Aggiungo infine che abbiamo cominciato a riscontrare il problema con le ultime versioni dell'app di valutazione, nei report lanciati prima dell'estate i criteri risultavano sempre superati.

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
