### ISSUE TITLE
ProtocolError - v2.11.3 dell'app di asseverazione

### ISSUE THREAD

**Issue by FrancescaFrigerio** [italia/pa-website-validator#540]
Buongiorno,
volevo segnalare che con l'ultima versione dell'app di asseverazione (v2.11.3) si presenta un errore che con le precedenti versioni non emergeva:
ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

Allego uno screen del test effettuato su un sito con versione 2.11.3:
![errore-v2 11 3](https://github.com/user-attachments/assets/cc894887-09a8-4543-be1b-3a3a34192ff7)

e del test effettuato sullo stesso sito ma con versione 2.11.2:
![v2 11 2](https://github.com/user-attachments/assets/488688b6-abae-4e6f-a3a8-23e9ed4b05ca)

Ringrazio in anticipo.
Francesca

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
