### ISSUE TITLE
R.SI.1.1 - Metatag in scheda servizio: verifica non corretta del criterio di tolleranza

### ISSUE THREAD

**Issue by enrimk** [italia/pa-website-validator#542]
Per la conformità alle ["raccomandazioni progettuali" sui metatag delle schede Servizio](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/conformita/conformita-modello-sito.html#raccomandazioni), viene indicato di usare _almeno il 50%_ dei [metatag](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/modello-sito-comunale/architettura-informazione.html#dati-strutturati-e-interoperabilita) previsti.

>   Da evitare:
>     - più del 50% dei metatag indicati non vengono utilizzati per marcare le voci delle schede servizio;

([conformita-modello-sito.rst#L627-L629](https://github.com/italia/design-comuni-docs/blob/8b639b106d5d8e990527801a63e05fdf8d591040/conformita/conformita-modello-sito.rst?plain=1#L627-L629)) 
https://github.com/italia/pa-website-validator/blob/9d9230ae7ef067d3f99f59f2342d60d36df71a33/src/storage/auditDictionary.ts#L294-L297

Quindi, la condizione di errore si dovrebbe raggiungere solo con un numero di tag mancanti _strettamente maggiore_ del 50%, e con il 50% si rientrerebbe in tolleranza.
Invece, ora si ottiene una non conformità anche con un numero di tag mancanti pari e non superiore alla soglia del 50%.

https://github.com/italia/pa-website-validator/blob/9d9230ae7ef067d3f99f59f2342d60d36df71a33/src/audits/municipality/metatagAudit.ts#L180

Può sembrare poco rilevante, senonché i tag a disposizione sono pochi, 10 in tutto, e basta una sola voce in più o in meno tra le poche disponibili per spostare decisamente l'equilibrio del test.

https://github.com/italia/pa-website-validator/blob/9d9230ae7ef067d3f99f59f2342d60d36df71a33/src/audits/municipality/metatagAudit.ts#L28

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
