### ISSUE TITLE
C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO

### ISSUE THREAD

**Issue by sjpagan** [italia/pa-website-validator#543]
Salve, Sto cercando di risolvere la problematica inerente alla validazione dei servizi, circa 3 funzionava e non capisco cosa è cambiato visto che adesso non passa più la validiazione.

Ho letto diversi topic in merito, compreso quello che parla dell'autenticazione SPID, riverificato tutto il codice e rispecchia pienamente la normativa come da voi indicato, è possibile capire in qualche modo dove si sta bloccando ?

<img width="837" alt="Screenshot 2024-11-08 alle 12 27 19" src="https://github.com/user-attachments/assets/1a8123c6-ff23-431f-a6a6-83d483232c15">

**Comment by tensor5** [comment]
Puoi dirci qual è il sito che stai testando?

**Comment by sjpagan** [comment]
si certo, è un ambiente di sviluppo quindi a breve non sarà più disponibile, però l'indirizzo è questo:

https://bellizzi.itsvil.it

**Comment by Giaimo-DTD** [comment]
Ciao @sjpagan abbiamo fatto un test e falliscono solamente i criteri della dichiarazione di accessibilità e del dominio, correttamente. Il test sulle schede informative di servizio invece viene superato.
Continui ad avere lo stesso risultato?

**Comment by tensor5** [comment]
Nuovo applicativo [qui](https://github.com/italia/pa-website-validator-gui).
