### ISSUE TITLE
Criterio C.SI.1.3 - Schede di servizio - Errore validazione ordinamento voci menu

### ISSUE THREAD

**Issue by RCPrato** [italia/pa-website-validator#546]
Buongiorno,
spostando una sola voce rispetto all'ordine previsto dal criterio C.SI.1.3 (consentito dal criterio di tolleranza) l'app di validazione non ci fa passare il test perché segnala 5 voci fuori ordine. 

Da quanto abbiamo capito lo script verifica per ogni voce la presenza della precedente e della successiva ma con questo criterio un singolo spostamento comporta obbligatoriamente la segnalazione di 5 voci errate:

- la voce spostata
- la voce che appare prima di quella spostata nella nuova posizione
- la voce che appare dopo quella spostata nella nuova posizione
- la voce che era prima di quella spostata nella posizione originale
- la voce che era dopo quella spostata nella posizione origianale

Esempio di risultato dell'app di validazione:

![immagine](https://github.com/user-attachments/assets/e718b1c0-7cba-45e1-9f2b-85f2467aada4)

**Comment by Giaimo-DTD** [comment]
Buongiorno, a breve rilasceremo una versione che dovrebbe risolvere il problema https://github.com/italia/pa-website-validator/pull/545

**Comment by tensor5** [comment]
Risolto nella release 2.11.5.

**Comment by enrimk** [comment]
@tensor5 @Giaimo-DTD 
Molto meglio quest'ultima versione, ma forse non è completamente risolto.
Funziona bene nel caso di una voce spostata _prima_ rispetto alla sequenza attesa; nel caso di una voce spostata _dopo_, mi sembra che tenda a sovrastimare. Cioè, in quel caso a risultare fuori sequenza sono tutte le altre voci che dalla mossa "guadagnano" un posto?
In ogni caso, non una sovrastima sistematica ×5 come prima.

Forse come toppa rapida si può fare la valutazione nei 2 versi opposti e prenderne il minimo (non sono sicuro)...
Ma immagino poi che in casi di estremo disordine, con roba magari spostata a caso sia prima che dopo, essere troppo precisi nel conteggio non abbia neanche senso.

**Comment by enrimk** [comment]
Un'altra cosa: perché il metodo [di prima](https://github.com/italia/pa-website-validator/blob/c8deef06c575c5abcd70c4df69881c80d20e075d/src/utils/utils.ts#L240) non è stato sostituito dovunque?
Vedo che [viene ancora usato](https://github.com/search?q=repo%3Aitalia%2Fpa-website-validator+%2FcheckOrder%5Cb%2F&type=code), ad es. [per i menù](https://github.com/italia/pa-website-validator/blob/c8deef06c575c5abcd70c4df69881c80d20e075d/src/audits/municipality/menuAudit.ts#L110): non è anche lì la stessa cosa?
