### ISSUE TITLE
Aggiornare i database GeoIP

### ISSUE THREAD

**Issue by lightuono** [italia/pa-website-validator#70]
Utilizzando il validatore mi sono accorto che la libreria **geoip-lite** utilizza dei database vecchi di 3 anni. Infatti facendo un controllo su un nostro sito, risulta con l'ip US e non IT, cosa che invece facendo un controllo sul sito di maxmind e con i database aggiornati, l'indirizzo ip risulta IT. 

È possibile utilizzare dei database più aggiornati?

**Comment by tensor5** [comment]
@lightuono grazie per la segnalazione. L'issue è stato risolto in 4d46a230b8f3d204e61be596fe312088101d7847 e 668f1312df30cae42e61f0049daa0d6c8af2849c, ed il fix è disponibile nella versione v1.0.10. Riapri l'issue se il problema si ripresenta.
