### ISSUE TITLE
Scuole - C.SC.2.1 - Pagina privacy policy indicata come non esistente

### ISSUE THREAD

**Issue by Giaimo-DTD** [italia/pa-website-validator#77]
La pagina di destinazione della privacy policy è esistente ma viene indicata come inesistente, quindi il criterio fallisce. Invece dovrebbe avere risultato giallo (perché non supera il check sulla sicurezza)
![image](https://user-images.githubusercontent.com/105422742/198062720-bbdca0f9-d21b-43fd-987c-13e41d9c6099.png)

**Comment by Giaimo-DTD** [comment]
@dg7dd nel tuo caso è presente il data-element nella voce del footer?

**Comment by dg7dd** [comment]
> @dg7dd nel tuo caso è presente il data-element nella voce del footer?

Non sono uno sviluppatore. Però sì, ho controllato e vedo che data-element "privacy-policy-link" è presente. 
Lo stesso problema me lo da pure con la Dichiarazione di accessibilità (link presente e funzionante, data-element "accessibility-link" presente).
In più, pur utilizzando il tema Design Scuole 2.0.3 su WordPress, ricevo flag giallo anche su C.SC.1.3 (Utilizzo di temi per CMS).

Per eventuali controlli, questo è il sito: istitutosignorelli.edu.it.
Se servono screenshot li allego
