### ISSUE TITLE
Comuni - C.SI.1.1 - Controllare i font in ogni titolo e paragrafo

### ISSUE THREAD

**Issue by tensor5** [italia/pa-website-validator#86]
- L’audit deve verificare che ogni titolo e paragrafo della pagina analizzata utilizzi il font Titillum Web o Lora
- Deve indicare nel risultato la pagina analizzata.

**Comment by OProf77** [comment]
Seguendo le indicazioni, ho inserito il data-element=”service-type” nelle sotto-voci del menù servizi (Famiglie e studenti - Personale Scolastico - Percorsi di studio) e il data-element="service-link" nella pagina che restituisce tutti i servizi, ma non rileva comunque i font.
Uso Drupal e gli URL delle pagine indicate sono: /servizi/famiglie-e-studenti,  /servizi/personale-scolastico,  /servizi/percorsi-di-studio

i data-element sono presenti nel tag <a>

**Comment by flaggz** [comment]
stesso problema
l'app dovrebbe validare degli elementi specifici random tipo h*, p e div vari per stabilire se il font utilizzato è quello corretto dal momento che le schede dei servizi sono raccomandate e non obbligatorie
