### ISSUE TITLE
C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO - Tipologia servizio

### ISSUE THREAD

**Issue by MassyCare99** [italia/pa-website-validator#90]
Voce obbligatoria mancante - Tipologia servizio
ma non è presente nella DOC

[https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-1-3](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it)

![Cattura](https://user-images.githubusercontent.com/102411343/198554280-2463e6d5-b9a0-41da-bcd8-a1d1427debc3.PNG)

**Comment by Giaimo-DTD** [comment]
La tipologia del servizio (categoria servizio) non viene verificata tramite data attribute, ma verificando il contenuto della breadcrumb.
Pertanto nella documentazione tecnica dell'app di valutazione viene solo indicato che ne viene verificata la presenza, senza riportarne data attribute.
Lo spiegheremo meglio nella documentazione dell'app, così come è spiegata nella [documentazione ](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/conformita/conformita-modello-sito.html)sui criteri di conformità "_Categoria del servizio (la tipologia di servizio indicata nella breadcrumb)_"
