### ISSUE TITLE
C.SI.1.6 - VOCI DI MENÙ DI PRIMO LIVELLO - HOST IIS

### ISSUE THREAD

**Issue by MassyCare99** [italia/pa-website-validator#92]
Server: Microsoft-IIS/8.5  

l'app ritorna messaggi in cui segnala di non trovare nessun data-element, in nessun sezione del sito e nemmeno le voci di primo livello

ho provato anche la pagina template-homepage.html  
statica su IIS, non trova nessun data-element

< div id="ctl00_ctl10_SiscomMenuTematicoAGID1_PanelContenitore" class="menu-wrapper">
  < a href="#" aria-label="home Nome del Comune" class="logo-hamburger">
    < svg class="icon" aria-hidden="true">
      < use href="images/svg/sprites.svg#it-pa">< /use>
    < /svg>
    < div class="it-brand-text">
      < div class="it-brand-title">Nome del Comune< /div>
    < /div>
  < /a>
  < ul class="navbar-nav" data-element="main-navigation">
    < li class="nav-item">
      < a class="nav-link" href="Amministrazionedettagli" data-element="management">Amministrazione< /a>
    < /li>
    < li class="nav-item">
      < a class="nav-link" href="Notizie" data-element="news">Novità< /a>
    < /li>
    < li class="nav-item">
      < a class="nav-link" href="Servizi" data-element="all-services">Servizi< /a>
    < /li>
    < li class="nav-item">
      < a class="nav-link" href="Guidadettagli" data-element="live">vivere il comune< /a>
    < /li>
  < /ul>
  < div class="clear">< /div>
  < ul class="navbar-nav navbar-secondary">
    < li class="nav-item">
      < a class="nav-link" href="Dettaglioargomenti.aspx?IDCategoria=74">Accesso all'informazione< /a>
    < /li>
    < li class="nav-item">
      < a class="nav-link" href="Dettaglioargomenti.aspx?IDCategoria=125">Sport< /a>
    < /li>
    < li class="nav-item">
      < a class="nav-link" href="Dettaglioargomenti.aspx?IDCategoria=130">Trasporto pubblico< /a>
    < /li>
    < li class="nav-item">
      < a class="nav-link" data-element="all-topics" href="Argomenti.aspx">
        < span class="fw-bold">Tutti gli argomenti...< /span>
      < /a>
    < /li>
  < /ul>
< /div>

**Comment by tensor5** [comment]
Ciao @MassyCare99, puoi mandarci uno screenshot dell'output dell'app?

**Comment by MassyCare99** [comment]
[Report.zip](https://github.com/italia/pa-website-validator/files/9921802/Report.zip)
allego

**Comment by MassyCare99** [comment]
![Cattura](https://user-images.githubusercontent.com/102411343/199531284-9294aa38-6722-43fb-9170-1606b1899f96.PNG)

**Comment by MassyCare99** [comment]
Buongiorno, 
se serve possiamo allegarvi in via privata il link al sito Web in questione

**Comment by MassyCare99** [comment]
ci sono novità?

> Ciao @MassyCare99, puoi mandarci uno screenshot dell'output dell'app?

**Comment by tensor5** [comment]
@MassyCare99 possiamo sentirci sul [Slack](https://slack.developers.italia.it/) così mi passi il link?

**Comment by acattaneoacn** [comment]
Ciao @MassyCare99 i data element non venivano trovati per una problematica di url scansionato. 
Se provi la nuova versione del validatore dovresti ottenere il risultato corretto.
